### ISSUE TITLE
Make UI available under a sub path

### ISSUE THREAD

**Issue by IceflowRE** [wg-easy/wg-easy#1001]
I would like to host the ui iin a subpath like `example.com/wg-easy`.

I could not find any option to already do it now.

**Comment by pheiduck** [comment]
You can use a subdomain for that case.

**Comment by IceflowRE** [comment]
> You can use a subdomain for that case.

That was not the request. I know i can use a subdomain, i explicitly asked for a subpath.

**Comment by pheiduck** [comment]
> > You can use a subdomain for that case.
> 
> That was not the request. I know i can use a subdomain, i explicitly asked for a subpath.

Well, it does not an Issue specific to wg-easy
