### ISSUE TITLE
Last connection details reset after reboot

### ISSUE THREAD

**Issue by Aransh** [wg-easy/wg-easy#1011]
**Describe the bug**
The last connection details appearing on the web is not retained after device restart.
![image](https://github.com/wg-easy/wg-easy/assets/11724502/073f125b-d48e-4587-acf1-e567a66f0a81)
Second device is the only one to connect since last reboot, first device was connected yesterday but there's no way to know.

**To Reproduce**
1. Connect client
2. Disconnect client
3. Go to web ui, see last connection status
4. Reboot device
4. Go to web ui, see last connection status is missing

**Expected behavior**
Last connection status is cached to some local file/volume, retained following reboots

**Desktop (please complete the following information):**
 - OS: Armbian
 - Version 24.2.1

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 17.5
 - Browser Safari

**Additional context**
I am not using docker, instead followed https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-without-Docker

**Comment by eandersons** [comment]
This is how `wg show` works - data is not preserved after restart, as far as I know.

If you want the connection data to be persisted, then you will have to use other tools to achieve that.
One of the options is to combine WireGuard Easy with ProCustodibus Pro. See the discussion #732 for more information.

**Comment by Trisky** [comment]
@Aransh 
I'm already able to do this by using https://github.com/tolkonepiu/wg-easy-extended

You'll need to setup Grafana as well:

![image](https://github.com/wg-easy/wg-easy/assets/8531036/13adea4f-2594-4a06-9ed6-537d871896a2)

**Comment by Aransh** [comment]
> @Aransh 
> 
> I'm already able to do this by using https://github.com/tolkonepiu/wg-easy-extended
> 
> 
> 
> You'll need to setup Grafana as well:
> 
> 
> 
> ![image](https://github.com/wg-easy/wg-easy/assets/8531036/13adea4f-2594-4a06-9ed6-537d871896a2)
> 
> 

Nice! Was not familiar with this, I don't think my poor little Orange Pi zero will be able to handle Grafana, but will keep this in my list, thanks!

**Comment by Aransh** [comment]
Now that v15 uses a databases to persist data, any chance to re-consider this?
