### ISSUE TITLE
[NOT SOLVED] Making wg-easy client addresses visible to the whole system 

### ISSUE THREAD

**Issue by dathtd119** [wg-easy/wg-easy#1016]
**Describe the bug**
This is not a bug/issue, the hidden client addresses from system is a wg-easy's function (I believe). But this made me, when using other services to monitor,configure,etc for specific client is quite impossible. This is just a solution for it

**To do this**
Referenced from this [issue's solution from wirehole](https://github.com/IAmStoxe/wirehole/issues/37)
Add these lines into **environment in docker compose**
```
environment:
      - WG_POST_UP=iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o
        %i -j ACCEPT;iptables -t nat -A POSTROUTING ! -d {wg-easy subnet} -o eth+
        -j MASQUERADE
      - WG_POST_DOWN=iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o
        %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
``` 
Remember to change **{wg-easy subnet}**.

**Comment by dathtd119** [comment]
I just let the solution sit here and close it, thanks for your services, wg-easy

**Comment by RhanCandia** [comment]
I tried the solution but I am losing access to the internet when I do this. Maybe because I am using a bridge network and assigning static internal addresses for services I want to hide in the VPN network.

Like so:
```
    networks:
      some-net:
        ipv4_address: 10.6.0.1

networks:
  some-net:
    external: true
    name: some-net
```

I tried to replace the {wg-easy subnet} with the subnet of the eg-easy container (which I extracted from `docket network inspect some-net`). But still losing the internet. After restoring to my previous compose and visiting Pi-hole I can see that there are now new IPs from testing but not able to connect to the internet. Is it because I also have unbound?

**Comment by dathtd119** [comment]
> I tried the solution but I am losing access to the internet when I do this. Maybe because I am using a bridge network and assigning static internal addresses for services I want to hide in the VPN network.
> 
> Like so:
> 
> ```
>     networks:
>       some-net:
>         ipv4_address: 10.6.0.1
> 
> networks:
>   some-net:
>     external: true
>     name: some-net
> ```
> 
> I tried to replace the {wg-easy subnet} with the subnet of the eg-easy container (which I extracted from `docket network inspect some-net`). But still losing the internet. After restoring to my previous compose and visiting Pi-hole I can see that there are now new IPs from testing but not able to connect to the internet. Is it because I also have unbound?
> 
> I tried with the `some-net`'s subnet. I can connect to the internet but Pi-hole just registers requests from wg-easy.some-net. I tried with `wg-easy`'s subnet (which was listed under `some-net` in the docker network inspect as 10.6.0.1/24). Now it registers the IP of the clients in the Pi-hole but client's can't connect to the internet.

Hi, thanks for checking my solution. I forgot to go back to this issue to reopen it since I ran into the same issue as you, and then I just skip it.
I'm gonna reopen this for further solution.
