### ISSUE TITLE
Changing WG_DEFAULT_ADDRESS does not update wg0.json and wg0.config files accordingly

### ISSUE THREAD

**Issue by davidacampos** [wg-easy/wg-easy#1031]
**Describe the bug**
While using docker compose, when changing WG_DEFAULT_ADDRESS after having already ran `docker compose up` once, then it does not update wg0.json nor wg0.config files accordingly. This causes routing rules to not work as expected. Meaning if allowing 0.0.0.0 you can only ping the host but not route all traffic (and more potential issues).

**To Reproduce**
1. Using docker compose, bring up the service using the default values from https://raw.githubusercontent.com/wg-easy/wg-easy/master/docker-compose.yml
2. Modify the docker-compose.yml by adding `WG_DEFAULT_ADDRESS=10.8.1.x`
3. Reload the service with `docker compose up`
4. Everything "seems" to work, but the routing should be messed up, as wg0.json and wg0.conf still use `10.8.0.1` as the server IP (which is the default value) instead of the newly defined `10.8.1.1`

**Expected behavior**
Either to update the files appropriately (wg0.conf and wg0.json) or document that this is not allowed and a possible workaround

**Additional context**
This might be expected, but might be good idea to add it to the documentation section that it requires either to delete the docker volume or to modify both files manually, as this is a difficult bug to track.

This issue is because in https://github.com/wg-easy/wg-easy/blob/master/src/lib/WireGuard.js#L40 the initial config is generated just once and never modified again, unless the file is deleted

**Comment by jsovalles** [comment]
Can confirm, I was having trouble trying to check different default addresses but wg-easy always uses `10.8.0.1`

**Comment by darren-trottier** [comment]
Same issue here, cannot get the wg0.conf to be updated

**Comment by petr-ujezdsky** [comment]
This is docker stuff. Once you create a docker container via compose, you can not alter its configuration via `docker-compose.yml` (eg. after stopping it). You have to `docker compose down` to delete whole stack and start again with `docker compose up`.

**Comment by eandersons** [comment]
> This is docker stuff. Once you create a docker container via compose, you can not alter its configuration via `docker-compose.yml` (eg. after stopping it). You have to `docker compose down` to delete whole stack and start again with `docker compose up`.

`docker compose down` is not necessary as `docker compose up` will automatically recreate the container if changes for the corresponding service in Compose file(s) have been detected.
From [`docker compose up` documentation](https://docs.docker.com/reference/cli/docker/compose/up/):

> If there are existing containers for a service, and the service’s configuration or image was changed after the container’s creation, `docker compose up` picks up the changes by stopping and recreating the containers (preserving mounted volumes). To prevent Compose from picking up changes, use the `--no-recreate` flag.

**Comment by Mask-Vip** [comment]
Yes, I also had the same issue, the problem was fixed after manually modifying the file and deleting the container and re-establishing it. Thank you davidacampos for the reminder.

**Comment by spali** [comment]
Can confirm the problem. On every new start of the container, the address in `[interface]` in `wg0.conf` gets reset to 10.8.0.1. Even WG_DEFAULT_ADDRESS is set to something else.

**Comment by spali** [comment]
Ok, got a "permanent" workaround. The 10.8.0 was still in the `wg0.json` and ended up due this in the `wg0.conf`. After manually changing the `json` it worked.
So the point is... as soon as a `json` exists, the WG_DEFAULT_ADDRESS does only affect clients, but not the server interface address.
