### ISSUE TITLE
Unable to connect after upgrade to version 13 

### ISSUE THREAD

**Issue by corasaniti** [wg-easy/wg-easy#1032]
With the upgrade to version 13 I cannot connect with my mobile phone to the VPN of my Raspberry Pi5 (Debian bookworm based OS).
In the logs I see the connection but in reality I am not connected, in fact the connection point is not visible.

If I downgrade to version 12 everything starts working properly again, so the portforward in my router is certainly configured correctly.
I await your news

Thank you

**Comment by bkmartin** [comment]
I see the same thing, I had to revert back to 12 from latest to get working again

**Comment by xianren78** [comment]
same problem here. downgrade to 12 works good

**Comment by matthabjan** [comment]
I have the exact same issue with a Raspberry Pi 4 here.

**Comment by sshpem** [comment]
perhaps the problem is WG_PORT, I found if you change WG_PORT, the container wireguard listen port will change to WG_PORT. It always be 51820 in previous version. run "docker exec container_name netstat -nal" to check it

**Comment by alvinleongcw** [comment]
i have the same issue of wg-easy because not working after updated. right before update, i want connecting and streaming and after my watchtower autoupdate.boom not working anymore.
i am using debian lxc in proxmox

**Comment by kaaax0815** [comment]
Look at #1034

**Comment by corasaniti** [comment]
I confirm that it is the port issue that is not working.  If I use the default port it works perfectly but if I pass the WG_PORT parameter with a custom port it doesn't work.

This is my docker run.  With the same docker run command everything works perfectly if I delete WG_PORT parameter and the default port 51820 is used

```
docker run -d 
   --name=wireguard-dyn-easy 
   --hostname=wg-easy 
   -e WG_HOST=xxxxxxxx 
   -e PASSWORD=xxxxxxx 
   -e TZ=Europe/Rome 
   -e WG_PORT=51830 
   -e LANG=en 
   -v ${PWD}/data/:/etc/wireguard 
   -p 51830:51820/udp 
   -p 51821:51821/tcp 
   --cap-add=NET_ADMIN 
   --cap-add=SYS_MODULE 
   --sysctl="net.ipv4.conf.all.src_valid_mark=1" 
   --sysctl="net.ipv4.ip_forward=1" 
   --restart always 
   ghcr.io/wg-easy/wg-easy:latest
```

**Comment by kaaax0815** [comment]
Change this `-p 51830:51820/udp` to the port you are using. if you have `WG_HOST=123`. use `-p 123:123/udp`

**Comment by corasaniti** [comment]
@kaaax0815 

Wooooooooooow. It works perfectly. I believe that is the correct behavior. If I map a custom port the server inside the container must be running on that port.
Thanks for the tip

**Comment by carfanatic93** [comment]
@kaaax0815 ty !!

Fixef it also for me.

**Comment by matthabjan** [comment]
> Change `-p 51830:51820/udp` to the port you are using. if you have `WG_HOST=123`. use `-p 123:123/udp`

Yes, that works! Thank you for providing the "fix".

**Comment by thegeekboyz** [comment]
> Change `-p 51830:51820/udp` to the port you are using. if you have `WG_HOST=123`. use `-p 123:123/udp`

confirmed working for all my custorm ports docker. thanks

**Comment by ddakrd** [comment]
Same problem

**Comment by stanthewizzard** [comment]
confirmed worked for me too

**Comment by pheiduck** [comment]
Please test: `ghcr.io/wg-easy/wg-easy:development`

**Comment by bkmartin** [comment]
@pheiduck I assume the dev branch reverts the change so that 51820 will be the listening port in the container.  is that old behavior the intended behavior moving forward?

**Comment by corasaniti** [comment]
@pheiduck 

Tried the `development `tag with the following docker run and it didn't work. I downgrade  to version 12. 
Could you please clarify, because I don't understand what the default behavior will be. If port 51820 will be the default one listening in the container
Thank you

```
docker run -d \
   --name=wireguard-dyn-easy \
   --hostname=wg-easy \
   -e WG_HOST=gallarate.dyndns-at-home.com \
   -e PASSWORD=paxlil77 \
   -e TZ=Europe/Rome \
   -e WG_PORT=51830 \
   -e LANG=en \
   -v ${PWD}/data/:/etc/wireguard \
   -p 51830:51820/udp \
   -p 51821:51821/tcp \
   --cap-add=NET_ADMIN \
   --cap-add=SYS_MODULE \
   --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
   --sysctl="net.ipv4.ip_forward=1" \
   --restart always \
   ghcr.io/wg-easy/wg-easy:development
```

**Comment by pheiduck** [comment]
`-e PORT=51821 \` is missing

**Comment by bkmartin** [comment]
@pheiduck your latest statements are unclear.   the readne says the container will listen on 51820 inside the container, no matter what value is set for WG_PORT.   The current observed behavior is the container listens on WG_PORT inside the container on both the development and latest branches.   This is why so many people with non default WG_PORT were broken by this release.  The question is, what behavior should be expected moving forward?  Will the readme be updated?

**Comment by corasaniti** [comment]
The problem is not the Web port but the Server port. Tried this docker run and it didn't work, I can't connect.

```
docker run -d \
   --name=wireguard-dyn-easy \
   --hostname=wg-easy \
   -e WG_HOST=xxxxxxxx  \
   -e PASSWORD=xxxxxxxx \
   -e TZ=Europe/Rome \
   -e WG_PORT=51830 \
   -e PORT=51821 \
   -e LANG=en \
   -v ${PWD}/data/:/etc/wireguard \
   -p 51830:51820/udp \
   -p 51821:51821/tcp \
   --cap-add=NET_ADMIN \
   --cap-add=SYS_MODULE \
   --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
   --sysctl="net.ipv4.ip_forward=1" \
   --restart always \
   ghcr.io/wg-easy/wg-easy:development

```

Can you say what the default behavior will be? The port listening on the server in the container will be 51820 regardless of the WG_PORT env parameter?
Thanks in advance

**Comment by tommy077** [comment]
> Change `-p 51830:51820/udp` to the port you are using. if you have `WG_HOST=123` use `-p 123:123/udp`

thx @kaaax0815 for the quick fix

**Comment by bkmartin** [comment]
@tommy077 we understand the workaround, the question now is what is the documented behavior going forward as the readme does not match what is happening.   will the next build revert the behavior to documented behavior?  will the docs change to say the listening port inside the container will be WG_PORT?   to get to closure here either 1) the doc needs to be updated or the 2) the new behavior should be reverted so the doc is correct

**Comment by bkmartin** [comment]
fyi, here is the commit that changed the behavior to not match the docs

https://github.com/wg-easy/wg-easy/commit/187888e078c575e2b12ac91db692f3c33283239a

**Comment by kaaax0815** [comment]
> @tommy077 we understand the workaround, the question now is what is the documented behavior going forward as the readme does not match what is happening.   will the next build revert the behavior to documented behavior?  will the docs change to say the listening port inside the container will be WG_PORT?   to get to closure here either 1) the doc needs to be updated or the 2) the new behavior should be reverted so the doc is correct

1) makes most sense

**Comment by thegeekboyz** [comment]
there must be a very good valid solid reason to make an unannounced breaking change that makes all using it to with non working docker without a clue unless come here. so why the change? if not a solid reason for change why not keep the same unless is is something planned in future? no going is gonna change the docker listening port anyway. why make this so unintuiative uninformed breaking change so i guess there must be a very solid reason

**Comment by kaaax0815** [comment]
that changing the WG_PORT variable changes on what port wireguard listens makes the most sense.
i dont think the implementation is the problem but more the missing communication

**Comment by fernandeusto** [comment]
> El problema no es el puerto Web sino el puerto Server. Intré a este atador corrió y no funcionó, no puedo conectarme.
> 
> ```
> docker run -d \
>    --name=wireguard-dyn-easy \
>    --hostname=wg-easy \
>    -e WG_HOST=xxxxxxxx  \
>    -e PASSWORD=xxxxxxxx \
>    -e TZ=Europe/Rome \
>    -e WG_PORT=51830 \
>    -e PORT=51821 \
>    -e LANG=en \
>    -v ${PWD}/data/:/etc/wireguard \
>     \
>    -p 51821:51821/tcp \
>    --cap-add=NET_ADMIN \
>    --cap-add=SYS_MODULE \
>    --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
>    --sysctl="net.ipv4.ip_forward=1" \
>    --restart always \
>    ghcr.io/wg-easy/wg-easy:development
> ```
> 
> Puedes decir cuál será el comportamiento predeterminado? El puerto que escucha en el servidor del contenedor será de 51820 independientemente del parámetro WG-PORT env? Gracias de antemano

You can use:
WG_PORT=51830   and  -p 51830:51830/udp

or comment # WG_PORT = xxx and -p 51830:51820/udp

**Comment by c0state** [comment]
I assumed that this change was inadvertent because what port it listens to internally doesn't matter (I believe), but changing it breaks existing config. For example, I use the docker-compose set up, so I had to change:
```
...
ports:
      - "59990:51820/udp"
      - "59991:51821/tcp"
...
```
to
```
ports:
      - "59990:59990/udp"
      - "59991:59991/tcp"
```
since I set both `PORT` and `WG_PORT` to custom ports.

I've updated to the "new" convention, but as other's have mentioned, it's unclear if the intent now is to revert or keep this new convention.

**Comment by bkmartin** [comment]
> You can use: WG_PORT=51830 and -p 51830:51830/udp
> 
> or comment # WG_PORT = xxx and -p 51830:51820/udp

Your second option would not be a good one since the generated client configs would have port 51820, but your server is actually listening on 51830.   The only really valid workaround here is your first one or just use all defaults of 51820.

**Comment by Codelica** [comment]
Incorrect docs aside, there seems to still be a bug here in that the default template for `PostUp` and `PostDown` aren't using the custom port if `WG_PORT` is supplied.  They are still hardcoded to 51820: https://github.com/wg-easy/wg-easy/blob/master/src/config.js#L28

**Comment by pheiduck** [comment]
Please try latest dev

**Comment by gratituliarity** [comment]
For usage with `development` image:
if you want to use port `58999`
make sure
`WG_PORT=58999`
AND CHANGE BOTH HOST AND CONTAINER PORT TO WG_PORT's value:
`58999:58999/udp`

changing only the host port like before does not work for me

**Comment by hubgit443** [comment]
It's working now~
  -e WG_CONFIG_PORT=51840 \
  -p 51840:51820/udp \

**Comment by dylif** [comment]
What if I want the generated config files to have one port, and the docker container to listen on different port? Explicitly, I want the container to listen on 51820 and my config files to have 53 as the endpoint port. I need this because my Port Forwarding on my router is set to route UDP port 53 to 51820 on my server. It seems this setup isn't possible with the recent update.

**Comment by corasaniti** [comment]
try this

-e WG_CONFIG_PORT=53
-p 53:53/udp \

**Comment by dylif** [comment]
My apologies. I realized that this can be solved quite simply by setting `WG_PORT=53` and mapping host 51820/udp to container 53/udp with `-p 51820:53/udp`.

**Comment by kaaax0815** [comment]
> The change of WG_PORT to WG_CONFIG_PORT should be front and center in changelogs and docs if it isn't already.

It didnt change from WG_PORT to WG_CONFIG_PORT therefore no such documentation is needed. Just the behavior of WG_PORT changed

**Comment by corasaniti** [comment]
Let's clarify. Now the WG_PORT parameter specifies the execution port of the Server inside the Container.
So if you want to use a custom port for example 5656 for the server and 5555 for the web interface port you have to set the environment parameters

```
 -e WG_PORT=5656 \
 -e PORT=5555 \
```

and then map the Docker with the following ports

```
 -p 5656 :5656 /udp \
 -p 5555 :5555 /tcp \
```
