### ISSUE TITLE
Cannot access web UI after upgrade to v13

### ISSUE THREAD

**Issue by TheRealC0unt** [wg-easy/wg-easy#1035]
After upgrading to the latest wg-easy release v13, dockerless mode, I cannot access the web UI any longer.
Whenever I try to access the UI, I'm receiving a 404 error, packed in a JSON response:

`{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /",
  "stack": []
}`

v12 did run flawlessly. Since none of the logs I am aware of helps to pin down the cause of the issue, I unfortunately have to ask here.
What am I missing? I followed the instructions on how to install and run wg-easy without docker to the letter.

Wireguard itself, btw, still works. My clients (around a dozen) can connect, so my educated guess is that the web UI serving part cannot access /www or some asset in it for some reason.

**Comment by pheiduck** [comment]
Please test: `ghcr.io/wg-easy/wg-easy:development`

**Comment by pheiduck** [comment]
> Is it required to upgrade to nodejs20?

Nope, but its more secure. ;)

**Comment by pheiduck** [comment]
You followed the upgrade path right?:

```
git clone https://github.com/wg-easy/wg-easy # do this if you dont have the repository cloned aldready
cd wg-easy
git checkout production
git pull
rm -rf /app /node_modules
mv src /app
cd /app
npm ci --omit=dev
cp node_modules ..
```

**Comment by tianiue** [comment]
Delete ‘’-e PORT=51821 \‘’

**Comment by pheiduck** [comment]
systemd service is running?

**Comment by Aransh** [comment]
Same issue here, service is running (and working, able to connect), but UI does not

**Comment by ramsnerm** [comment]
I have the same issue updating an LCX on Proxmox. Connection working but GUI not.

**Comment by Aransh** [comment]
I tried reverting for now (moved back to commit c5d328be2a59a4d39584a841b6a261fdf7e22484, the one I was using before the update) but still getting the same error... I wonder if it might be related to some unversioned dependency?

**Comment by Aransh** [comment]
> Damn, guess I found it. 
> 
> 
> 
> In ../lib/Server.js, there is that "const publicDir" row, pointing to "www", a relative path. I changed it to "/app/www" now, just as another try, restarted the service, and voilà, the UI interface works again. Guys, that's really silly, why did it work fine with the previous versions and now it doesn't? And why does QA not recognize such a deal breaker?
> 
> 
> 
> Strong suggestion for upcoming releases: make the path of the www directory another configuration switch. I'm generally not happy about its location, I'd rather place it to /var/www where it usually belongs on linux machines.
> 
> 
> 
> Edit: found the culprit. You fucked it up in Commit https://github.com/wg-easy/wg-easy/commit/e8a160b14ff05444ea3066abdd205ab9d33398f2, by removing row 29 and replacing it with the new const row at the script end, where the path adjustment went MIA.

Worked for me indeed, thanks!

**Comment by ramsnerm** [comment]
> Damn, guess I found it.
> 
> In ../lib/Server.js, there is that "const publicDir" row, pointing to "www", a relative path. I changed it to "/app/www" now, just as another try, restarted the service, and voilà, the UI interface works again. Guys, that's really silly, why did it work fine with the previous versions and now it doesn't? And why does QA not recognize such a deal breaker?
> 
> Strong suggestion for upcoming releases: make the path of the www directory another configuration switch. I'm generally not happy about its location, I'd rather place it to /var/www where it usually belongs on linux machines.
> 
> Edit: found the culprit. You fucked it up in Commit [e8a160b](https://github.com/wg-easy/wg-easy/commit/e8a160b14ff05444ea3066abdd205ab9d33398f2), by removing row 29 and replacing it with the new const row at the script end, where the path adjustment went MIA.

Worked for me too.

**Comment by pheiduck** [comment]
> Damn, guess I found it.
> 
> In ../lib/Server.js, there is that "const publicDir" row, pointing to "www", a relative path. I changed it to "/app/www" now, just as another try, restarted the service, and voilà, the UI interface works again. Guys, that's really silly, why did it work fine with the previous versions and now it doesn't? And why does QA not recognize such a deal breaker?
> 
> Strong suggestion for upcoming releases: make the path of the www directory another configuration switch. I'm generally not happy about its location, I'd rather place it to /var/www where it usually belongs on linux machines.
> 
> Edit: found the culprit. You fucked it up in Commit [e8a160b](https://github.com/wg-easy/wg-easy/commit/e8a160b14ff05444ea3066abdd205ab9d33398f2), by removing row 29 and replacing it with the new const row at the script end, where the path adjustment went MIA.

Please to a PR, then I will do a patch release for everyone thanks to find the issue! @TheRealC0unt

**Comment by pheiduck** [comment]
@TheRealC0unt okay I will do the PR later. with have dev builds for docker so we can test before release…

**Comment by pheiduck** [comment]
Please test new agian: ghcr.io/wg-easy/wg-easy:development
