### ISSUE TITLE
add support for docker secrets

### ISSUE THREAD

**Issue by carmatana** [wg-easy/wg-easy#1062]
Hello,

the following issue (closed) says that the solution to manage secrets is using .env file

https://github.com/wg-easy/wg-easy/pull/169

that is not correct as env file is equivalente to having the variables in docker compose

Secrets work differently:

https://docs.docker.com/engine/swarm/secrets/

https://docs.docker.com/compose/use-secrets/

It would be nice to have this implemented

**Comment by pheiduck** [comment]
Make a PR to implement it. ;)

**Comment by pheiduck** [comment]
As I was dig into it, I discovered that secrets only work in docker swarm.
So I worked on a `.env`file, but its may less secure the the secrets...

**Comment by carmatana** [comment]
Thanks @pheiduck 

What is a PR and how do I make one ?

Secrets also work with docker-compose, not only in swarm.

I do not have swarm but I have other containers using secrets as variable values:


https://docs.docker.com/compose/use-secrets/

**Comment by pheiduck** [comment]
@carmatana https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by kaaax0815** [comment]
@pheiduck Whats the status on this? Should we implement this?

**Comment by kaaax0815** [comment]
No sensitive env variables are used anymore in #1333. Maybe we could close this?
