### ISSUE TITLE
Security vulnerability found in the Web UI

### ISSUE THREAD

**Issue by davide-acanfora** [wg-easy/wg-easy#1067]
Hi, I just found a vulnerability involving the Web UI when it is publicly exposed to a malicious attacker. Since the flaw allows access to any file inside the container (even files containing client keys) without logging in, I don't know if this is the right place to talk about it. Should I contact someone or can I describe it here?

**Comment by pheiduck** [comment]
Please contact @WeeJeWel. Are you able to make fix for that?

**Comment by pheiduck** [comment]
We have a signal channel maybe we could invite you.

**Comment by peterlewis** [comment]
Unlocked conversation as otherwise @davide-acanfora will not be able to reply, I don't think...

@davide-acanfora, do you have Signal?

**Comment by davide-acanfora** [comment]
No problem, I had planned to email @WeeJeWel, but then I got carried away with fixing the code.

@pheiduck yes https://signal.me/#eu/vY_YuF5sAp2wKLBCxAlIAZe6eBt8jvjBcnbn_vsyoxtIs4wPrtZE54uQ84okIVgH

**Comment by peterlewis** [comment]
Thanks, Davide. I've invited you to the Signal channel.

**Comment by peterlewis** [comment]
Thank you, @davide-acanfora for your hard work on resolving this so quickly!
