### ISSUE TITLE
Unauthorized when log in Web UI [Can’t log in]

### ISSUE THREAD

**Issue by explosik** [wg-easy/wg-easy#1068]
Unauthorized when log in Web UI [Can’t log in]

1. Clear install
2. Wg-easy:13
3. When I trying log in myip:51831 web ui it says UNAUTHORIZED. Cant LOG IN!

Please help somebody!

 - Ubuntu 24.04 server vps
 - Safari
 - iPhone 14 Pro Max
![IMG_7869](https://github.com/wg-easy/wg-easy/assets/35393058/3bf345ad-731a-47e8-a28e-2dd27042eb30)

**Comment by explosik** [comment]
COMPLETED! ✅ The problem was the password that was too complicated!

**Comment by pheiduck** [comment]
Long time no see „3G“ 😄

**Comment by explosik** [comment]
> Long time no see „3G“ 😄

In the basement, dude 😀
