### ISSUE TITLE
Can't create more when one user

### ISSUE THREAD

**Issue by LordPanda95** [wg-easy/wg-easy#1069]
The server does not allow to create more than one client

1. Go to web-ui
2. Click on "New"
3. Input new client name

Screenshots
<img width="777" alt="Screenshot 2024-05-25 at 15 16 56" src="https://github.com/wg-easy/wg-easy/assets/22136377/b2278a6e-90f0-4eaf-a00a-819ea9d38327">
<img width="466" alt="Screenshot 2024-05-25 at 15 16 39" src="https://github.com/wg-easy/wg-easy/assets/22136377/515dffd8-2bde-4f91-920b-21eddaa12017">
<img width="548" alt="Screenshot 2024-05-25 at 15 16 34" src="https://github.com/wg-easy/wg-easy/assets/22136377/54b09aaf-e29f-4e44-beb8-03f4c6eba9d1">
<img width="803" alt="Screenshot 2024-05-25 at 15 16 22" src="https://github.com/wg-easy/wg-easy/assets/22136377/c3192d9f-80e7-4cc3-80d8-200a89c21f51">

Use docker image "ghcr.io/wg-easy/wg-easy:13" arm64 on raspberry pi 5

**Comment by pheiduck** [comment]
I can't reproduce this on v13.

**Comment by eandersons** [comment]
Sounds like #669, #62 and #470.

**Comment by LordPanda95** [comment]
Thanks, I can fix it by changing
WG_DEFAULT_ADDRESS=10.8.0.1
to
WG_DEFAULT_ADDRESS=10.8.0.x
