### ISSUE TITLE
[FEATURE PROPOSAL] handle /16 & /8 Subnets

### ISSUE THREAD

**Issue by gganster** [wg-easy/wg-easy#1083]
Hi,

For IOT purpose with lot of rasberry pi (>255) and VNC needs. Ive modified wg-easy for /16 mask and unlock habilities to have more than 65 000 clients. 

Are you interested by a PR ?

No more configuration needed and retro compatible. It use your existing WG_DEFAULT_ADDRESS env variable to define the mask.

ex: 
4.2.0.x  ->  /24
4.2.x.x  ->  /16

Happy coding.

**Comment by pheiduck** [comment]
Are you interested by a PR ?
Yep 😄

**Comment by gganster** [comment]
Hi,

PR created #1087

**Comment by bmarinov** [comment]
Hey, I just hit this issue and sadly this wouldn't be enough to cover my case. I am on a `/20` network and just realized, that wg-easy generates configuration for `/24`. Can we also add a separate, optional configuration value for the subnet? Out of scope here, but definitely needed IMO.

Many valid network configurations cannot be inferred, especially once you start adding VLANs into the mix and separate in smaller networks. Im planning to split my /20 in two /21 subnets for example.

**Comment by kaaax0815** [comment]
Implemented with #1347
