### ISSUE TITLE
No outside connection on WG VPN(?) (Mostly need help???)

### ISSUE THREAD

**Issue by KaapaTeelb** [wg-easy/wg-easy#1092]
No outside connection on WG VPN(?)

I installed the wg-easy via the guide at cloudzy vps (Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-92-generic x86_64), 24,*, 20.* too) (<- support ticked claimed they do not have any connection restrictions)
I can access the wg-easy hosted website via the ip to set it up. (http:// (ip) :51821/)
I can make the client.
I can connect to vpn from smarthphone or pc, but. There is no outside connection.
![image](https://github.com/wg-easy/wg-easy/assets/8286113/32a1506c-29b7-475c-897c-80ee6a682589)

I did set up openvpn as a test, and it did work. But wireguard/neither wg-easy didnt really work?
I tried reinstalling both clean, openvpn is the only one worked, I also tried installing default wireguard, via the tutorials, stuff worked at the time, but recently (after the machine updated or something??) stopped, again, I did the same steps on clean re-install, yet it didnt seem to do anything, as I cannot connect.

I did also tried installing wg-easy on clean install but it didnt seem to do any difference as I dont have outside connection anyway. So I'm stuck here, please help. (Sorry if this is not the place to post it I just don't know where to)

**Comment by KaapaTeelb** [comment]
Fixed, had to add these lines
  -e WG_POST_UP="iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE" \
  -e WG_POST_DOWN="iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE" \
  to the startup 😔 
  why so hard

**Comment by KaapaTeelb** [comment]
Doesn't work anymore
xd

**Comment by KaapaTeelb** [comment]
I'm not sure what to do it stopped working like a week ago and I've tried a bunch of things but it doesn't seem like I found the solution? It also was working before.

Here's the settings I were using for starting it up
(Ip, Password, Device were edited)

```
  docker run -d \
  --name=wg-easy \
  -e LANG=en \
  -e WG_HOST=ip_address \
  -e PASSWORD=password \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -e WG_DEVICE="eth0" \
  -e WG_MTU=1420 \
  -e WG_PERSISTENT_KEEPALIVE=25 \
  -e WG_DEFAULT_DNS="8.8.8.8, 8.8.4.4" \
  -e WG_PRE_UP="iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE" \
  -e WG_POST_DOWN="iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE" \
  -e UI_TRAFFIC_STATS=true \
  -e UI_CHART_TYPE=1 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy
```
  
Pls help I dont know what to do

**Comment by gdeluca** [comment]
If you don't have connection from wan and everithign is forwing fine on lan then maybe your isp firewall maybe is bloking your connection. Have you set your server static ip, and set that ip on dmz on the ips router and configure your server firewall on you server
