### ISSUE TITLE
use password hash instead of cleartext password

### ISSUE THREAD

**Issue by RobertHeim** [wg-easy/wg-easy#1105]
**Describe the bug**
Currently the UI password is provided via environment variable making the cleartext password part of the environment. Also, the client sends the cleartext password to the server. This should all happen encrypted (e.g. use bcrypt).

This requires me as a user to build a workaround and secure the interface by a reverse proxy with proper authentication handling - which is not (wg-)easy.

**Expected behavior**
Secrets should always be encrypted.
I want to provide the password encrypted as base64 string of my bcrypt encrypted password via an environment variable `PASSWORD_HASH`.

**Comment by pheiduck** [comment]
We had a function like this, but it gets removed here: #1071 

Feel free to make a PR :)

**Comment by pheiduck** [comment]
https://stackoverflow.com/posts/61405208/revisions

**Comment by pheiduck** [comment]
https://github.com/wg-easy/wg-easy/commit/b5372f0dbc0d6c081f0488f0df1314f83a7fe935

**Comment by kaaax0815** [comment]
this should always happen encrypted as hashing on the client side is considered an anti pattern (https://stackoverflow.com/questions/3715920/is-it-worth-hashing-passwords-on-the-client-side, https://www.sjoerdlangkemper.nl/2020/02/12/the-case-for-client-side-hashing-logging-passwords-by-mistake)

**Comment by kaaax0815** [comment]
A reverse proxy (with https) mostly fixes the error. As the env var inside the container is expected to be secure. UIs like wg-easy shouldnt be used without https

**Comment by pheiduck** [comment]
@kaaax0815 I don't understand your problem if you recognize problems and don't want to contribute to improvements?

**Comment by kaaax0815** [comment]
@pheiduck I do want to contribute but I have fairly limited time therefore I raise the issue so others can work on them
