### ISSUE TITLE
WG_DEFAULT_ADDRESS problem if you add more devices than expected

### ISSUE THREAD

**Issue by GuilleMurdoc** [wg-easy/wg-easy#1107]
I tried to set the environment variable WG_DEFAULT_ADDRESS to 192.168.1.21x, and it works, but when yo create enough devices to cover all ip range, it starts to assign the ip 192.168.1.2110 to new devices, so it throws an internal server error.

Also, I recommend to change the way to define the environment variable WG_DEFAULT_ADDRESS and may be, it's a good idea to set the first ip to assing.

**Comment by RobertHeim** [comment]
The current implementation is rather easy and expects 192.168.1.x without any sanity checks on the value. It just replaces `x`.

**Comment by RobertHeim** [comment]
Not the using `.12x` will also break default `WG_POST_UP`and `WG_POST_DOWN` scripts

see https://github.com/wg-easy/wg-easy/blob/2a102eea9326795119a5e1bb1036605a4aeced8c/src/config.js#L24
and https://github.com/wg-easy/wg-easy/blob/2a102eea9326795119a5e1bb1036605a4aeced8c/src/config.js#L32
