### ISSUE TITLE
Undocumented feature

### ISSUE THREAD

**Issue by kaaax0815** [wg-easy/wg-easy#1109]
**Describe the bug**
Undocumented commit b5372f0dbc0d6c081f0488f0df1314f83a7fe935.
Implements undocumented feature

**Expected behavior**
There should be a documentation for the api how it can be used without the ui.

Also the password is still send to wireguard in plaintext so how is it more secure to compare them via their hashes instead of comparing them normally?

**Comment by pheiduck** [comment]
> Also the password is still send to wireguard in plaintext 

If you have the time, you are welcome to do a PR to improve this. :)

**Comment by kaaax0815** [comment]
As I commented here: https://github.com/wg-easy/wg-easy/issues/1105#issuecomment-2171771616

The password should be sent in plaintext. The whole hashing doesn't improve security and is not really needed. The only improvement would be to support a env var like `HASHED_PASSWORD` so you nowhere have to specify the plain password

**Comment by pheiduck** [comment]
Well, when the Webif is exposed to the public it should be sent encrypted, to prevent man in the middle attacks...

**Comment by kaaax0815** [comment]
https://github.com/wg-easy/wg-easy/issues/1105

The author edited his question
In the pr I also mentioned why it shouldnt be send encrypted. Https is for that reason not hashing on client side

**Comment by pheiduck** [comment]
commit https://github.com/wg-easy/wg-easy/commit/b5372f0dbc0d6c081f0488f0df1314f83a7fe935 is not really a Feature btw.

**Comment by kaaax0815** [comment]
True but mentioned in the mentioned pr it makes the user think it improves security even tho it doesn't really
