### ISSUE TITLE
Line Chart makes UI look weird

### ISSUE THREAD

**Issue by kaaax0815** [wg-easy/wg-easy#1111]
**Describe the bug**
Using chart type 1 makes ui look weird

**To Reproduce**
1. Set chart type 1
2. log in

**Expected behavior**
should look like the other types

**Screenshots**
![firefox_oja0rxVRBS](https://github.com/wg-easy/wg-easy/assets/32197462/644dd7bc-7d03-4c95-a457-b5d59d9efdfb)

**Additional context**
There are additional lines between each client which should not happen

**Comment by pheiduck** [comment]
@suxscribe has implement the feature I hope he will come up, to fix it. :)
Or someone else have enough time to do so.

**Comment by suxscribe** [comment]
For some reason it occurs when there's no traffic data
I'll try to fix this

**Comment by pheiduck** [comment]
ping @suxscribe

**Comment by suxscribe** [comment]
Fixed in #1201
