### ISSUE TITLE
Clarify License Intent

### ISSUE THREAD

**Issue by coatandhat** [wg-easy/wg-easy#1125]
PR #756 changed the license for wg-easy from a short hand-rolled license to CC BY-NC-SA-4.0. 

The previous license explicitly stated that users may 'use this software for a company' but that they may not 'use this software in a commercial product without a license from the original author', which I understood to mean that users who wished to run a wg-easy server as part of a commercial organisation were free to do so under this original license, but that if users wished to sell a software package based on wg-easy then that would require a separate license from the author.

The CC BY-NC-SA-4.0 license, however, appears to be somewhat ambiguous on what constitutes commercial use when applied to software as it is not specifically a software license. See, for example, this StackExchange thread: https://opensource.stackexchange.com/questions/12070/allowed-uses-of-a-software-licensed-under-cc-by-nc-license

Was the intention of PR #756 to replace the previous license with a standard license which was as similar as possible, and thus to continue to allow the running of the wg-easy software as-is in commercial organisations (but to restrict the selling of wg-easy based software to third parties)? If so, it would be helpful to add an explicit clarification of this intention in the README.

Alternatively, you may wish to consider the use of a software-specific license such as the GNU GPL to reduce ambiguity.

**Comment by peterlewis** [comment]
> Was the intention of PR #756 to replace the previous license with a standard license which was as similar as possible, and thus to continue to allow the running of the wg-easy software as-is in commercial organisations (but to restrict the selling of wg-easy based software to third parties)?

Yes, precisely this (I believe).


> If so, it would be helpful to add an explicit clarification of this intention in the README.

That's a fair request. I will look to @WeeJeWel before making any changes, but so long as he is happy then I'm happy to do what we can to help clarify the intent behind the chosen licensing.

**Comment by kaaax0815** [comment]
I think @coatandhat is correct here. software should use software specific licenses

**Comment by kaaax0815** [comment]
Wrote a email. Waiting for response

**Comment by meonkeys** [comment]
FOSS licensing enthusiast here.

I recommend AGPL v3+ if you want strict copyleft. This scares away most commercial leeches. You can still make your own commercial/enterprise version with a different license (dual license).

I recommend MIT if you want permissive licensing.

Note that you must own the code to change the license--all contributors must agree or have already given the code to you.

**Comment by meonkeys** [comment]
> Do you know how a process to migrate to AGPL 3 would look like

No, not exactly. I'd recommend contacting the [SFC](https://sfconservancy.org) or [FSF](https://www.fsf.org), they might be able to advise with authority or connect you with someone who can.

That said... if you wrote all the code you can change the license anytime. If there are multiple significant contributors I would imagine you'd want to show copyright/ownership assignment to you or whomever changes the license, or that all contributors agree with changing the license.

> To allow commercial access we could do something like...
> This will (probably) never happen

Given it will probably never happen, this is moot, but I just wanted to point out that you can't add a "non-commercial" clause to the AGPL, that makes it into a different license. It's best to stick with the actual AGPL text.

**Comment by kaaax0815** [comment]
> Given it will probably never happen, this is moot, but I just wanted to point out that you can't add a "non-commercial" clause to the AGPL, that makes it into a different license. It's best to stick with the actual AGPL text.

I do not want to change the License Text (you are completely right). I just meant as @WeeJeWel is the original author afaik he could give out licenses that do not follow AGPL to companies. The text is mentioned would just live in the README so companies know they have to open source their software if the modify it and if they don't want to they can contact @WeeJeWel and "buy" a license to modify the software without needing to open source it

**Comment by meonkeys** [comment]
The original author is just *one* of the contributors, right? I think to be safe *all* contributors must agree with *any* license change, assuming the new license is not directly compatible with CC BY-NC-SA-4.0 (and AGPL is definitely not compatible). Might only be "significant" contributors that need to agree, but again, I'm no authority here, just an enthusiast.

I understand this "co-ownership by contributors" legal concept is why, for example, the Linux kernel will always be GPL. And *again*, I may be wrong, I'm just trying to be helpful here.

**Comment by meonkeys** [comment]
Thumbs up. Go for it!

(Same disclaimers as above: IANAL and other folks would better/best advice on license choice and migration process, but while I'm here I'll do my best!)

From a user's perspective: Personally, selfishly, I love the choice of AGPL v3+ for wg-easy. I think it's an excellent tool to preserve copyleft. Longevity supported by the license is a practical consideration for me since I want the software I use to survive different owners, forks, political situations, etc.

The AGPL sends a clear message to users that you care about _their_ freedom to change, re-share, etc. Of course, some folks (especially corporations acting like individuals) recoil at this same strict copyleft message, which is why we also see those "do whatever you want" licenses (my least favorite ones). I think the cost of turning some folks away is worth having a clear and user-empowering license like the AGPL.

**Comment by tetuaoro** [comment]
I am not able to say anything about license.

**Comment by coatandhat** [comment]
AGPL seems like a very reasonable choice in this case.

**Comment by kaaax0815** [comment]
Will be fixed with https://github.com/wg-easy/wg-easy/pull/1397
