### ISSUE TITLE
Connectivity and data communication

### ISSUE THREAD

**Issue by BigB2024** [wg-easy/wg-easy#1136]
Hi,
I was able to install wg-easy and all its components as it was instructed. It all went through, and I got  to Web UI page, also, I  am able to make  a new client, generate the QR code and text profile,  the client makes the basic connection through its local Wireguard interface, but the data doesn't communicate and I don't get the red dot next to my client name as it should be. Here is the screen shot from Web UI for you review .
I am using RackNerd VPS along with ubuntu 20.04  OS
Will you advise please
Many Thanks
Ben
![Screenshot 2024-06-27 145229](https://github.com/wg-easy/wg-easy/assets/174013874/7c30b97d-86fd-4cb6-9304-52997f0d5106)

**Comment by EldarioLink** [comment]
Hi. I have the same issue on my new vps ( ubuntu 20.04, and 22.04 as well ):
I install successfully and get web ui. Can generate new config. But there is no connection. 

P.S. i tried many times. check needed ports, reinstall OS and tried again on pure machine. But there is no successfull result. Also i was told there is no restrictions from my vps provider..

**Comment by mathys-lopinto** [comment]
Hello,
Do you have any firewall install on your server (like iptables, ufw) or provided by RackNerd (actived by default, like we can have with IONOS) or an firewall on your IPhone wifi ?
Can you also provide what docker version you use, and the wg-easy build (latest, nightly ...)
If you didn't have any firewall, can you send here your configuration (docker and client) **WITHOUT INCLUDE KEY CONTENT** ?

**Comment by mathys-lopinto** [comment]
When i'm ask for configuration, i asking for your docker compose file/ docker run command and the iphone.conf without the key content.

**Comment by BigB2024** [comment]
Here is the client profile without keys, I can't find docker-compose.yml, 
Thanks for your help

[Interface]
PrivateKey = XXXXXXXXXXXXXXxx
Address = 10.8.0.2/24
DNS = 10.8.2.2

[Peer]
PublicKey = XXXXXXXXXXXXXXXXXXXx
PresharedKey = XXXXXXXXXXXXXx
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
Endpoint = wg.eliyad.com:51820
and

**Comment by mathys-lopinto** [comment]
For run wg-easy do you use command   ``docker run -d \
  --name=wg-easy \ [...]``
  
 Or you use ``docker compose up --detach`` ?
 
For the first case, send the full docker run command else send the docker-compose.yml in the folder where you run docker compose up -d

On your sever, can you try to start the iphone VPN and run this command for send the output:
``` bash
docker exec wg-easy wg show
```

**Comment by BigB2024** [comment]
phone WG is on and ->docker exec wg-easy wg show:, I just can't find the the compos file.

interface: wg0
  public key: XXX
  private key: (hidden)
  listening port: 51820

peer: XXX
  preshared key: (hidden)
  endpoint: 2.144.36.131:64292     **( it makes the tunnel, this is my IP)**
  allowed ips: 10.8.0.2/32
  transfer: 1.16 KiB received, 736 B sent

**Comment by EldarioLink** [comment]
> For run wg-easy do you use command `docker run -d \ --name=wg-easy \ [...]`
> 
> Or you use `docker compose up --detach` ?
> 
> For the first case, send the full docker run command else send the docker-compose.yml in the folder where you run docker compose up -d
> 
> On your sever, can you try to start the iphone VPN and run this command for send the output:
> 
> ```shell
> docker exec wg-easy wg show
> ```
 Hello. Sorry for interfering. i'm trying to solve the same problem too. Here is my `docker run -d \ --name=wg-easy \ [...]`:

  docker run -d \
  --name=wg-easy-test \
  -e LANG=en \
  -e WG_HOST=217.30.10.80 \
  -e PASSWORD=foobar123! \
  -e PORT=51921 \
  -e WG_PORT=51920 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51920:51920/udp \
  -p 51921:51921/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy

**The output `docker exec wg-easy-test wg show`**:

interface: wg0
  public key: yEUaCNCa/ArYw5cSZLNr5lj2iCBXlIgarNSioO/WYE8=
  private key: (hidden)
  listening port: 51920

peer: eANmMAwElg64CDuXwbaoUNcbGHVJdAjMbcwJmLZatVo=
  preshared key: (hidden)
  endpoint: 85.249.30.18:40406
  allowed ips: 10.8.0.2/32
  latest handshake: 4 minutes, 6 seconds ago
  transfer: 860 B received, 6.64 KiB sent

**And the client `conf` file is**:


[Interface]
PrivateKey = {hidden}
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = yEUaCNCa/ArYw5cSZLNr5lj2iCBXlIgarNSioO/WYE8=
PresharedKey = {hidden}
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 217.30.10.80:51920

There on site `http://217.30.10.80:51921/` i see config, it seems to be okay, but it doesn't work:

![screen](https://github.com/wg-easy/wg-easy/assets/40660289/32db76cc-510d-4cf8-baaf-20b04c43bdd7)

IDK why it happens. If you can, please help! I will appreciate your help!

PS. Ports `51921, 51920` are opened via ufw, i tried it out many times, btw on my old vps it works fine via just one command.

**Comment by BigB2024** [comment]
I am  playing around with upd ports, I think my ISP has blocked many ports. I let you know the outcome soon

**Comment by BigB2024** [comment]
To mathys-lopint,o
Hi,
here are the latest information, I played with different upd ports, but still no luck. Here are compose and interface info, Do you have any Idea?
Docker Compose:
****************************
services:
  wg-easy:
    environment:
      - WG_HOST=my_VPS_IP
      - PASSWORD=XXXXXXXXX
      - PORT=5537
      - WG_PORT=5536
      - WG_CONFIG_PORT=92820
      - WG_DEFAULT_ADDRESS=10.66.66.167
      
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - 5536:5536/udp
      - 5537:5537/tcp
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
************************************************
interface: wg0
  public key: xxxxxxxxxxxxxxxxxx
  private key: (hidden)
  listening port: 5536

peer: 
  preshared key: (hidden)
  endpoint: "myhomeIP:55497
  allowed ips: 10.8.0.2/32
  transfer: 148 B received, 92 B sent
