### ISSUE TITLE
On stable build password does not work when I use password hash.

### ISSUE THREAD

**Issue by Framdark** [wg-easy/wg-easy#1141]
Weirdly it works fine when I just put the password in unencrypted. What happens when I put it in using the hash is when I go to the web ui it does not ask for password and just sends me straight in.

**Comment by kevinkellner** [comment]
Same issue here. It is not only on latest, but also on previous tags (11, 12)

**Comment by pheiduck** [comment]
Because the enviroment variable **PASSWORD_HASH** is only available on nighly till now and not stable images.
This is not a bug.

**Comment by antonkvm** [comment]
If the PASSWORD_HASH environment variable is only available on nightly, then the example docker run snippet and the example docker-compose.yml are misleading and should be changed, as they use that variable but not the nightly build as an image.

This is also the reason why password authentication does not work for people who don't know about this, as mentioned in issue #1141.
