### ISSUE TITLE
Import existing keys

### ISSUE THREAD

**Issue by GordonCopestake** [wg-easy/wg-easy#1146]
Feature request: import existing keys

I have a working wireguard setup but would like to migrate to wg-easy. In order to do so I have to regenerate all my keys.

It would be good if there was an option to import existing keys into wg-easy so we could specify the server key as well as any existing clients.

My thinking would be: install wg-easy, open the web interface, specify the existing server keys, add a client and be given the option to specify their keys too.

If there are already clients setup then clearly changing the server key would break things so this would only be possible when there are no clients on wg-easy, or on initial run.

**Comment by pheiduck** [comment]
https://github.com/wg-easy/wg-easy/commit/7f05448a5d4edf8430018c3d99f9508c59fa4f55

**Comment by GordonCopestake** [comment]
Thats great, thanks very much. I'll download the nightly and give it a spin

**Comment by GordonCopestake** [comment]
The backup and restore works perfectly, thats a great feature to have, thank you.

When I try to manually edit the backup JSON file though, to add or edit a client, on restore I always get a server error 500.

Hard to tell the cause as the response is just:

```
{
  "statusCode": 500,
  "stack": []
}
```

I have a feeling it might be something to do with the client id's?

**Comment by pheiduck** [comment]
> I have a feeling it might be something to do with the client id's?

The id should not be modified.

**Comment by GordonCopestake** [comment]
How do I add a client? Do I have to create a "dummy" client first, then export, then change that key?
