### ISSUE TITLE
pw

### ISSUE THREAD

**Issue by ChandlerAx** [wg-easy/wg-easy#1150]
theres no password everyone can access the web ui & delete/add clients how to fix this? (lastest version of today)

**Comment by cliaz** [comment]
The 'PASSWORD' field is being deprecated, with the recommendation to switch to using the PASSWORD_HASH field.
Not having a password set correctly, either via PASSWORD or PASSWORD_HASH, will result in what you're experiencing. 

The PASSWORD_HASH field is only supported in the nightly builds. Check out the discussion [here](https://github.com/wg-easy/wg-easy/discussions/1131) about switching to nightly build, and the "How to generate an bcrypt hash read me" [here](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md)

**Comment by pheiduck** [comment]
Please rtfm before posting issues Thx!
Please follow @cliaz instruction.
And if we should improve documentation, everyone is welcome todo so!
