### ISSUE TITLE
Error "ModuleNotFoundError: No module named 'bcrypt' " with macOS Sonoma M2

### ISSUE THREAD

**Issue by valorisa** [wg-easy/wg-easy#1153]
**Describe the bug**
Error following when I run the command '`python3 -c "import bcrypt; password =`' with macOS Sonoma.

**To Reproduce**
Steps to reproduce the behavior :
1. 
`Mac-mini-M2 ~ % python3 -c "import bcrypt; password = b'your_password_here'; assert len(password) < 72, 'Password must be less than 72 bytes due to bcrypt limitation'; hashed = bcrypt.hashpw(password, bcrypt.gensalt()); print(f'The hashed password is: {hashed.decode()}'); docker_interpolation = hashed.decode().replace('$', '$$'); print(f'The hashed password for a Docker env is: {docker_interpolation}')" # or python if you run this on Windows. CHANGE your_password_here BY YOUR PASSWORD`

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bcrypt'`

**Expected behavior**
`The hashed password is: $XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
The hashed password for a Docker env is: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

**Screenshots**
![Capture d’écran 2024-07-07 à 18 21 43](https://github.com/wg-easy/wg-easy/assets/13067566/24f6d89f-c308-4d88-bd42-c29ed963e08c)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14.6]

**Additional context**
' with macOS

**Comment by pheiduck** [comment]
https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md#macos

**Comment by valorisa** [comment]
For me the solution is here :

![Capture d’écran 2024-07-08 à 10 33 17](https://github.com/wg-easy/wg-easy/assets/13067566/d2f9ad45-82b1-4fd1-b5b6-ed7d0f4e5ac1)

**Comment by valorisa** [comment]
Eventually, could you please add following lines for macOS in ZSH ? : 

```
~ % python3 -m venv path/to/venv
~ % source path/to/venv/bin/activate
(venv) ~ % python3 -m pip install --upgrade pip
(venv)  ~ % python3 -c "import bcrypt; password = b'XXXXXXXXX'; assert len(password) < 72, 'Password must be less than 72 bytes due to bcrypt limitation'; hashed = bcrypt.hashpw(password, bcrypt.gensalt()); print(f'The hashed password is: {hashed.decode()}'); docker_interpolation = hashed.decode().replace('$', '$$'); print(f'The hashed password for a Docker env is: {docker_interpolation}')" # or python if you run this on Windows. CHANGE your_password_here BY YOUR PASSWORD
The hashed password is: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
The hashed password for a Docker env is: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by valorisa** [comment]
https://docs.python.org/3.9/library/venv.html#module-venv

**Comment by pheiduck** [comment]
> https://docs.python.org/3.9/library/venv.html#module-venv

Yes I know that, this way it wouldn't effect system pkgs.
`--break-system-packages` is not recommended, will update the documatation later.

**Comment by valorisa** [comment]
![Screenshot_2024-07-15-15-10-50-35_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/9716ca59-01b7-4205-a55c-be93574c5b7c)

**Comment by pheiduck** [comment]
The Password Hashing is now easier thanks to @tetuaoro
https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md

**Comment by valorisa** [comment]
OK, I'll try it.

**Comment by tetuaoro** [comment]
> OK, I'll try it.

Hi, look at #1187 too.
