### ISSUE TITLE
Support for aarch64

### ISSUE THREAD

**Issue by hcr2020** [wg-easy/wg-easy#1169]
Hi 
I used your instructions to make a docker container,  which  ran successfully but doesn't  launch because of exec error

 Log from portainer     
exec /usr/bin/dumb-init: exec format error

Could you add linux/aarch64 support ? I found this attempt :
 
https://github.com/yury-sannikov/amnezia-wg-docker
But it didn't succeed.
Thank you in advance

**Comment by pheiduck** [comment]
our image supports this architectures:
https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy
as well as aarch64.

**Comment by hcr2020** [comment]
I have mistaken it  for amnesia-wireguard-easy

**Comment by pheiduck** [comment]
I give no support for forks... ^^ Otherwise there submit PRs upstream.

**Comment by hcr2020** [comment]
Thanks
