### ISSUE TITLE
Web UI not prompting for password

### ISSUE THREAD

**Issue by deelowe** [wg-easy/wg-easy#1177]
**Describe the bug**
Despite having PASSWORD_HASH set, I am not presented with a pasword/login prompt when accessing 
http://0.0.0.0:51821

**To Reproduce**
1. Create bcrypt hashed password following instructions in "How_to_generate_an_bcrypt_hash.md"
2. Copy the has following "The hashed password for a Docker env is: "
3. Launch wg-easy using

   docker run -d \
   --name=wg-easy \
   -e LANG=en \
   -e WG_HOST=[HOST IP ADDRESS] \
   -e PASSWORD_HASH=[HASHED PASSWORD] \
   -e PORT=51821 \
   -e WG_PORT=51820 \
   -v ~/.wg-easy:/etc/wireguard \
   -p 51820:51820/udp \
   -p 51821:51821/tcp \
   --cap-add=NET_ADMIN \
   --cap-add=SYS_MODULE \
   --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
   --sysctl="net.ipv4.ip_forward=1" \
   --restart unless-stopped \
   ghcr.io/wg-easy/wg-easy

4. Visit http://0.0.0.0:51821 on host machine
5. Observe wg-easy webui is accessible without entering a password

**Expected behavior**
I would expect the webui to prompt for a login of some sort if PASSWORD_HASH is supplied to the docker run command.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Browser: Firefox - 115.12.0esr (64-bit)
 - Version: Latest

**Additional context**
Configuration completely follows the instructions given in README.md. There are no custom settings.  Behavior persists whether I use docker run or docker compose. All other wg-easy settings seem to work just fine.

NOTE: using the deprecated "-e PASSWORD=[PASSWORD]" option produces the same issue.

**Comment by deelowe** [comment]
Quick update. I tried supplying the deprecated "-e PASSWORD=" option and I'm still not getting a password prompt.

**Comment by pheiduck** [comment]
latest and other versions haven't changed there are use password env.
Expect nightly is using hashed password env.
You may need to read the readme of the production branch.

**Comment by deelowe** [comment]
> latest and other versions haven't changed there are use password env. Expect nightly is using hashed password env. You may need to read the readme of the production branch.

This is a completely fresh install on my VPS. Not sure how anything would be cached? Is there a way to clear the env?

**Comment by pheiduck** [comment]
> > latest and other versions haven't changed there are use password env. Expect nightly is using hashed password env. You may need to read the readme of the production branch.
> 
> I'm not sure I follow? What should I change?

docker run -d
--name=wg-easy
-e LANG=en
-e WG_HOST=[HOST IP ADDRESS]
-e PASSWORD=[PASSWORD]
-e PORT=51821
-e WG_PORT=51820
-v ~/.wg-easy:/etc/wireguard
-p 51820:51820/udp
-p 51821:51821/tcp
--cap-add=NET_ADMIN
--cap-add=SYS_MODULE
--sysctl="net.ipv4.conf.all.src_valid_mark=1"
--sysctl="net.ipv4.ip_forward=1"
--restart unless-stopped
ghcr.io/wg-easy/wg-easy

**Comment by deelowe** [comment]
> Quick update. I tried supplying the deprecated "-e PASSWORD=" option and I'm still not getting a password prompt.

I already tried that. See this comment above: https://github.com/wg-easy/wg-easy/issues/1177#issuecomment-2225956291

**Comment by deelowe** [comment]
> > > latest and other versions haven't changed there are use password env. Expect nightly is using hashed password env. You may need to read the readme of the production branch.
> > 
> > 
> > I'm not sure I follow? What should I change?
> 
> docker run -d --name=wg-easy -e LANG=en -e WG_HOST=[HOST IP ADDRESS] -e PASSWORD=[PASSWORD] -e PORT=51821 -e WG_PORT=51820 -v ~/.wg-easy:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart unless-stopped ghcr.io/wg-easy/wg-easy

I tried that already. See this comment above: https://github.com/wg-easy/wg-easy/issues/1177#issuecomment-2225956291

**Comment by lacrima08** [comment]
> > > > latest and other versions haven't changed there are use password env. Expect nightly is using hashed password env. You may need to read the readme of the production branch.
> > > 
> > > 
> > > I'm not sure I follow? What should I change?
> > 
> > 
> > docker run -d --name=wg-easy -e LANG=en -e WG_HOST=[HOST IP ADDRESS] -e PASSWORD=[PASSWORD] -e PORT=51821 -e WG_PORT=51820 -v ~/.wg-easy:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart unless-stopped ghcr.io/wg-easy/wg-easy
> 
> I tried that already. See this comment above: [#1177 (comment)](https://github.com/wg-easy/wg-easy/issues/1177#issuecomment-2225956291)
> 
> It's also worth noting this is on a fresh VPS and wg-easy install. wg-easy is the second service I installed/configured (after SSH).

it's working for me with PASSWORD instead of PASSWORD_HASH

**Comment by Xaneets** [comment]
I faced a similar problem. I tried to set both password and hash. But  UI does not ask for a password.

**Comment by Xansala** [comment]
I am facing the same issue @deelowe . Have an installation where the password prompt worked when it was setup with 
`-e PASSWORD=xxx`
Recently after a container update it does not seem to work anymore and the password prompt is not showing up.
