### ISSUE TITLE
Password Hash Generation not working

### ISSUE THREAD

**Issue by apguru** [wg-easy/wg-easy#1187]
**Describe the bug**
Trying to generate a password using a temporary container I get an error "Cannot find module /app/wgpw".

**To Reproduce**
1. Run `docker run ghcr.io/wg-easy/wg-easy wgpw foobar123`
2. See error

**Expected behavior**
See returned password hash

**Screenshots**
![image](https://github.com/user-attachments/assets/bbaf7d01-e513-4da4-afd4-28d10d35e166)

**Desktop (please complete the following information):**
 - OS: Windows 11 / Ubuntu 2404

**Comment by pheiduck** [comment]
Until now its under :
Run docker run `ghcr.io/wg-easy/wg-easy:development wgpw foobar123`

Later: ghcr.io/wg-easy/wg-easy:nightly
sooner: ghcr.io/wg-easy/wg-easy:latest or ghcr.io/wg-easy/wg-easy:v14

**Comment by antonkvm** [comment]
If the wg-password script does not work with the stable build, then the [tutorial](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md) should not suggest using that build to create the hash, because that will never work.
