### ISSUE TITLE
Does wg-easy not support arm64/v8?

### ISSUE THREAD

**Issue by xd19861224** [wg-easy/wg-easy#1198]
I used docker-compose to install wg-easy on my armbian system, but got an error:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Then Put this line --platform linux/amd64 after docker run

new error：

![Quicker_wg-easy](https://github.com/user-attachments/assets/17ef83e5-ee50-47f6-8ffe-f9de31030fe1)

**Comment by pheiduck** [comment]
It does: https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy

**Comment by xd19861224** [comment]
![image](https://github.com/user-attachments/assets/05b11717-9bea-4479-85dd-e3105d2d2b44)
