### ISSUE TITLE
Better contribution solution

### ISSUE THREAD

**Issue by kaaax0815** [wg-easy/wg-easy#1203]
### Problem:
1. no issue follows the issue template (not even remotely) therefore often crucial information is missing
2. no issue template for feature requests
3. no issue template for problems (or be strict and manually convert them to discussions)
4. issue with branches. master is not prod branch and therefore not latest stable. this should be communicated more clearly.
5. versions and their breaking changes are not really intuitive
6. every pr needs to be created by a maintainer to create a docker build which shouldnt be the case
7. og author is not active anymore

**Comment by pheiduck** [comment]
I agree with all your statements!

**Comment by pheiduck** [comment]
I try to don't follow 6. for now...

**Comment by kaaax0815** [comment]
@pheiduck https://docker-mailserver.github.io/docker-mailserver/latest/

For releases adding a tag and a release using github with breaking changes or referring to a CHANGELOG.md would better document breaking changees

**Comment by pheiduck** [comment]
> Better labels like https://github.com/abdonrd/github-labels would also make sense

It`s done!

**Comment by kaaax0815** [comment]
> It`s done!

Im not sure but I think the templates also have to be adjusted

**Comment by pheiduck** [comment]
> > It`s done!
> 
> Im not sure but I think the templates also have to be adjusted

Sure.

**Comment by kaaax0815** [comment]
Instead of using a github action to update packages. We could also use something like dependabot.

**Comment by kaaax0815** [comment]
I think https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/ would be the best option

**Comment by pheiduck** [comment]
> Instead of using a github action to update packages. We could also use something like dependabot.

Ok, will replace gh action with dependabot.

**Comment by kaaax0815** [comment]
Closing this for now as Docs are implemented in #1361
