### ISSUE TITLE
Latest docker image can't change Wire Guard port!

### ISSUE THREAD

**Issue by kon3ko** [wg-easy/wg-easy#1205]
**Describe the bug**
![image](https://github.com/user-attachments/assets/284d5d4e-3fd5-458b-8641-dc8a5a46907d)

I tried changing the port from 51820 to 51830.
Found that the `latest` image is not usable.

But when reduced to using `12` image, it can work normally.
This doesn't happen on the server if you try testing with `nc -z -v -u 127.0.0.1 51830`
But the client side will not be able to connect.

**To Reproduce**
1. Use docker compose with latest
2. change `51820:51820/udp` to `51830:51820/udp`
3. change `WG_PORT=51830`
4. run `docker compose up -d`

**Expected behavior**
The first time I found It cannot be used with the Wire Guard client.
So I tried checking the firewall but couldn't find anything wrong. Until I tried the old version.

**OS server**
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

**Comment by eandersons** [comment]
You should carefully read the description of `WG_PORT`:

> The public UDP port of your VPN server. WireGuard will listen on that (othwise default) inside the Docker container.

**Comment by elvismercado** [comment]
expanding on the previous comment.

If you setup `WG_PORT=51830` then the wireguard port inside the contain is `51830`.
Your exported port must look something like this `51830:51830/udp` then, depending on your port forward.
So WG_PORT changes the port used for wireguard `inside` the container.

Another example:
Lets say you port forward port `51830` from your router to the docker container. And you do not change WG_PORT which then would use the `default port inside` the container then the port export  would have to look like what you had: `51830:51820/udp`.

**Comment by kon3ko** [comment]
@eandersons @elvismercado @tetuaoro Oh!!!!! Thank a lot
I spent over 8 hours on this thing testing the settings to make sure they were set correctly.
Now it's back to working normally. Thank you very much.
