### ISSUE TITLE
Install wg-easy with traefik

### ISSUE THREAD

**Issue by TollerEmil** [wg-easy/wg-easy#1209]
**Describe the bug**
I try to install via the Script: [https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Traefik-SSL](url)

**To Reproduce**
1.  `sudo docker-compose up -d`
Returns: ERROR: Network traefik_network declared as external, but could not be found. Please create the network manually using `docker network create traefik_network` and try again.
2. Create Network: `sudo docker network create traefik_network` works fine
3. Again: `sudo docker-compose up -d` seems to run ok
4. Open browser to URL a "404 page not found" is shown on the website.
5. `sudo docker stats` output:
wg-easy            0.00%     0B / 0B             0.00%     5.8kB / 0B        59.1MB / 0B   12
wgeasy_traefik_1   0.03%     0B / 0B             0.00%     25.7kB / 10.4kB   106MB / 0B    9

**Desktop (please complete the following information):**
 - OS:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

Hardware: Rpi 4

**Comment by prateeknischal** [comment]
There may be some misconfiguration with how traefik discovers the wg-easy container. Here is my configuration that works.
https://gist.github.com/prateeknischal/9f26d30141510c0c4e8bafe4bbd2d289

It is a pretty minimal config so should be easy to extend without any magic. I too was getting 404 for majority of my setup until I fixed my tags and upgraded to traefik v3 for most upto date docs.

**Comment by graf-Gopher** [comment]
For traefik v3 in my case, help **"traefik.port"** & **"loadbalancer.server.port"** labels

_labels:
      - "traefik.enable=true"
      - "traefik.port=51821"
      - "traefik.docker.network=default_network"
      - "traefik.http.routers.wireguard.entrypoints=https"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.home.domain.com`)"
      - "traefik.http.routers.wireguard.tls=true"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"_
