### ISSUE TITLE
No handshake one day

### ISSUE THREAD

**Issue by botswanabub** [wg-easy/wg-easy#1214]
Hi @all,

I'm running WG-EASY on a RPI5 for month without any problem. Once a day, I'm not sure when exactly, it stops working and I can't receive a handshake anymore.
Beside updating the RPI/DOCKER etc. there where no changes in the network or hardware.
Ports are active (51820, 51821). Webinterface is reachable. No idea what that could be, any ideas where I can start? I know there are many posibilities but I happy with any input.

lastest debug after reinstall and start container once again:

```
wireguard  | 2024-07-25T10:03:49.255Z Server Listening on http://0.0.0.0:51821
wireguard  | 2024-07-25T10:03:49.258Z WireGuard Loading configuration...
wireguard  | $ wg genkey
wireguard  | $ echo ***hidden*** | wg pubkey
wireguard  | 2024-07-25T10:03:49.272Z WireGuard Configuration generated.
wireguard  | 2024-07-25T10:03:49.272Z WireGuard Config saving...
wireguard  | 2024-07-25T10:03:49.274Z WireGuard Config saved.
wireguard  | $ wg-quick down wg0
wireguard  | $ wg-quick up wg0
wireguard  | 2024-07-25T10:03:49.355Z WireGuard Config syncing...
wireguard  | $ wg syncconf wg0 <(wg-quick strip wg0)
wireguard  | 2024-07-25T10:03:49.385Z WireGuard Config synced.
wireguard  | 2024-07-25T10:03:58.398Z Server New Session: Cm-xxxxxx
wireguard  | $ wg genkey
wireguard  | $ echo xxxxx= | wg pubkey
wireguard  | $ wg genpsk
wireguard  | 2024-07-25T10:04:04.616Z WireGuard Config saving...
wireguard  | 2024-07-25T10:04:04.619Z WireGuard Config saved.
wireguard  | 2024-07-25T10:04:04.619Z WireGuard Config syncing...
wireguard  | $ wg syncconf wg0 <(wg-quick strip wg0)
wireguard  | 2024-07-25T10:04:04.663Z WireGuard Config synced.
```

**Comment by Anndres47** [comment]
Hi, I'm not sure what is causing your problem.
But I'm trying to configure WG-EASY on my RPI5, could you give me an overview of the steps you followed setting it up?

I'm kinda lost here, wg is up and running but when a peer is connected, I tried to ping another host unsuccessfully and can't access internet neither :(

**Comment by botswanabub** [comment]
hi, finally the update:
the error was a mal configuration from ISP ... I figured out by establishing other connections when I were in front of.

my config is standard (thats why I was wired why it's not working anymore ...) and everything is working fine! lookups local, too
