### ISSUE TITLE
add database

### ISSUE THREAD

**Issue by offizium-berndstorath** [wg-easy/wg-easy#1216]
**Describe the bug**
Many features are requested that would need to store data somewhere persistent. should be atomic and support multiple connections. so multiple admins wont interfere with one another

a json file is imo not the best storage solution. even a simple (type-safe) wrapper around such file would greatly improve dx.

i looked at some solutions but cant choose:
https://github.com/appy-one/acebase (unmaintained?)
https://github.com/Level/level
https://github.com/kriasoft/node-sqlite (unmaintained?)
https://github.com/typicode/lowdb

**Comment by kaaax0815** [comment]
Implemented with https://github.com/wg-easy/wg-easy/pull/1330
