### ISSUE TITLE
Wrong password accepted from external secrets

### ISSUE THREAD

**Issue by matteo-martinelli** [wg-easy/wg-easy#1218]
**Describe the bug**
My will is to pass the PASSWORD in my docker-compose as a secret stored in an external file. Nevertheless, when I do so, the password to access into the UI corresponds to the actual name of the variable, instead of the password pointed by the variable.

**To Reproduce**
1. Structure the docker compose as follows: 

```...
image: ghcr.io/wg-easy/wg-easy:13
environment:
      - PASSWORD=wg-pw
...
secrets: 
  wg-pw: 
    file: ./secrets/wg-pw
```

2. Create a `secrets` file respecting the structure pointed in the compose. 
3. The wg-pw file contains the password, as `my-wg-password`.

**Expected behavior**
Wen accessing the UI, I expect the service to use the file stored in the external file, i.e. `my-wg-password`.
Instead, the password accepted is `wg-pw`.

**Comment by eandersons** [comment]
Docker secrets are not yet supported. See #1062, #1152.

> Instead, the password accepted is `wg-pw`.

Exactly as you instructed to by using the environment variable `PASSWORD`.

**Comment by matteo-martinelli** [comment]
> Docker secrets are not yet supported. See #1062, #1152.
> 
> > Instead, the password accepted is `wg-pw`.
> 
> Exactly as you instructed to by using the environment variable `PASSWORD`.

Thank you very much for the clarification. I will adjust my compose.
