### ISSUE TITLE
Cannot login even true password

### ISSUE THREAD

**Issue by dikeckaan** [wg-easy/wg-easy#1221]
**Describe the bug**
Login page is not working in nightly

**To Reproduce**
1. Pull nightly
2. Get password hash
3. edit your docker run command
4. Try Login

**Expected behavior**
Login but not working

**Screenshots**
![image](https://github.com/user-attachments/assets/97d77524-65fc-47c8-bd34-0610af991463)

True password has issue

**Desktop (please complete the following information):**
 - OS: [w11]
 - Browser [hrome, edge]
 - Version [latest, 127]

**Smartphone (please complete the following information):**
 - Device: [iPhone14pm]
 - OS: [e.g. iOS 17.5.1]
 - Browser [chrome]
 - Version [latest, idk version]

**Additional context**

my server is ubuntu 22.04 and docker latest (installed today) all firewall options are disabled for test, if i try latest it works perfect but without password login page

  docker run -d \
  --name=wg-easy \
  -e LANG=en \
  -e WG_HOST=mypublicip \
  -e PASSWORD_HASH='$2b$12$coPqCsPtcFO.Ab99xylBNOW4.Iu7OOA2/ZIboHN6/oyxca3MWo7fW' \  // tried your hash,  my hash and issue persist
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy:nightly

**Comment by Char1esOrz** [comment]
I had the same problem, have you solved it yet?

**Comment by tetuaoro** [comment]
> I had the same problem, have you solved it yet?

I did it now and it works, here my command with litteraly `YOUR_PASSWORD` password :

```bash
sudo docker run --env WG_HOST=0.0.0.0 --rm --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --mount type=bind,source="$(pwd)"/config,target=/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp -e PASSWORD_HASH='$2b$12$coPqCsPtcFO.Ab99xylBNOW4.Iu7OOA2/ZIboHN6/oyxca3MWo7fW' ghcr.io/wg-easy/wg-easy:nightly
```

**Comment by dikeckaan** [comment]
``> > I had the same problem, have you solved it yet?
> 
> I did it now and it works, here my command with litteraly `YOUR_PASSWORD` password :
> 
> ```shell
> sudo docker run --env WG_HOST=0.0.0.0 --rm --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --mount type=bind,source="$(pwd)"/config,target=/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp -e PASSWORD_HASH='$2b$12$coPqCsPtcFO.Ab99xylBNOW4.Iu7OOA2/ZIboHN6/oyxca3MWo7fW' ghcr.io/wg-easy/wg-easy:nightly
> ```

yes it worked and i guess the issue happened because of language option. 

i use this and edited password

docker run ghcr.io/wg-easy/wg-easy:nightly wgpw examplepassword
PASSWORD_HASH='$2a$12$SVQMv7UFtn0w6F/KSNV1n.g/.RY4PSNtQ45rTlcCu2U8Y9v8HbXym'

```shell
sudo docker run -d --env WG_HOST=my.public.ip.addr --rm --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --mount type=bind,source="$(pwd)"/config,target=/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp -e PASSWORD_HASH='$2a$12$SVQMv7UFtn0w6F/KSNV1n.g/.RY4PSNtQ45rTlcCu2U8Y9v8HbXym' ghcr.io/wg-easy/wg-easy:nightly`
```

login password is examplepassword


Thanks and i guess we need edit README file

**Comment by govtech42** [comment]
To resolve this issue, generate a new password hash using your desired password and Apache’s htpasswd utility. First, install the necessary tool by executing the following command:

`sudo apt install apache2-utils`

Next, generate a bcrypt hash by running the command below, replacing mypassword with your actual password:

`htpasswd -nbB wgpw mypassword`

The output will be similar to the following:

`wgpw:$2y$05$BWuF18ZJlcgqKCR9DBODmebr2oVIpHbkIgiaRsRqKqPlrIufjS..G`

Extract the hash portion (i.e., the string after the colon) and assign it to the environment variable PASSWORD_HASH:

`PASSWORD_HASH=$2y$05$BWuF18ZJlcgqKCR9DBODmebr2oVIpHbkIgiaRsRqKqPlrIufjS..G`

Note: Do not include the wgpw: prefix — only the hashed string is required.

After setting the new hash, restart your Docker service. 

`docker compose down`
`docker compose up -d`

Your password should now be correctly recognized and authentication will function as expected.

**Comment by Snickdx** [comment]
> To resolve this issue, generate a new password hash using your desired password and Apache’s htpasswd utility. First, install the necessary tool by executing the following command:
> 
> `sudo apt install apache2-utils`
> 
> Next, generate a bcrypt hash by running the command below, replacing mypassword with your actual password:
> 
> `htpasswd -nbB wgpw mypassword`
> 
> The output will be similar to the following:
> 
> `wgpw:$2y$05$BWuF18ZJlcgqKCR9DBODmebr2oVIpHbkIgiaRsRqKqPlrIufjS..G`
> 
> Extract the hash portion (i.e., the string after the colon) and assign it to the environment variable PASSWORD_HASH:
> 
> `PASSWORD_HASH=$2y$05$BWuF18ZJlcgqKCR9DBODmebr2oVIpHbkIgiaRsRqKqPlrIufjS..G`
> 
> Note: Do not include the wgpw: prefix — only the hashed string is required.
> 
> After setting the new hash, restart your Docker service.
> 
> `docker compose down` `docker compose up -d`
> 
> Your password should now be correctly recognized and authentication will function as expected.

I'm using wg-easy on easy panel, did these steps but still no success. Even tried escaping $ signs and adding quotes to luck

**Comment by Chrisake** [comment]
The issue is cause because of the $ sign and how it is handled in the docker file, this is why the same hash works when used on the cli but fails inside the docker file. The solution is to double the $ signs inside the docker file, for example add:

`- PASSWORD_HASH=$$2a$$12$$N3ploRW2Fm/A0wwXriMsjerKYA/ShU/9W2.fW4kUVK1DspEYwJU26`

(password: myultrasecurepassword)
