### ISSUE TITLE
Web UI cannot listen on localhost

### ISSUE THREAD

**Issue by martyy665** [wg-easy/wg-easy#1222]
Hello there,

if I set the ENV WEBUI_HOST=localhost in the docker-compose file, the log confirms that it should be OK:

```
[+] Running 2/2
 ✔ Network docker_compose_wgeasy_default  Created                                                                                                                                                                 0.2s 
 ✔ Container wg-easy                      Created                                                                                                                                                                 0.1s 
Attaching to wg-easy
wg-easy  | 2024-07-28T13:22:39.894Z Server Listening on http://localhost:51822
wg-easy  | 2024-07-28T13:22:39.897Z WireGuard Loading configuration...
wg-easy  | 2024-07-28T13:22:39.908Z WireGuard Configuration loaded.
wg-easy  | 2024-07-28T13:22:39.908Z WireGuard Config saving...
wg-easy  | 2024-07-28T13:22:39.910Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | 2024-07-28T13:22:40.054Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-07-28T13:22:40.090Z WireGuard Config synced.
```

Despite that, the service listed on 0.0.0.0 instead.

```
tcp          LISTEN        0             4096                        0.0.0.0:51822                      0.0.0.0:*            users:(("docker-proxy",pid=27165,fd=4))
```

Moreover, no index.html is returned in this state when called GET from the localhost.

```
--2024-07-28 15:44:13--  (try: 2)  http://localhost:51822/
Connecting to localhost (localhost)|127.0.0.1|:51822... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

Everything works as expected when listening on all interfaces (0.0.0.0) (incl. GET from locahost).

Am I doing anything wrong?

**Comment by tetuaoro** [comment]
Hi, try without `WEBUI` env.

**Comment by pheiduck** [comment]
WEBUI_HOST=localhost -> WG_HOST=localhost

**Comment by martyy665** [comment]
Sorry, I probably did not describe the use case enough. I need to have the WG interface available on public IP/domain (parameter WG_HOST - it works fine), but the management website should be available locally only (further managed by the Nginx) - parameter WEBUI_HOST. According to the container log, the behaviour seems to be OK.

**Comment by tetuaoro** [comment]
Ok, what's your env ports config ? Based on above info, `docker run ... -p 51822:51822/tcp 51821:51821/udp` ?

**Comment by tetuaoro** [comment]
Can you try this config ? `WG_HOST=127.0.0.1`, it's the local loopback address.

**Comment by tetuaoro** [comment]
Sorry, I'm wrong. Let `WEBUI_HOST` by default and bind docker with this following : `docker run ... -p 127.0.0.1:51821:51821/tcp ...`. If you use docker compose, adapt the command.

**Comment by martyy665** [comment]
Hi  @tetuaoro, thank you for the advice. Of course, you are totally right. The interface that the Web UI listens on is completely under Dockers <-> host control. Internally, the container MUST listen on at least a docker virtual adapter to make the port tunnelling.

Sorry again, I was slightly confused by the documentation in terms of the meaning WEBUI_HOST parameter.

Thank you!
