### ISSUE TITLE
Remove bcrypt semi-auto hash

### ISSUE THREAD

**Issue by thatssorude** [wg-easy/wg-easy#1223]
The dumbest and ugliest thing ive ever seen
Its not working, just not.Not gonna report bugs and errors since its just BAD DESIGN
It shouldnt be this way, just remove that and use just password before.If you want to use more secure hashing algo do it automatically
Please revert it and stop committing useless updates.At some point product is already finished and only thing that product need is fixing bugs, not creating them with stupid updates

And no offense, i love this project, it makes my life much easier, but this…
Just keep it simple and easy(this is wg-easy, not wg-i-can-show-my-every-skill-in-this-project)

**Comment by tetuaoro** [comment]
Haha, you are really `rude` but you are right. I was planning to remove the password from the environment and just set it from the UI, but it seems we need a database and not just a file. So, need the owner's opinion.

**Comment by jeromecc** [comment]
The script you provided to generate this password hash does not work.

```
docker run ghcr.io/wg-easy/wg-easy wgpw 'mypassword'
Error: Cannot find module '/app/wgpw'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by kaaax0815** [comment]
There is work going into making everything easier. Just stay tuned
