### ISSUE TITLE
IP address assignement should be CIDR compliant, using an "x" is good for newbies but bad for entreprise adoption

### ISSUE THREAD

**Issue by GhaziTriki** [wg-easy/wg-easy#1224]
https://github.com/wg-easy/wg-easy/blob/5dad038796f7a986ab7501e1ad352cb266a359d8/src/lib/WireGuard.js#L242-L252

**Comment by eandersons** [comment]
There is a pull request #1003 for this functionality, and there has been unsuccessful attempts (#888 was not backwards compatible) to implement this previously.

Also, search for existing issues: [CIDR](/wg-easy/wg-easy/issues?q=is%3Aissue+CIDR).

**Comment by kaaax0815** [comment]
Implemented with #1347
