### ISSUE TITLE
Download config file as a .conf instead of .txt

### ISSUE THREAD

**Issue by altbert** [wg-easy/wg-easy#1225]
Will it be possible to change the default download extension of the client configuration file with the extension ".conf" instead of ."txt".
I propose this change to avoid the step of renaming the file when trying to import it from the WireGuard app on Android or iPhone.

**Comment by tetuaoro** [comment]
It's already with `.conf` extension. I tested with the android, ios and laptop.

**Comment by altbert** [comment]
I see, from Firefox PC the file download as .conf but from Firefox mobile as .txt.
Seems that Firefox mobile on Android changes the extension to .txt.
Probably a Firefox Behavior.
![wg-admin](https://github.com/user-attachments/assets/68e76ec8-aff5-43ad-98dc-43eb597fe4a9)

**Comment by eandersons** [comment]
See also #417 and #796 for more information regarding this.
