### ISSUE TITLE
Prototype Pollution Check

### ISSUE THREAD

**Issue by offizium-berndstorath** [wg-easy/wg-easy#1232]
https://github.com/wg-easy/wg-easy/blob/1416613cc671c0bb86eca6708740482fa965806a/src/lib/Server.js#L205-L208

Is there really a issue with prototype polution? 
The key of an object has to be `__proto__` but this creates a object with `{ clientId: '__proto__' }`

Maybe the better solution is to check if the clientId is a valid uuid with something like zod

**Comment by pheiduck** [comment]
This was suggested by a Security Sanitizer.
If you have a better solution please make a PR. :)

**Comment by kaaax0815** [comment]
Implemented with https://github.com/wg-easy/wg-easy/pull/1244
