### ISSUE TITLE
There is no admin authorization

### ISSUE THREAD

**Issue by krutpik** [wg-easy/wg-easy#1235]

**Comment by pheiduck** [comment]
If you mean PASSWORD authorization then please read the README of production branch.
Master is our dev branch, I don't have permissions to rename the branch.
https://github.com/wg-easy/wg-easy/tree/production

**Comment by krutpik** [comment]
> If you mean PASSWORD authorization then please read the README of production branch. Master is our dev branch, I don't have permissions to rename the branch. https://github.com/wg-easy/wg-easy/tree/production

It says enter the hash of the administrator password. I created a password hash using docker, but when logging into wg-EasyUI, the password is not requested.

**Comment by pheiduck** [comment]
I may don't get what your problem is here. Please provide more information.

**Comment by tennnessse** [comment]
I have the same issue. When running in Docker Compose, the control panel does not prompt for a password.

**Comment by pheiduck** [comment]
https://github.com/wg-easy/wg-easy/blob/production/README.md

**Comment by tennnessse** [comment]
> https://github.com/wg-easy/wg-easy/blob/production/README.md

Oops, sorry, I used the master branch instead of production. Everything is working now

**Comment by pheiduck** [comment]
Pending release will provide all features to **production** https://github.com/wg-easy/wg-easy/pull/1199
