### ISSUE TITLE
Documentation Update Needed: Clarification on WEBUI_HOST parameter change, parameter should be UI_HOST, not WEBUI_HOST if you run wg-easy in local server and want to use public IP address or domain name for accessing the WireGuard server from external clients.

### ISSUE THREAD

**Issue by Inforegister** [wg-easy/wg-easy#1237]
**Describe the bug**
Hello wg-easy development team,

I would like to report an issue with the documentation regarding the environment variables used in the Docker run command. 
The documentation and examples often mention WEBUI_HOST, which is incorrect. The actual environment variable that should be used to set the internal user interface IP is UI_HOST.

UI_HOST: This environment variable should be used to set the internal IP address for accessing the WireGuard user interface.

If you are using WEBUI_HOST in docker command for example to make web user interface to work different ip (internal IP) address and you want the peer endpoint to be different(you want to use public ip to access wireguard server what is in LAN subnet) you have to use WG_HOST parameter for that.  **just sidenote for to none tech people**

The documentation and examples often mention WEBUI_HOST, which is incorrect. The actual environment variable that should be used to set the internal user interface IP is UI_HOST. But the problem is that the current documentation clearly explains to use WEBUI_HOST, but it doesn't work, the docker container only restarts and thats it, but if you use UI_HOST parameter it works like charm and if you download conf file everything works and you don't have to change nothing in text editor

**To Reproduce**

1. Use that docker command to 

docker run -d \
  --name=wg-easy \
  -e LANG=en \
  -e WG_HOST=9x.xxx.xx.xxx \ #public ip aka external ip
  -e PASSWORD_HASH=example hash goes here  \
  -e PORT=51821 \
  -e WEBUI_HOST=192.xxx.xx.xxx \ #internal ip what you have in your LAN network to access user interface
  -e WG_PORT=51820 \ #dont forget NAT rule for that in router to set up
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \ 
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy

This doesn't work because docker container only restarts and user interface doesn't work

if you use in you server "docker ps" than it only shows that container restarts and thats it

**Expected behavior**

BUT if you use this command everything works like charm 

docker run -d \
  --name=wg-easy \
  -e LANG=en \
  -e WG_HOST=9x.xxx.xx.xxx \ #public ip aka external ip
  -e PASSWORD_HASH=example hash goes here  \
  -e PORT=51821 \
  -e UI_HOST=192.xxx.xx.xxx \ #internal ip what you have in your LAN network to access user interface
  -e WG_PORT=51820 \ #dont forget NAT rule for that in router to set up
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy

Basically just change parameter WEBUI_HOST to UI_HOST in docs than everybody else know if they want to run wireguard server in LAN and end user wants to access that server from different computer and router via public IP 

Please update the documentation to reflect the correct usage of these environment variables. 

**Screenshots**
<img width="623" alt="image" src="https://github.com/user-attachments/assets/152893ae-4acd-466f-a924-ec56064d6f4a">

 Additionally, the role of WG_HOST is not clearly explained. This has led to confusion when setting up wg-easy with Docker. When you are junior level sometimes things are hard to understand, could you please add "hostname/public ip" or something to WG_HOST description to make it more understandable how you can use that parameter 

WG_HOST: This environment variable should be used to set the public IP address or domain name for accessing the WireGuard server from external clients.

<img width="617" alt="image" src="https://github.com/user-attachments/assets/daf53f5e-4551-406a-9f03-07b959d67ca4">

**Additional context**
Thank you for making wireguard GUI it makes none tech people life much easier and sorry for my english not my native language

**Comment by pheiduck** [comment]
Please make a PR then we can adopt your changes. Thanks!

**Comment by pheiduck** [comment]
BTW WEBUI_HOST is optional and is not required.

**Comment by Inforegister** [comment]
Hello there,

First of all, I have to apologize, because I didn't read the documentation properly, because it was Friday and it was necessary to get the application up and running quickly. I have to clarify my content little bit, the argument that you have to use WEBUI_HOST parameter, is wrong what I claimed in first place, because I didn't check things before I started writing an issue about it. If you use WG_HOST,everything works like charm you just have to use router public IP in the parameter to set up the docker container via command line, not the LAN server IP what I did when I tried to install the wireguard. That was the mistake I made at first installation, because I was in rush and didn't read the documentation properly. The docker container listens 0.0.0.0 IP from both ports, webui and the public UDP port of your VPN server. So that means you can access the webui and the public UDP port of your VPN server from every IP you want and it doesn't matter are you using WEBUI_HOST or not(what should be UI_HOST instead if you want to use that parameter), but you don't have to use UI_HOST because WG_HOST works like it has to. At first, I thought that these two parameters WG_HOST and UI_HOST had to be used so that the container would know which is webui port and the public UDP port of your VPN server, but I didn't read the documentation properly , because I was in a hurry. In summary, the WG_HOST parameter works beautifully, you just need to use the router's public IP. But **if you are a beginner like me, then you have to remember that anyone who wants, can access the webui user account manager from the outside, if you don't have a firewall rule or some other solution what blocks access to that port from the outside.** In short, the whole issue is simply that the WEBUI_HOST parameter does not work, but the UI_HOST works instead, but it is not necessary to use this parameter to set up docker container, because the WG_HOST parameter does the whole job beautifully, you just have to add the router public IP  as a parameter and that's it.
