### ISSUE TITLE
No authentication, PASSWORD_HASH is set 

### ISSUE THREAD

**Issue by ezhil56x** [wg-easy/wg-easy#1240]
**Describe the bug**
I have added PASSWORD_HASH as an environment variable and there is no authentication

**To Reproduce**
```
  docker run -d \
  --name=wg-easy \
  -e LANG=en \
  -e WG_HOST=vpn.server.com \
  -e PASSWORD_HASH='hashed_password_here' \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -e WG_DEVICE=ens18 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy
```

**Expected behavior**
User should be authenticated

**Comment by pheiduck** [comment]
See readme from: https://github.com/wg-easy/wg-easy/tree/production

**Comment by ezhil56x** [comment]
@pheiduck Missed production branch. Login is fixed. Is there any issue this the latest release 13? I am not able to access internet as well as local network when connected to vpn. 

Found this https://github.com/wg-easy/wg-easy/issues/953

Is this fixed or yet to be fixed?

**Comment by pheiduck** [comment]
We will Release version 14 next week. It will fix a bring a lot of new features.
