### ISSUE TITLE
wg-password script

### ISSUE THREAD

**Issue by General13K7** [wg-easy/wg-easy#1241]
docker run ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '/app/wgpw'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.15.1

after I did command docker run ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD

**Comment by ezhil56x** [comment]
This worked
```
docker run ghcr.io/wg-easy/wg-easy:nightly wgpw YOUR_PASSWORD
```

**Comment by General13K7** [comment]
generated hash but after copy it to docker-compose and run it - no password at all - clear enter to WEB UI

**Comment by ezhil56x** [comment]
There is a different readme for production 

https://github.com/wg-easy/wg-easy/tree/production
