### ISSUE TITLE
Container always stopped with exit code 143

### ISSUE THREAD

**Issue by 0verEngineer** [wg-easy/wg-easy#1258]
**Describe the bug**
Every once in a while the container does not run because it has exited with exit code 143, i run a lot of other containers on the same server and wg-easy is the only one with this problem.

**Comment by eandersons** [comment]
Are there any logs before exiting?

**Comment by 0verEngineer** [comment]
I did not see anything special

**Comment by tetuaoro** [comment]
🤔

**Comment by tetuaoro** [comment]
What's the configuration ? Host, docker, and ENV variables.

**Comment by 0verEngineer** [comment]
``version: "3.8"

services:
  wg-easy:
    environment:
      - WG_HOST=dyn.dns.domain

      # Optional:
      - PASSWORD=password
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.178.24
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.178.26/24, 192.168.178.24/24, 10.0.1.0/24

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.wireguard.entrypoints=http"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.home`)"
      - "traefik.http.routers.wireguard.service=wireguard"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"


networks:
  traefik-network:
    external: true
``

It is a fedora VM running on my Truenas machine

**Comment by tetuaoro** [comment]
Sorry by docker I mean wg-easy version. My fault

**Comment by 0verEngineer** [comment]
Up to date, i updated a few days ago but this issue is not new.

**Comment by tetuaoro** [comment]
Ah nvm, you used weejewel version

**Comment by tetuaoro** [comment]
> Up to date, i updated a few days ago but this issue is not new.

Yeah the image is ghcr.io/wg-easy

**Comment by tetuaoro** [comment]
Look at the readme

**Comment by 0verEngineer** [comment]
Oh interesting, do you know if i can just switch the images?

**Comment by tetuaoro** [comment]
Make sure to follow the production branch, not the master branch

**Comment by tetuaoro** [comment]
Follow https://github.com/wg-easy/wg-easy/blob/production/docker-compose.yml
