### ISSUE TITLE
WG-Easy api's giving 500 error

### ISSUE THREAD

**Issue by HassanFlutterDev** [wg-easy/wg-easy#1260]
i am calling /api/wireguard/client
but it's giving 

{
    "statusCode": 500,
    "stack": []
}

but it's session api is working well

**Comment by tetuaoro** [comment]
How ?! Via curl ?!

**Comment by HassanFlutterDev** [comment]
<img width="1680" alt="Screenshot 2024-08-09 at 10 56 27 PM" src="https://github.com/user-attachments/assets/74ac017c-7726-4e8b-8863-8527de6d54b4">
i am calling in postman

**Comment by HassanFlutterDev** [comment]
> How ?! Via curl ?!

can you help me which is correct way

**Comment by tetuaoro** [comment]
I'm not sure, but you can't get a session like that.

**Comment by tetuaoro** [comment]
Ah your @ip is expose

**Comment by HassanFlutterDev** [comment]
> I'm not sure, but you can't get a session like that.

can you help me how can it be? i want to make or delete user config from apis

**Comment by tetuaoro** [comment]
The route `/api/wireguard/client` (get) is secure.

**Comment by tetuaoro** [comment]
Are you use PASSWORD ??

**Comment by tetuaoro** [comment]
First create a session via post /api/session and if it returns success = true, then try call get /api/wireguard/client. Sorry I am on phone

**Comment by HassanFlutterDev** [comment]
yes it's gives me success response

**Comment by HassanFlutterDev** [comment]
> You can also handle the session with a authorization header instead of cookies. api documentation would be easier for people. mentioned here #1179

can you give me api documentation i am not finding it

**Comment by HassanFlutterDev** [comment]
can you help me how can i run that api's with authorization

**Comment by pheiduck** [comment]
Later one we should implement a api token so now password breach if the application is insecure.

**Comment by HassanFlutterDev** [comment]
yes i got it 

it's good

> The easiest would be to add the Authorization header
> 
> https://github.com/wg-easy/wg-easy/blob/4e79d0ee03211dc6148db66ee7e4dcd24c8098ac/src/lib/Server.js#L144-L147
> 
> make a request with `Authorization` header with the value being your password you would type in the ui. just make sure the connection is encrypted
