### ISSUE TITLE
Problem after upgrading to version 14

### ISSUE THREAD

**Issue by Andruxa0** [wg-easy/wg-easy#1263]
I did everything according to the instructions:
Updated it like this:
docker stop wg-easy
docker rm wg-easy
docker pull ghcr.io/wg-easy/wg-easy

After that I generated a password hash:
docker run ghcr.io/wg-easy/wg-easy wgpw mypass

Pasted the hash into
     docker run -d \
  --name=wg-easy
  -e LANG=en.
  -e WG_HOST=myip \.
  -e PASSWORD_HASH='hash'.
  -e PORT=51821 \.
  -e WG_PORT=51820 \.
  -v ~/.wg-easy:/etc/wireguard \.
  -p 51820:51820/udp.
  -p 51821:51821/tcp.
  --cap-add=NET_ADMIN.
  --cap-add=SYS_MODULE.
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy.

And after that, when you enter the password in the control panel, the login load is infinite. If you enter a wrong password, it gives an error instantly. If you enter the correct password - endless loading.

Translated with DeepL.com (free version)

**Comment by coppcam** [comment]
I have this issue aswell

**Comment by zaphod007** [comment]
same here, doesnt work

**Comment by ikrsdo** [comment]
same here. but little different.

I can access with direct port forward like http://vpn.mydomain.com:51821 using password.

Behind the cloudflare tunnel (https://vpn.mydomain.com) is exactly like in the first comment "**when you enter the password in the control panel, the login load is infinite. If you enter a wrong password, it gives an error instantly. If you enter the correct password - endless loading.**"

Before previous version without "password_hash" I can use cloudflare tunnel to secure GUI access.

**Comment by moppman** [comment]
This could be a caching issue. See https://github.com/wg-easy/wg-easy/issues/1253#issuecomment-2275076711 for an explanation and a possible solution.

**Comment by ikrsdo** [comment]
Thanks  @moppman 👍 
You are right. Disabled cache on cloudflare and it works :)


![image](https://github.com/user-attachments/assets/cfb70048-5d78-4d0b-a6b5-60e7fc02b2f9)

**Comment by Andruxa0** [comment]
> Я все сделал по инструкции: Обновил так: docker stop wg-easy docker rm wg-easy docker pull ghcr.io/wg-easy/wg-easy
> 
> После этого я сгенерировал хэш пароля: запуск docker ghcr.io/wg-easy/wg-easy wgpw mypass
> 
> Вставил хэш в docker run -d --name=wg-easy -e LANG=en. -e WG_HOST=myip . -e PASSWORD_HASH='хэш'. -e PORT=51821 . -e WG_PORT=51820 . -v ~/.wg-easy:/etc/wireguard . -p 51820:51820/udp. -p 51821:51821/tcp. --cap-add=NET_ADMIN. --cap-add=SYS_MODULE. --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --перезапускать, если не остановлено ghcr.io/wg-easy/wg-easy.
> 
> И после этого, когда вы вводите пароль в панели управления, загрузка входа в систему бесконечна. Если вы вводите неправильный пароль, он мгновенно выдает ошибку. Если вы вводите правильный пароль - бесконечная загрузка.
> 
> Переведено с помощью DeepL.com (бесплатная версия)

**Comment by Andruxa0** [comment]
Indeed, it's enough just to clear the cache and everything works. Thank you all!

**Comment by adrinux** [comment]
Everything works after clearing the cache, **except** authentication. If you had Authentication set up before you need to replace your PASSWORD env with PASSWORD_HASH.

See https://github.com/wg-easy/wg-easy/issues/1269

And the example dockerfile in the project README.
