### ISSUE TITLE
Updating container causes webpage to fail.

### ISSUE THREAD

**Issue by spenceradolph** [wg-easy/wg-easy#1266]
**Describe the bug**
I updated the container like the UI stated, but then I now can only see the loading spinner when browsing to the page.

**To Reproduce**
- update container using commands provided by readme
- start container using same command as last time
- visit web page and see the loading spinner

**Expected behavior**
It should show the normal webpage.

**Additional context**
Chrome console is indicating the following error:
"ReferenceError: restoreConfig is not defined"

Here is the command I am using to run wg-easy.
```
docker run -d --name wg-easy --network private --restart unless-stopped -e WG_HOST=vpn.mydomain.io -e WG_ALLOWED_IPS=10.0.0.12/32 -e WG_POST_UP='<snipped iptables rules>' -v ~/.wg-easy:/etc/wireguard -p 51820:51820/udp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" ghcr.io/wg-easy/wg-easy
```

**Comment by spenceradolph** [comment]
Solution was found via https://github.com/wg-easy/wg-easy/issues/1263

**Comment by moppman** [comment]
This is a caching issue, see
https://github.com/wg-easy/wg-easy/issues/1253#issuecomment-2275076711 and https://github.com/wg-easy/wg-easy/issues/1263

Disabling caching in your browser for  your wg-easy domain via the browser console or clearing the cache should fix things.

**Comment by TheAndrey** [comment]
Great update! 🫣
Now the control panel is available to anyone on the Internet. This is very bad. 😡
There should be **no way to disable authentication** in such a tool. The application must require the user to set a password otherwise it will not run.
