### ISSUE TITLE
Add option to change wg address

### ISSUE THREAD

**Issue by einalex** [wg-easy/wg-easy#1267]
**Describe the bug**
The host's ip address cannot be set.
This makes it very hard to add wg-easy to an existing wireguard network, where another host already has the .1 address.

**Expected behavior**
Provide an environment variable to set the host IP. (ADDRESS field in wg0.conf)

**Comment by jiawei2912** [comment]
I can't seem to find anything with "CIDR" or "address" in #1179, and I'm facing the same issue as @einalex now. I already have another host with the .1 address and that wg0 keeps defaulting to .1 in its subnet makes things a bit difficult.

As far as I can understand from [wgHelper.ts](https://github.com/wg-easy/wg-easy/blob/e1ed93674d131eaf65f9285b451e8481d1b35e26/src/server/utils/wgHelper.ts#L49), I don't believe that it is actually possible to accomplish what we need as the given CIDR seems to be normalised before it's incremented by 1n to get the first usable IP in a given subnet. 

The relevant line being:
```
const ipv4Addr = stringifyIp({ number: cidr4.start + 1n, version: 4 });
```
 
as taken from wg-easy/src/server/utils/wgHelper.ts:

```
generateServerInterface: (
    wgInterface: InterfaceType,
    hooks: HooksType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const cidr4 = parseCidr(wgInterface.ipv4Cidr);
    const cidr6 = parseCidr(wgInterface.ipv6Cidr);
    const ipv4Addr = stringifyIp({ number: cidr4.start + 1n, version: 4 });
    const ipv6Addr = stringifyIp({ number: cidr6.start + 1n, version: 6 });

    const address =
      `${ipv4Addr}/${cidr4.prefix}` +
      (enableIpv6 ? `, ${ipv6Addr}/${cidr6.prefix}` : '');

    return `# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${wgInterface.privateKey}
Address = ${address}

```

I also saw something about setting WG_DEFAULT_ADDRESS in a few other posts, but I've tried that in docker-compose.yml to no avail. wg0's address doesn't change. 

Might I suggest modifying it to work such that when given "10.10.10.2/24", it's taken that the wg0 should be of the address 10.10.10.2 while the subnet is taken to be /24? 

For context, I'm trying to configure wg-easy to work without masquerade as it's important that our firewall can see the actual SRC IPs of the VPN clients.

**Comment by kaaax0815** [comment]
you can change the cidr in v15 using the admin panel. if you have any problems please create a new issue
