### ISSUE TITLE
Latest version breaks Web UI working behind Cloudflare Zero Trust

### ISSUE THREAD

**Issue by goake** [wg-easy/wg-easy#1268]
Web UI no longer works behind Cloudflare Zero Trust. It doesnt get beyond pressing the login button.

Web UI works no problem connecting via local network, so know that PASSWORD_HASH has been implemented correcty.

Also, tried removing PASSWORD_HASH, hangs immediately on entry via Cloudflare zero Trust, but works fine via local network.

Reverting to version 13 averything works fine, so I know its not a Cloudflare problem

**Comment by venil7** [comment]
for me web ui doesnt work even without cloudflare

**Comment by tetuaoro** [comment]
> Web UI no longer works behind Cloudflare Zero Trust. It doesnt get beyond pressing the login button.

Hi, try clear cache your cloudflare service

**Comment by goake** [comment]
Tried clearing cache on cloudflare service, didnt work. So tried clearing cache on browser, and that did the trick.

Thank you!
