### ISSUE TITLE
Keeping PASSWORD while not setting PASSWORD_HASH disables authentication

### ISSUE THREAD

**Issue by moppman** [wg-easy/wg-easy#1269]
This is something I noticed when people were having issues after updating to v14.
Some context:

* In order to avoid having people write cleartext passwords in their docker compose file, PR #1116 introduced a new environment variable PASSWORD_HASH that was supposed to supercede the old PASSWORD variable.
* This was a potentially breaking change, as was discussed e.g. in PR #1123 and people agreed it should be announced with a post-login notification **before** the actual update so users would know things would change.

* However, in PR #1180  a fallback to the old PASSWORD variable was prematurely removed in a very unfortunate way:
```diff
- const requiresPassword = !!PASSWORD || !!PASSWORD_HASH;
+ const requiresPassword = !!PASSWORD_HASH;
```

What that means:
 If users update from v13 to v14 (e.g. by using the `:latest` tag to get the stable wg-easy production version) and if they keep their old PASSWORD env variable without adding a PASSWORD_HASH variable, **authentication is effectively disabled**, and they maybe even won't notice it.

That behavior is exactly what caught users by surprise in #1261. 
IMHO breaking changes regarding sensitive areas like authentication should have a safe fallback or at least fail hard and early.

Thanks for reading!

**Comment by pheiduck** [comment]
@moppman thanks for clarifying the new behavior even better.

So I've added a note in the release PR that people should block traffic through the wireguard ports before upgrading to 14 and editing the docker-compose file or docker run.

Pinned the issue so people can revise if there have this issue.

**Comment by TheAndrey** [comment]
Great update! 🫣
Now the control panel is available to anyone on the Internet. This is very bad. 😡
There should be **no way to disable authentication** in such a tool. The application must require the user to set a password otherwise it will not run.

**Comment by pheiduck** [comment]
@TheAndrey this will may possible with the next version: https://github.com/wg-easy/wg-easy/pull/1228

**Comment by pheiduck** [comment]
> But using `:latest` tag is arguably bad too.

I don’t think so, if you use watchtower to keep your containers up to date you need this tag.

**Comment by pheiduck** [comment]
> add tag `:14` and update without worrying (because new minor changes are released under 14.1 and 14).

I didn’t know where you have this information, due we don’t have this behavior / mechanism.

**Comment by nicolasluckie** [comment]
> If users update from v13 to v14 (e.g. by using the `:latest` tag to get the stable wg-easy production version) and if they keep their old PASSWORD env variable without adding a PASSWORD_HASH variable, **authentication is effectively disabled**, and they maybe even won't notice it.

This is exactly what happened to me, I overlooked the instructions when upgrading from v13 to v14 using the `:latest` tag and forgot to change `WEB_PASSWORD` to `PASSWORD_HASH` using this page: [How_to_generate_an_bcrypt_hash.md](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md)

Thankful I found this issue here and got it resolved quickly, thanks!

**Comment by yllekz** [comment]
Is there a way to configure the Web UI creds directly in the web UI itself? I just found this issue like quite a few others. Doing it in terminal is possible sure, but could there be some kind of way to do it in the control panel just to get it over and done with?

**Comment by Wuemeli** [comment]
Why not add an interactive setup guide? Instead of setting everything in the .yml etc files?

**Comment by Mat-DB** [comment]
> I overlooked the instructions when upgrading from v13 to v14

Where can I find the instruction on upgrading?
I always read the changelog of a service before upgrading, but can't find a clear changelog easily for wg-easy.
Thanks!

**Comment by divadwong68** [comment]
> > I overlooked the instructions when upgrading from v13 to v14
> 
> Where can I find the instruction on upgrading? I always read the changelog of a service before upgrading, but can't find a clear changelog easily for wg-easy. Thanks!

There's a but Update button near the logoff when there's an update. When you click on it, it brings you to https://github.com/wg-easy/wg-easy#updating Unfortunately, I don't see anything about making changes to the yml file regarding the password here.

**Comment by divadwong68** [comment]
What I finally ended on was creating a password.env file in the same directory as the docker-compose.yml.
In the password.env contains PASSWORD_HASH='$2a$12$zLIKnCfqsT8lhsvrhGR.CwklGRg4zQ92PpKoKa3XCdL9.KWzewBBu'
as an example.
The instructions in creating your pw hash is here: https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md

Added to docker-compose
env_file: ./password.env
to the line above environment: 

docker-compose down
docker-compose up -d

**Comment by vanillamage** [comment]
I wanted this tool to help me, but it will never go inside. https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
![2024-08-23_10-17-37](https://github.com/user-attachments/assets/0749db1d-4e73-41ff-81f2-1af77226e35f)

**Comment by kaaax0815** [comment]
@vanillamage please post your relevant files. docker run command or docker compose file

**Comment by vanillamage** [comment]
docker run -d \
  --name=wg-easy \
  -e LANG=ru \
  -e WG_HOST=хх.хх.хх.хх \
  -e PASSWORD_HASH='$2a$12$IAdbGNZ672buVzdWsR5/eeb7/WHdqiBwOLeKbhoyb1HIbx8.DMJHe' \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy


docker run ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD
PASSWORD_HASH='$2a$12$IAdbGNZ672buVzdWsR5/eeb7/WHdqiBwOLeKbhoyb1HIbx8.DMJHe' // literally YOUR_PASSWORD

> @vanillamage пожалуйста, разместите соответствующие файлы. команда docker run или файл docker compose

**Comment by kaaax0815** [comment]
If you login with password `YOUR_PASSWORD` it should work.

If not see if there are any errors in the browser and server console

**Comment by vanillamage** [comment]
> Если вы войдете в систему с паролем, `YOUR_PASSWORD` это должно сработать.
> 
> Если нет, проверьте, нет ли каких-либо ошибок в браузере и консоли сервера

Damn, it was surprisingly obvious. thanks :-))))

**Comment by pitkes22** [comment]
Please strongly consider making this fail-safe as soon as possible and moving the `:latest` label from this version (even reverting it back to `v13` to prevent further users from experiencing this issue). It is absolutely irresponsible to push a change like this in a project dealing with VPN and security, which are inherently sensitive topics. I cannot comprehend how a change like this could have been published. 🤦‍♂️

There are several solutions that can be easily implemented to fix this issue:
1. If `PASSWORD` is set, the container should crash or not start, providing a warning about the migration to `PASSWORD_HASH`.
2. If `PASSWORD_HASH` is not set, the container should not allow anonymous access. If this behavior is desirable, it should be explicitly set, for example, by using a new option like `DISABLE_AUTH`.

Honestly, this is exactly why small projects like this cannot be trusted. When basic security issues aren't addressed promptly, it makes me seriously reconsider using this project at all. The fact that you've been aware of this problem for two weeks and still haven't fixed it is just crazy. This level of neglect for such a critical issue is unacceptable. :-1: :-1: :-1:

**Comment by pheiduck** [comment]
Container should exit with code 1 and refer to PASSWORD_HASH + Guide.

**Comment by kaaax0815** [comment]
This is now fixed. If you update the container (or any new user) it will fail if the old `PASSWORD` variable is set

**Comment by AzureSwallow** [comment]
I solved this issue.

The solution is too easy.

1st. Make the password hash using https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
       E.g., 
       docker run ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD
       PASSWORD_HASH='$2a$12$M4ffCTMh9i1bJTn9FwuBY.dDNCdcpuiWficLuJ4LzxTsbR4onb/YC'

2nd. Please input the env value, NAME: PASSWORD_HASH, and value: hashed code without single quotes.
       E.g. Please take a look at the picture (my environment value on Portainer)

3rd. Save and restart the wg-easy; then you can access it with YOUR_PASSSWORD

![1](https://github.com/user-attachments/assets/79e8d7c9-eff1-4e4a-8c31-6a245af885b8)

**Comment by ralfawilke** [comment]
When you run wg-easy on a Synology:
I managed to get the PASSWORD_HASH as follows:
1) Login with root permission via SSH. [https://kb.synology.com/en-global/DSM/tutorial/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet]
2) run: 
sudo docker run -it ghcr.io/wg-easy/wg-easy wgpw YOURPASSWORD
