### ISSUE TITLE
! GitHub Wiki pages can be changed/modified by ANYONE

### ISSUE THREAD

**Issue by Glup3** [wg-easy/wg-easy#1273]
**Describe the bug**
I noticed someone changed the pihole wiki section. In order to verify my theory I created my own test page.

https://github.com/wg-easy/wg-easy/wiki/Wiki-can-be-modified-by-anyone

**To Reproduce**
1. Go to wiki pages
2. New Page button is visible

**Expected behavior**
only maintainers can update wiki

**Additional context**

**Comment by Glup3** [comment]
I have reverted the changes for the pihole section. Check out the revision tab

**Comment by pheiduck** [comment]
Okay, I restricted the wiki edit access to Team Members. If something needs to be changed or added there. Let me know via Issue.

**Comment by Glup3** [comment]
alright, nice thank you!
