### ISSUE TITLE
[Feat]: Simple Stats API

### ISSUE THREAD

**Issue by jdevera** [wg-easy/wg-easy#1285]
### Description

I'd like to request the creation of an API that exposes:
* Number of configured peers
* Number of connected peers

My usecase: I want to show that in a [Homepage](https://gethomepage.dev/) dashboard.

### Suggested Solution

An API endpoint (authenticated or not) that returns this payload:
```json
{
  "configured_peers": 10
  "connected_peers": 3
}
```

### Alternatives

A second docker container with access to the host docker socket and then run something in the WG container that gets the latest handshake time and figures out if they are connected (I'm guessing, did not check how this is done for the UI)

`wg show wg0 latest-handshakes`

**Comment by AKEB** [comment]
http://localhost:51821/metrics/json After closing the pull request and adding the ENABLE_PROMETHEUS_METRICS Envronment

**Comment by kaaax0815** [comment]
@jdevera #1299 got merged

**Comment by jdevera** [comment]
I'm impressed with how quickly this got added, gonna test it right now!

**Comment by jdevera** [comment]
Fantastic! This is what I wanted to get in the end:
![CleanShot 2024-08-24 at 00 07 13 - Google Chrome - VRT Homelab@2x](https://github.com/user-attachments/assets/be1615df-aa75-4d34-ba5d-e857f5651f79)
