### ISSUE TITLE
[Feat]: Conection to a client? How? Site 2 Site oder Hoste Mode?

### ISSUE THREAD

**Issue by PaulEins** [wg-easy/wg-easy#1292]
### Description

Hi,

I now have a VPN router with WireGuard support. The connection to the “WireGuard” server, which runs in the Synology docker, works.
But now I want the Synology to be able to access the clients there. The goal is that I can enter the path in the SS of a camera so that it goes into the Docker container and there to the camera that is in the VPN router.

Problem. How do I change it or set it up so that the WireGuard container is not in its own networker, but in host mode? I have heard that this has to be done first. I have Portianer, can I simply change this or should I rather reinstall it with better settings.

Or is Site To Site WireGuard possibe?

What cna i do? I will conect from my SS the camera, into my docker WireGuard, into my VPN router into my Cam by my VPN router.

### Suggested Solution

I dont anderstand this box.

**Comment by AKEB** [comment]
Hi. Try removing the port setting from the wirefuard docker and add a network_mode: host setting

**Comment by warioishere** [comment]
trying the same here, I need access from my wireguard server to my clients, but they arent pingable and reachable.
I am using the follwing config;

```
docker run -d \
  --name=wg-easy-test \
  --network=host \
  -e LANG=de \
  -e WG_HOST=mydomain.com \
  -e PASSWORD_HASH='xxx' \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ./.wg-easy:/etc/wireguard \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy:latest
```

i added 
`sudo sysctl -w net.ipv4.ip_forward=1`
and
`sudo sysctl -w net.ipv4.conf.all.src_valid_mark=1`

manually.

But the clients then dont have internet access and I neither cant ping them too

Can anyone help me?
