### ISSUE TITLE
[Feat]: Release notes

### ISSUE THREAD

**Issue by goremykin** [wg-easy/wg-easy#1293]
### Description

I have just upgraded from 13 to 14 and realized that I don't have a login screen anymore because the PASSWORD env var was replaced with PASSWORD_HASH.

### Suggested Solution

It would be nice to have some release notes. Or maybe just a list of breaking changes 

### Additional Context

Thank you very much for this project, I appreciate it in any case even without a change log.

**Comment by pheiduck** [comment]
Would be nice if there is a CI to do this.

**Comment by OneWeekNotice** [comment]
In addition to offizium-berndstorath comment (not sure if I'm repeating what they were saying)

Proper [semantic versioning](https://semver.org/) would be a plus. `major.minor.patch`

This will help determine when there is a breaking chamge

This would also help when people use automation to update their docker containers/ software. 

For example. Software like [what up docker](https://github.com/fmartinou/whats-up-docker), where you can automatically upgrade a container on minor and patch but only notify when a major version comes up to read the release notes, backup and prepare for the breaking changes. 

Thanks for all the work on this
