### ISSUE TITLE
[Bug]: One Time Link Fixup

### ISSUE THREAD

**Issue by kaaax0815** [wg-easy/wg-easy#1302]
### Describe the bug

As mentioned here https://github.com/wg-easy/wg-easy/pull/1301#issuecomment-2298459550 there are some security implications that need to be adressed.

Mainly if a user creates a link but never uses it, or takes insanely long, a bad adversary has the time to bruteforce the otl code and get to the config as the otl endpoint is unsecured (by design)

### Expected behavior

Some possible ways of fixing it:
- auto erase code after set time (e.g 5 minutes)
- be able to delete otl in ui
- clearly state security implications to the user

**Comment by pheiduck** [comment]
@kaaax0815 Are you able to fix this bug?
