### ISSUE TITLE
[Bug]: No RX datas after clean install

### ISSUE THREAD

**Issue by jf84398942813** [wg-easy/wg-easy#1305]
### Describe the bug

Hi,
I have followed the step by step install instruction but the Wireguard client is not receive any packet.
tx growth, but rx stuck to 0.

I'm using Rpi 3B+ to host your solution.
The conaitner is running and I can access to Web UI to create users.

The config I have run :
`docker run -d \
  --name=wg-easy \
  -e WG_HOST=#MYDOMAIN# \
  -e PASSWORD=#MYPWD# \
  -e WG_PORT=27360 \
  -e WG_MTU=1500 \
  -e WG_DEFAULT_DNS=192.168.1.23 \
  -e UI_TRAFFIC_STATS=true \
  -e UI_SHOW_LINKS=true \
  -v ~/.wg-easy:/etc/wireguard \
  -p 27360:51820/udp \
  -p 27361:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy`

Thanks for your help.

### Expected behavior

rx and tx

**Comment by scmanjarrez** [comment]
I've noticed that my wireguard server stopped working after version 12 (no traffic), have you tried using `ghcr.io/wg-easy/wg-easy:12` image?

**Comment by jf84398942813** [comment]
I confirm using `ghcr.io/wg-easy/wg-easy:12` works.
using `ghcr.io/wg-easy/wg-easy:13` fail
using `ghcr.io/wg-easy/wg-easy:14` fail
using `ghcr.io/wg-easy/wg-easy:latest` fail

**Comment by jf84398942813** [comment]
okay ! I understand.
With your config, it works fine !

Thank you very much for your help.

**Comment by scmanjarrez** [comment]
Yes! thank you very much!

**Comment by jf84398942813** [comment]
> > what is the idle duration to turn off the activity on the web ui ?
> 
> 10 Minutes
> 
> https://github.com/wg-easy/wg-easy/blob/968d2b90a04b528c64ab441648577f25aa01cc63/src/www/index.html#L171

How can I update it by myself ?
Possible to add this param as env variable ?

**Comment by scmanjarrez** [comment]
> > > what is the idle duration to turn off the activity on the web ui ?
> > 
> > 
> > 10 Minutes
> > https://github.com/wg-easy/wg-easy/blob/968d2b90a04b528c64ab441648577f25aa01cc63/src/www/index.html#L171
> 
> How can I update it by myself ? Possible to add this param as env variable ?

If that value is only present in that static file, as a workaround you could copy the file locally, modify the value and mount the file in the container.
```
docker cp containername:/app/www/index.html .
# modify the value in the mentioned line
# and now mount the file using -v
-v $PWD/index.html:/app/www/index.html
# or docker compose
volumes:
  - ./index.html:/app/www/index.html
```
The drawback of this approach is that you need to do the change on each version, where index.html is updated (like always?)

**Comment by jf84398942813** [comment]
make sense, and works fine. Tested and approuved !
thank you very much for the workaround and your quick reply !
