### ISSUE TITLE
[Bug]: Endless loading

### ISSUE THREAD

**Issue by retrabaud-code** [wg-easy/wg-easy#1308]
Hello everyone!
Updated according to ReadMe, then run the, with my credentials:

```
  docker run -d \
  --name=wg-easy \
  -e LANG=de \
  -e WG_HOST=<🚨YOUR_SERVER_IP> \
  -e PASSWORD_HASH=<🚨YOUR_ADMIN_PASSWORD_HASH> \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy
```
wg easy went up, the site became accessible, but after logging in - endless loading.

**Comment by retrabaud-code** [comment]
It is worth noting that the authorization was successful and I see API requests in the network, as well as my old configurations

**Comment by retrabaud-code** [comment]
![image](https://github.com/user-attachments/assets/f8fd7751-8be4-47fc-a6e5-1722187acbc6)

**Comment by Hekzory** [comment]
Same for me, decided to update to latest docker image and got an endless loop in web gui

**Comment by awesomeaiden** [comment]
Same issue, happened after updating to latest docker image.

**Comment by retrabaud-code** [comment]
Hi, @offizium-berndstorath 
I understand your complaint against me, but resetting the cache did not help. I’ll tell you more, I logged in from different browsers and incognito mode, including

**Comment by moglerdev** [comment]
@retrabaud-code do use a reverse proxy (like nginx) or connect directly to the wg-easy web service? I had a similar issue that my reverse proxy cached some files.

**Comment by mattish91** [comment]
> @retrabaud-code do use a reverse proxy (like nginx) or connect directly to the wg-easy web service? I had a similar issue that my reverse proxy cached some files.

This was indeed the issue for me, after unchecking "Cache assets" it started working after a cache flush.

Life saver as i didn't notice this when i first updated the container and just realized i had an issue when i was supposed to reconfigure my new device.

**Comment by KaapaTeelb** [comment]
Same issue
