### ISSUE TITLE
[Feat]: Shadowsocks transport

### ISSUE THREAD

**Issue by mvasl** [wg-easy/wg-easy#1311]
### Description

With some ISP's and DPI providers starting to actively block Wireguard connections, it would be useful to have some sort of obfuscation of initial WG handshake and session in general.

Plain wireguard protocol is quite easy to detect and block when you have a way to sniff the traffic in a MitM manner.

### Suggested Solution

I propose adding a built-in optional shadowsocks server as an obfuscation layer into the image, controlled with an additional env variable in an on/off fashion.

### Additional Context

More discussions on the matter can ve found in https://github.com/net4people/bbs/issues/88 for example

**Comment by kaaax0815** [comment]
Using something like https://hub.docker.com/r/dockage/shadowsocks-server is the best way to do it. If you want you can test it and post a wiki entry on how to do it. Making this built in is out of scope
