### ISSUE TITLE
[Feat]: add an opportunity of fine tuning for clients

### ISSUE THREAD

**Issue by ashgrey74** [wg-easy/wg-easy#1317]
### Description

Hello, I need an opportunity of fine tuning the clients config. I have an old router, that doesn't support Preshared Key in the client. The wg0.conf is hardcocded, so I don't have an opportunity to edit it.

### Suggested Solution

Add a key for docker run command, that allows to manually edit the wg0.conf file.

**Comment by kaaax0815** [comment]
I don't think this is possible. It would require major rewrite of the Wireguard logic.
The only thing I could think of would be adding the option to disable the pre shared key for specific clients through the web ui
