### ISSUE TITLE
[Bug]: Wrong Link to wg-easy on TrueNAS Scale Electric-Eel Apps?

### ISSUE THREAD

**Issue by SelectLOL1** [wg-easy/wg-easy#1323]
### Describe the bug

![grafik](https://github.com/user-attachments/assets/50385098-e3c6-4f89-bfe9-7c2335a3348d)

As you can see the link goes to: [https://github.com/WeeJeWel/wg-easy](https://github.com/WeeJeWel/wg-easy)

But that repo seems tobe archived. Might hinder users like me from using it, if it looks like deprecated.

### Expected behavior

Work just fine!

**Comment by eandersons** [comment]
As far as I know, this has nothing to do with WireGuard Easy.

You should file an issue or make a pull request in [TrueNAS/charts](/truenas/charts) repository, as the wrong URL is from there. See [`charts/wg-easy/app_versions.json`](/truenas/charts/blob/master/charts/wg-easy/app_versions.json).
