### ISSUE TITLE
[Feat]: update wiki

### ISSUE THREAD

**Issue by CTPEJIKuH** [wg-easy/wg-easy#1324]
### Description

After the update, I lost the ability to update the wiki, please update this article:
https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Ansible#configuring-variables-and-vm-ip-address
I have already updated the Ansible roles so that they work correctly with password hash.

### Suggested Solution

replace string 43 from:   
- wg_easy_password: "mypassword"
to:
wg_easy_password_hash`: you need create a password hash `https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md`

**Comment by eandersons** [comment]
Just for reference about editing permission restriction: #1273

**Comment by pheiduck** [comment]
Will take care of it when I have time
