### ISSUE TITLE
[Bug]: New Features Unavailable using docker installation

### ISSUE THREAD

**Issue by Ihtesham-3914** [wg-easy/wg-easy#1325]
### Describe the bug

Hello, 

Hope you are doing well sir, the method you mentioned in the repository of how to install it using docker & ghcr.io/wg-easy/wg-easy 

I have the latest version installed buf i can't see  any new features on admin ui, only dark and lite theme improved. And chart showing just lines going up and down when user connected. 

No expire date, no onetime download link, no other features as well on the admin Panel. . 

Please update docker as well also tell me why i can't seeing these feature is there something wrong with my installation? 

Because i already updated it and make them true, WG_ENABLE_ONE_TIME_LINKS, WG_ENABLE_EXPIRES_TIME, etc  etc
Using docker run -d \

Please guide 

### Expected behavior

Waiting for Solution Dear Owner

**Comment by eandersons** [comment]
From ReadMe:

> For stable versions instead of nightly or development please read README from the production branch!

[Production branch](/wg-easy/wg-easy/tree/production) does not yet have features you mentioned.

If you want to use the latest features, you have to use Docker image with the tag `nightly`.

**Comment by Ihtesham-3914** [comment]
Hello, 

When will be these available on production branch?

**Comment by Ihtesham-3914** [comment]
Hello reply please

**Comment by rallep71** [comment]
ghcr.io/wg-easy/wg-easy:nightly make this or this ghcr.io/wg-easy/wg-easy:development

**Comment by kaaax0815** [comment]
@Ihtesham-3914 There is no ETA. Just wait. There will be documentation in the README on how to enable them
