### ISSUE TITLE
[Feat]: Support for Authentik // Disable Authentication

### ISSUE THREAD

**Issue by FreddieDK** [wg-easy/wg-easy#1329]
### Description

I'll like to have Authentik manage my authentication for wg-easy

### Suggested Solution

1. Support for OpenID // Auth2 
2. Being able to turn off Authentication and let Authentik manage it through proxy

**Comment by kaaax0815** [comment]
noted here https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297

**Comment by IRus** [comment]
What do you think about installing https://github.com/oauth2-proxy/oauth2-proxy as a proxy for wg-easy?

**Comment by khase** [comment]
This is already possible. 
I just setup such scenario.

If you omit the Password Hash variable form the environment than wg-easy won't require any authentication.
I am using authentik with a configured proxy provider and use it in combination with traefik forward auth middleware:
https://docs.goauthentik.io/docs/providers/proxy/server_traefik

**Comment by kaaax0815** [comment]
Are you using the latest version? There was a fix for 14. That stops the Container if Password-Hash is not supplied
