### ISSUE TITLE
[Bug]: Prometheus Datasource has no API path

### ISSUE THREAD

**Issue by hwiards** [wg-easy/wg-easy#1334]
### Describe the bug

Using the nightly version, I can not add the metrics endpoint to grafana via the prometheus data-source interface.

When using http://wg-easy:51821/metrics (via docker-network) as the Prometheus server URL, when clicking on Save & Test it reports:

When using GET:
- 404 Cannot find static asset /metrics/api/v1/query - There was an error returned querying the Prometheus API. 

When using POST:
- 405 Method Not Allowed - There was an error returned querying the Prometheus API.

Using the link in the browser gives the data like it is displayed in this screenshot. [1298](https://github.com/wg-easy/wg-easy/pull/1298)

### Expected behavior

It seems like the API path is missing and therefore the check fails.

**Comment by IRus** [comment]
@hwiards http://wg-easy:51821/metrics is not Prometheus server URL, it's metrics endpoint.

You need to setup a separate Prometheus container with and add this (http://wg-easy:51821/metrics) URL as target for scraping: https://prometheus.io/docs/prometheus/latest/getting_started/#configure-prometheus-to-monitor-the-sample-targets

**Comment by Winand** [comment]
> @hwiards http://wg-easy:51821/metrics is not Prometheus server URL, it's metrics endpoint.

But it is supposed to return a metrics page, right?
```
29034e85541e:/app# wget -O- http://localhost:51821/metrics
Connecting to localhost:51821 (127.0.0.1:51821)
wget: server returned error: HTTP/1.1 404 Cannot find static asset /metrics
```

**Comment by IRus** [comment]
@Winand yes, this feature was introduced recently and not yet landed into stable builds, you can use nightly tag.

But this is not Prometheus server, it's endpoints with metrics in Prometheus format or JSON.

<img width="686" alt="Screenshot 2024-09-04 at 13 54 16" src="https://github.com/user-attachments/assets/c09e7bbf-4822-4565-8e63-a64f1fc385d7">

<img width="686" alt="image" src="https://github.com/user-attachments/assets/664542fa-d838-4a38-8927-81d7aaef0d83">

One thing that maybe can be improved: is including more metrics in JSON endpoint.
