### ISSUE TITLE
[Bug]: Problems with nftables

### ISSUE THREAD

**Issue by raphael421** [wg-easy/wg-easy#1335]
### Describe the bug

I tried to start the container via docker compose. Standard configuration, I only changed the `WG_HOST` env variable to my domain. I get an error telling me that `modprobe` cannot change the directory because `/lib/modules` does not exist.  Due to the fact that the container doesn't turn on, I can't run a command in it and see what specifically is going on. In addition, `iptables` cannot initialize the `nat` table. If this information is important, my distribution is Arch and firewall is nftables.

### Expected behavior

The container turns on, I can access the web panel and connect some peers.

### Relevant log output

```shell
wg-easy  | 2024-08-30T21:28:18.058Z Server Listening on http://0.0.0.0:51821
wg-easy  | 2024-08-30T21:28:18.062Z WireGuard Loading configuration...
wg-easy  | 2024-08-30T21:28:18.064Z WireGuard Configuration loaded.
wg-easy  | 2024-08-30T21:28:18.064Z WireGuard Config saving...
wg-easy  | 2024-08-30T21:28:18.066Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | Error: Command failed: wg-quick up wg0
wg-easy  | [#] 
wg-easy  | [#] ip link add wg0 type wireguard
wg-easy  | [#] wg setconf wg0 /dev/fd/63
wg-easy  | [#] ip -4 address add 10.8.0.1/24 dev wg0
wg-easy  | [#] ip link set mtu 1420 up dev wg0
wg-easy  | [#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
wg-easy  | modprobe: can't change directory to '/lib/modules': No such file or directory
wg-easy  | modprobe: can't change directory to '/lib/modules': No such file or directory
wg-easy  | iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
wg-easy  | Perhaps iptables or your kernel needs to be upgraded.
wg-easy  | [#] ip link delete dev wg0
wg-easy  | 
wg-easy  |     at genericNodeError (node:internal/errors:984:15)
wg-easy  |     at wrappedFn (node:internal/errors:538:14)
wg-easy  |     at ChildProcess.exithandler (node:child_process:422:12)
wg-easy  |     at ChildProcess.emit (node:events:519:28)
wg-easy  |     at maybeClose (node:internal/child_process:1105:16)
wg-easy  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
wg-easy  |   code: 3,
wg-easy  |   killed: false,
wg-easy  |   signal: null,
wg-easy  |   cmd: 'wg-quick up wg0'
wg-easy  | }
```

**Comment by Zickles** [comment]
I am also having this error on alpine

**Comment by Zickles** [comment]
i fixed it by running `modprobe ip_tables`

**Comment by raphael421** [comment]
> i fixed it by running `modprobe ip_tables`

Oh, yeah, I had blocked `ip_tables` in modprobe some time ago due to `nftables` issues. After deleting `/etc/modprobe.d/noiptables.conf` the container turns on normally. Sorry for creating this issue, since the problem was on my part. I just wonder: Would it be possible to optionally implement `nftables` instead of `iptables`? While trying to fix this issue I've tried to change PostUp and PostDown in container's envs, but even after deleting wg0.conf and wg0.json, it still tried to modprobe `iptables`.

**Comment by raphael421** [comment]
Okay, I'll close this issue as that probably was also my misconfiguration.

**Comment by raphael421** [comment]
Alright, after modprobe'ing ip_tables, things have turned out badly... With your usual settings, I can't even connect to neither panel nor DNS, while container runs without any errors in logs. After setting `network_mode` to `host`, `privileged` to `true` and getting rid of sysctl settings I can access panel and connect to the DNS itself, but I get this from wireguard on kernel:
```
wireguard: wg0: Packet has unallowed src IP (fe80::b814:51c4:7451:766b) from peer 3 (x.x.x.x:x)
wireguard: wg0: Packet has unallowed src IP (10.114.190.244) from peer 3 (x.x.x.x:x)
```

**Comment by raphael421** [comment]
Changing PostUp and PostDown to `nft` gives me `/usr/bin/wg-quick: line 295: nft: command not found`

**Comment by raphael421** [comment]
It seems that docker tries to masquerade ports in the NAT when `network_mode` is not set to `host`, which causes issues with `inet filter`'s `input` chain. Without this masquerade I can access all ports, because they're accepted(panel's port accepts connections only from local addresses) in `input` chain, however I have to run it with `network_mode: host` so that docker won't try to create this mess, but then it messes up the forwarding that wg-quick tries to set up. The only workaround at the moment is to use `iptables` firewall instead of `nftables`, but even then docker will discard my firewall without `network_mode: host`. Is there any other option out there?

**Comment by raphael421** [comment]
> Alright, after modprobe'ing ip_tables, things have turned out badly... With your usual settings, I can't even connect to neither panel nor DNS, while container runs without any errors in logs. After setting `network_mode` to `host`, `privileged` to `true` and getting rid of sysctl settings I can access panel and connect to the DNS itself, but I get this from wireguard on kernel:
> 
> ```
> wireguard: wg0: Packet has unallowed src IP (fe80::b814:51c4:7451:766b) from peer 3 (x.x.x.x:x)
> wireguard: wg0: Packet has unallowed src IP (10.114.190.244) from peer 3 (x.x.x.x:x)
> ```

Okay, so solution to that was simply adding rules to the forward chain to accept those from wireguard(I had them set to `policy drop;`, which in turn was dropping every packet forwarded by wg0) and disabling `iptables` for docker in `daemon.json`.
