### ISSUE TITLE
[Feat]: reset client usage

### ISSUE THREAD

**Issue by m0x61h0x64i** [wg-easy/wg-easy#1339]
### Description

please add a functionality to be able to reset client usage

### Suggested Solution

just a button in ui to reset usage client

**Comment by tetuaoro** [comment]
Hi,

What do you mean by *reset usage* ?

**Comment by m0x61h0x64i** [comment]
> What do you mean by _reset usage_ ?

I mean reset the data traffic used by user
like if this 
![image](https://github.com/user-attachments/assets/415c1edc-6453-42e0-881e-94e1057d414f)
becomes
![image](https://github.com/user-attachments/assets/f2b650ab-7276-43c1-9154-5e00f349d845)

**Comment by kaaax0815** [comment]
By restarting the container the usages are reset. As this is not saved in any way (which is planned at a later stage)
