### ISSUE TITLE
[Bug]: MTU Settings only Apply on Client Configs not on Host Configs

### ISSUE THREAD

**Issue by Usucra** [wg-easy/wg-easy#1351]
### Describe the bug

After issues with being able to SSH into my Maschines at Home I realized that it was Connected to the MTU Value of the Wireguard Interface on the Device and saw that the WG_MTU Variable is never used on the main Interface and only on the generated Profiles from the Web Interface

### Expected behavior

WG_MTU Value defines the MTU of Both the Clients and the Server

**Comment by kaaax0815** [comment]
Good catch. We should introduce 2 Mtu values for Server and Client. As some people like to optimize the Mtu and often the server has a higher one. (noted here https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297)
Does Wireguard set the Mtu of the interface correctly or is it more work than adding it to the config?

**Comment by kaaax0815** [comment]
Implemented here #1356. Will take a while until its in `nightly` or even `latest`
