### ISSUE TITLE
[Bug]: Running wgpw (wg-password) without password doesn't work

### ISSUE THREAD

**Issue by f73** [wg-easy/wg-easy#1357]
### Describe the bug

When running `docker run ghcr.io/wg-easy/wg-easy wgpw` without password there isn't any prompt for user to provide password, container just exit.

### Expected behavior

Per [wg-password](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md) when running `docker run ghcr.io/wg-easy/wg-easy wgpw` without provided password, a prompt to enter password should appear.

### Relevant log output

```shell
There isn't any logs using docker logs -t "containe_name"
```

**Comment by pheiduck** [comment]
Try: docker run `ghcr.io/wg-easy/wg-easy:nightly` wgpw

**Comment by f73** [comment]
I offer prompt "Enter your password: %", but exit immediately.

Log ouput:
`2024-09-05T13:27:06.925049454Z Enter your password: %`

**Comment by pheiduck** [comment]
@mcmacker4 please fix this bug.
Thx!

**Comment by mcmacker4** [comment]
@f73 can you try running with `-it` flags?
```
docker run -it ghcr.io/wg-easy/wg-easy:nightly wgpw
```

**Comment by f73** [comment]
@mcmacker4 I can confirm that `wg-easy:nightly` using `docker run -it ghcr.io/wg-easy/wg-easy:nightly wgpw` works as intended.

**Comment by pheiduck** [comment]
Documentation has been fixed now.: https://github.com/wg-easy/wg-easy/commit/f4b3d4fb6b1080948ab74f675877e2b020423de2

**Comment by mcmacker4** [comment]
Ah great. Thank you @pheiduck
