### ISSUE TITLE
[Bug]: Prometheus metrics support does not work

### ISSUE THREAD

**Issue by rallep71** [wg-easy/wg-easy#1373]
### Describe the bug

Prometheus metrics support does not work

### Relevant log output

```shell
http://10.0.70.50:51825/metrics

{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics",
  "stack": []
}

http://10.0.70.50:51825/metrics/json
{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics/json",
  "stack": []
}

docker setup

  docker run -d \
  --name=wg-easy \
  -e LANG=de \
  -e WG_HOST=xxxxxxx(my_ip) \
  -e PASSWORD_HASH='$2a$12$12NDEq6HekrZjluK8Ibe..iqIl3WQzSkkW7HdHloyaAPw4Og7/KqW' \
  -e PORT=51825 \
  -e WG_PORT=51824 \
  -e WG_DEFAULT_DNS=10.0.70.1 \
  -e ENABLE_PROMETHEUS_METRICS=true \
  -e UI_ENABLE_SORT_CLIENTS=true \
  -e UI_CHART_TYPE=3 \
  -e UI_TRAFFIC_STATS=true \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51824:51824/udp \
  -p 51825:51825/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy
```

**Comment by rallep71** [comment]
Ok, i read this https://github.com/wg-easy/wg-easy/issues/1334.

But wrote this please in youre offical Documentation that this can used in moment wg-easy nightly only !!!

I testet and testet and so on for long time... :(

**Comment by kaaax0815** [comment]
> Ok, i read this https://github.com/wg-easy/wg-easy/issues/1334.
> 
> But wrote this please in youre offical Documentation that this can used in moment wg-easy nightly only !!!
> 
> I testet and testet and so on for long time... :(

Please just read the README. It's there for a reason.

> For stable versions instead of nightly or development please read README from the production branch!

**Comment by florian-asche** [comment]
I little note on the specific feature, that this is only in nighly would be great.

**Comment by kaaax0815** [comment]
Just read the README. It's clearly stated that the `:latest` Tag is built against the `production` branch. Then you can read the readme in that branch and see that the feature doesn't exist there.

**Comment by tokKurumi** [comment]
> Just read the README. It's clearly stated that the `:latest` Tag is built against the `production` branch. Then you can read the readme in that branch and see that the feature doesn't exist there.

I see a lot of people have same question. Why do theirs metrics do not work. I think it's better to mention this behavior directly in features in README. Now, a lot of people are getting confused.

**Comment by vladyslav2** [comment]
@kaaax0815 can you describe your logic for removing prometheus metrics for the production build?
to be honest this was my main point to use your solution (and i'm really grateful for you doing it) - to have grafana dashboard with wireguard stats

**Comment by kaaax0815** [comment]
@vladyslav2 it's not removed. It's just not released.
