### ISSUE TITLE
[Feat]: hope wg-easy can add a colum to set interface: ex: eth2

### ISSUE THREAD

**Issue by minimoonleaf** [wg-easy/wg-easy#1376]
### Description

hope wg-easy can add a colum to set interface: ex: eth2

My environment is synology use Container manager add Compose.yaml to create wireguard services,
==========
version: "3.8"
services:
  wg-easy:
    environment:
      # Required:
      # Change this to your host's public address
      - LANG=cht
      - WG_HOST=???
      - UI_TRAFFIC_STATS=true
      # Optional:
      - PASSWORD_HASH=$$$
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=8.8.8.8
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
==========

The wg0.conf settings always has be auto build like :
==========
PostUp =  iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; 
==========
but I want to set wireguard use eth2 to connect, when write the wg0.conf file
==========
PostUp =  iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth2 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg2 -j ACCEPT; iptables -A FORWARD -o wg2 -j ACCEPT; 
==========
when I restart the Container manager service the wg0.conf file always recovery to default eth0 setting
==========
PostUp =  iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; 

### Suggested Solution

Add a colum to set network interface

**Comment by kaaax0815** [comment]
Thats what `WG_DEVICE ` is for

**Comment by pheiduck** [comment]
please add: `WG_DEVICE=eth2`

**Comment by minimoonleaf** [comment]
I have add 
-WG_DEVICE=eth2

The VPN seens no work

when I ssh connect
> sudo docker exec -it wg-easy bash
84410ef8????:/app#
84410ef8????:/app#ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
3: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.8.0.1/24 scope global wg0
       valid_lft forever preferred_lft forever
97: eth0@if98: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.2/16 brd 172.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever

The docker container wg-easy even only eth0 no see the eth2

**Comment by gaby** [comment]
@minimoonleaf Is `eth2` in your host (outside Docker) ?
 If so you have to use `network_mode: host` when running with compose
