### ISSUE TITLE
[Feat]: Show wg-easy version on web page

### ISSUE THREAD

**Issue by Mart-555** [wg-easy/wg-easy#1388]
### Description

I'm very new to using wg-easy, so maybe I may have missed it, but is there a way of showing what version of wg-easy is running. if not would it be possible to add this to the web page ?

### Suggested Solution

Add some text to show the software version at the bottom of the web page

**Comment by moppman** [comment]
The wg-easy API exposes this information. AFAICT this is currently only used for update checks to display an upgrade notification.

`currentRelease` in `app.js` holds the release version. So I guess `{currentRelease}` could easily be displayed in  `index.html`'s footer.

Until this is implemented you can also check manually with your browser under `https://<your_domain>/api/release`
