### ISSUE TITLE
[Bug]: WG-Easy GUI Keep Showing Connections Stats even if the client is disconnected

### ISSUE THREAD

**Issue by mofakhar** [wg-easy/wg-easy#1400]
### Describe the bug

When you disconnect your VPN, the reported stats in the WG-easy GUI should zeros and the indicator that there's on-going connection should stop blinking but we do see the contrary.

### Expected behavior

When you disconnect, the GUI should see no traffic coming anymore and stop blinking the client and zeros the stats
![image](https://github.com/user-attachments/assets/c8d96de3-038b-454d-aea3-bfab47b033ac)

**Comment by kaaax0815** [comment]
This is how WireGuard works. Nothing wg-easy can do about. The client is marked as offline if the latest handshake is older then 15 minutes
