### ISSUE TITLE
[Feat]: adding custom comment to downloaded files

### ISSUE THREAD

**Issue by francescor** [wg-easy/wg-easy#1415]
### Description

add custom comments in peers' configuration files

### Suggested Solution

I would like to have the possibility to add a multiline comment in all downloaded configurations (even the one with the QR)

My idea is to add there some instructions for my users... 

### Alternatives

maybe there is already another way to achieve this?

**Comment by kaaax0815** [comment]
Do you mean literal comments `# example`?
There is no such support and probably never will be.
If you want to add some instructions then do it in a proper manner.
Scanning the QR Code with the WireGuard App would never reveal comments therefore doesn't add any benefit

**Comment by francescor** [comment]
> Do you mean literal comments # example?

yes

> Giving the User a Page a good Documentation or FAQ 

ok

**Comment by francescor** [comment]
should I close this myself?
