### ISSUE TITLE
Can't access. Error - Unauthorized 

### ISSUE THREAD

**Issue by kara707** [wg-easy/wg-easy#1417]
### Describe the bug

Updated to the latest version, when entering the password it shows "Unauthorized" and does not let me into the interface.

### Expected behavior

Help please, i lost access to my wg wpn((

**Comment by kaaax0815** [comment]
Please post docker run command / docker compose file and server logs

**Comment by kara707** [comment]
I reread the "readme", now you need to enter not the password in its pure form, but the hash. I have already fixed everything and got access to the interface, thank you!
