### ISSUE TITLE
[Bug]: Prometheus /metrics access

### ISSUE THREAD

**Issue by jkawka** [wg-easy/wg-easy#1418]
### Describe the bug

Unfortunately but access to Prometheus doesn't work:
```
{
"statusCode": 404,
"statusMessage": "Cannot find static asset /metrics",
"stack": []
}
```

option is enabled ENABLE_PROMETHEUS_METRICS=true and password also set

### Expected behavior

display metrics at /metrics url

**Comment by kaaax0815** [comment]
duplicate of #1373
