### ISSUE TITLE
[Bug]: Generated config file name contains spaces

### ISSUE THREAD

**Issue by realhackcraft** [wg-easy/wg-easy#1424]
### Describe the bug

The generated config file name contains a space, to separate the client name and "WireGuard". This makes certain guis angry (such as the Windows one, which can't parse path with space).

### Expected behavior

Remove the space from the file name, or file a bug report to wireguard-windows (I'm not sure how)

**Comment by moppman** [comment]
Could you explain what you mean in a bit more detail?

Currently, if you generate a new client, you can enter an arbitrary name. Any special characters, e.g. spaces, are matched and replaced with a hyphen via regex here: https://github.com/wg-easy/wg-easy/blob/2bd1dffe7e8ace1426a174608be44a708268bd0c/src/lib/Server.js#L239

**Comment by realhackcraft** [comment]
When you download the confit file, it appends “ WireGuard.conf” at the end, and at least the windows client will fail to load the file if it has a space in the name.

**Comment by moppman** [comment]
> When you download the confit file, it appends “ WireGuard.conf” at the end, and at least the windows client will fail to load the file if it has a space in the name.

I really don't see how this would be possible with the current code. File name normalization was added 3 years ago in #83, explicitly resolving the problem that you mentioned with the Windows WireGuard client.

Are you perhaps running a very old version of `wg-easy` ?

**Comment by realhackcraft** [comment]
No, I don’t believe that’s the case. I had updated ‘wg-easy’ a few days ago.

**Comment by moppman** [comment]
That's very strange, I'm at my wits' end then, to be honest.

- What does `https://<your-wg-easy-domain>/api/release` return?
- What `docker` command or `docker-compose` file are you running?

**Comment by kaaax0815** [comment]
Also what browser are you using? This is definitely not a problem with wg-easy

**Comment by realhackcraft** [comment]
I just realized the cause of the issue after what you said. I’m using the Arc browser, and it has a download auto-renaming feature. That must why I was getting spaces in the file names. Sorry for wasting your time 😅
On Sep 28, 2024, at 08:45, Bernd Storath ***@***.***> wrote:

﻿

Also what browser are you using? This is definitely not a problem with wg-easy
