### ISSUE TITLE
[Bug]: Wg-easy in Portainer don't get networ information

### ISSUE THREAD

**Issue by flancky** [wg-easy/wg-easy#1429]
### Describe the bug

After the last update of wg-easy (a few days ago), my container stopped working. The wg-easy container doesn't get network information (see attached picture). I tried everything—well, maybe not everything, but everything I found on the internet—and I can't fix this issue. I deleted folders, images, containers, stacks... I even used the original code to recreate it from scratch, but nothing works. The network information was working fine just before updating the wg-easy container. It's configured with Pihole, and Pihole works perfectly, but my VPN is down. Could you help me? I really need my VPN to work! Thanks a lot for your help!
![wg-easy_error](https://github.com/user-attachments/assets/fb028c81-5568-499a-9b9f-10bdff78df57)

### Expected behavior

Working like before update!!!

**Comment by kaaax0815** [comment]
did you migrate from `PASSWORD` to `PASSWORD_HASH`

**Comment by flancky** [comment]
Hi, no!! How can I do it?

**Comment by flancky** [comment]
Thanks to @kaaax0815 because he told me the solution!!! Thanks a lot!!
