### ISSUE TITLE
[Bug]: Adding anything to iptables env blocks all traffic

### ISSUE THREAD

**Issue by DevGoran** [wg-easy/wg-easy#1431]
### Describe the bug

Adding anything to let's say WG_POST_UP removes all iptables rules inside the container. No traffic possible this way.

Example
- WG_POST_UP=echo "iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE" > /etc/wireguard/post-up.txt
or 
- WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

### Expected behavior

Should be able to configure traffic to our needs.

### Relevant log output

```shell
/app # iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

**Comment by tetuaoro** [comment]
@kaaax0815 why not runn custom `iptables` defined by the admin user after our implemented rules. This will allow the admin to overwrite wg-easy rules without bugs like that.

```typescript
// run our iptables rules : PreUp, PostUp
// custom admin user rules
```

**Comment by kaaax0815** [comment]
@tetuaoro Hardcoding it would prevent special cases where e.g. users don't want to masquerade their ip. Adding custom Scripts is for more experienced users which should understand the consequences. And with #1333 its more clear what is run. As it will be shown to the user

**Comment by DevGoran** [comment]
@kaaax0815 
An idea I have, if you're going to implement something in the UI, would be to give the users 2 options:
- Insert the whole iptable rules in a text field as I would do in the wg config
- Have something like an "Allow/Deny <Field for IPs> to < <Field for IPs> on <field for ports>" list (similar to how it may look in Opnsense. I guess important would be that we could move the entries up/down to change the sequence. Not sure how difficult that would be to implement but would be a neat feature.

**Comment by kaaax0815** [comment]
@DevGoran
Have a look at https://github.com/wg-easy/wg-easy/blob/master/src%2Fconfig.js#L26

These are the rules that are run if you don't specify custom ones.
You can extend them to your liking

**Comment by DevGoran** [comment]
@kaaax0815 haven't thought of adding my rules directly to the config.js file, thanks!

**Comment by kaaax0815** [comment]
> @kaaax0815 haven't thought of adding my rules directly to the config.js file, thanks!

@DevGoran you also could do that but that wasn't my point.

You can copy them and add them before your custom rules to the env vars.

**Comment by DevGoran** [comment]
> > @kaaax0815 haven't thought of adding my rules directly to the config.js file, thanks!
> 
> @DevGoran you also could do that but that wasn't my point.
> 
> You can copy them and add them before your custom rules to the env vars.

I'm sure I actually tried that, but the iptable was empty within the container, hence the post. I will try it again later today.

**Comment by DevGoran** [comment]
```
      - WG_POST_UP=echo "iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE" > /etc/wireguard/post-up.txt
      - WG_PRE_DOWN=echo "iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE" > /etc/wireguard/pre-down.txt
```

@kaaax0815 so for example if I add even one single rule as above, the iptable seems to be empty inside the container. I've also tried to add multiple rules by separating them with a ; but nothing seems to work:
```
/app # iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

**Comment by kaaax0815** [comment]
@DevGoran this is expected as you are overwriting the default.

Look at https://github.com/wg-easy/wg-easy/issues/1394#issuecomment-2346013634

There you can see how to add custom rules.
