### ISSUE TITLE
[Bug]: I can't log to the web-panel after changing PASSWORD to PASSWORD_HASH

### ISSUE THREAD

**Issue by getsueineko** [wg-easy/wg-easy#1436]
### Describe the bug

I use the image ghcr.io/wg-easy/wg-easy:nightly and changed PASSWORD in env to PASSWORD_HASH, after that I can not log in to the web panel.
```
    environment:
      - WG_HOST=x.x.x.x    
      # - PASSWORD=sweetpassword
      - PASSWORD_HASH='$3a$14$0H2eKYM0skpHe.t8xfSdGeqUxwk4H7Z0Jiqcv2XVKwjmNgskFRBdW'
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3
 ```     

### Expected behavior

Work just fine!

### Relevant log output

```shell
Nothing crimminal

2024-09-25T14:23:31.275Z Server Listening on http://0.0.0.0:51821
2024-09-25T14:23:31.288Z WireGuard Loading configuration...
2024-09-25T14:23:31.294Z WireGuard Configuration loaded.
2024-09-25T14:23:31.295Z WireGuard Config saving...
2024-09-25T14:23:31.300Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2024-09-25T14:23:31.635Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2024-09-25T14:23:31.732Z WireGuard Config synced.
```

**Comment by wial88** [comment]
https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md

You need to add a second "$"

**Comment by moppman** [comment]
You also need to remove the single quotes from your password hash.
From [How_to_generate_an_bcrypt_hash.md](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md):
>Please note: don't wrap the generated hash password in single quotes when you use `docker-compose.yml`. Instead, replace each `$` symbol with two `$$` symbols

**Comment by getsueineko** [comment]
Thank a lot! I was not attentive enough =(
