### ISSUE TITLE
[Feat]: SSL/HTTPS

### ISSUE THREAD

**Issue by lordspace** [wg-easy/wg-easy#1437]
### Description

hey, do you have any plans to make the UI work behind https?

### Suggested Solution

maybe use another nginx container or another server to send secured requests to the backend?

**Comment by moppman** [comment]
There are some options for reverse proxies (Caddy, nginx) listed in the wiki:

https://github.com/wg-easy/wg-easy/wiki

**Comment by lordspace** [comment]
Thanks!
