### ISSUE TITLE
[Bug]: Cursor deletes comma and jumps to Pos1 when deleting the first number after the comma in a Custom Field "Currency".

### ISSUE THREAD

**Issue by MrMoep** [wg-easy/wg-easy#1438]
### Describe the bug

I tried to write an amount of money in the custom currency field and made a typo directly after the comma. (16,7 instead of 16,8). I deleted the last number and the comma is automatically erased and the cursor jumps to the beginning. So if I try to change 16,7 to 16,8 it changes to 816).

![2024-09-26 17_18_23](https://github.com/user-attachments/assets/a15bbd58-83d2-4b1a-a94b-6ae34b36e92d)
![2024-09-26 17_18_32](https://github.com/user-attachments/assets/3a3ea420-1237-4f52-8293-23a193111be5)
![2024-09-26 17_18_43](https://github.com/user-attachments/assets/546d789d-a6f8-4e81-aee2-8c6328a9a54b)

### Expected behavior

The already typed comma shouldn't be deleted and the cursor shouldn't change position.

**Comment by moppman** [comment]
I think you meant to post this in another repo 😆

**Comment by MrMoep** [comment]
Verrückt, wie kann denn sowas passieren?

Das sollte bei PaperlessNGX gepostet werden.
