### ISSUE TITLE
[Bug]: Password Hash generator broken

### ISSUE THREAD

**Issue by Nsm564** [wg-easy/wg-easy#1442]
### Describe the bug

`docker run -it ghcr.io/wg-easy/wg-easy wgpw password`
it gives different Hash for same password each time i run it its broken . 
check screenshot :   https://imgur.com/a/l4txZaC

### Expected behavior

Same hash from same password

**Comment by laperuz92** [comment]
It's not a bug, just enhanced security.

https://stackoverflow.com/questions/52121168/bcrypt-encryption-different-every-time-with-same-input#:~:text=bcrypt%20returns%20a%20different%20hash,hashes%20back%20to%20their%20passwords.

**Comment by Nsm564** [comment]
ok didnt know wsy for bothering :)
