### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ghutch1** [wg-easy/wg-easy#1443]
### Describe the bug

A bug happened!

it keeps saying unauthorized everytime I try to login on web ui

### Expected behavior

Let me login

**Comment by 7dorm** [comment]
same here, installed on server 
<img width="601" alt="Screenshot 2024-09-29 at 12 57 31 pm" src="https://github.com/user-attachments/assets/83a43c58-d10d-408c-a858-228d5719cb3a">

**Comment by moppman** [comment]
Did you see this, especially the part about how PASSWORD_HASH needs to be set in docker-compose.yml?

https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md

**Comment by Ghutch1** [comment]
![Screenshot 2024-09-29 12 29 26 PM](https://github.com/user-attachments/assets/e1a8aae0-ac9c-42c8-b320-e34f86cbb4d7)
 
 this is the problem I'm getting

**Comment by moppman** [comment]
@Ghutch1 I'm afraid screenshots aren't helpful, sorry.

"Unauthorized" just means your server does not accept your password. This is **probably** because you made a mistake when you set your $PASSWORD_HASH environment variable in your docker-compose.yml.
 
wg-easy doesn't accept a PASSWORD env variable any longer since v14. Many users struggled with this because it's a bit finicky.

Please take a good look at the "How to" document that I linked to in my previous post, especially this part:

>Please note: don't wrap the generated hash password in single quotes when you use docker-compose.yml. Instead, replace each $ symbol with two $$ symbols. For example:
>- PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG

The document also explains how to generate a password hash from your password if you haven't already.

**Comment by Ghutch1** [comment]
@moppman 
docker run --detach \
  --name wg-easy \
  --env LANG=en \
  --env WG_HOST=0.0.0.0 \
  --env PASSWORD_HASH='$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG \
  --env PORT=51821 \
  --env WG_PORT=51820 \
  --volume ~/.wg-easy:/etc/wireguard \
  --publish 51820:51820/udp \
  --publish 51821:51821/tcp \
  --cap-add NET_ADMIN \
  --cap-add SYS_MODULE \
  --sysctl 'net.ipv4.conf.all.src_valid_mark=1' \
  --sysctl 'net.ipv4.ip_forward=1' \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy

**Comment by moppman** [comment]
You're missing the closing single quote after your hash.

**Comment by Ghutch1** [comment]
@moppman 

docker run --detach \
  --name wg-easy \
  --env LANG=en \
  --env WG_HOST=0.0.0.0 \
  --env PASSWORD_HASH='$2a$12$YjSeDN5bsf0yhB3n9QoBfOsRIasju3L4X78kclEiEomce3C2gAcDi’ \
  --env PORT=51821 \
  --env WG_PORT=51820 \
  --volume ~/.wg-easy:/etc/wireguard \
  --publish 51820:51820/udp \
  --publish 51821:51821/tcp \
  --cap-add NET_ADMIN \
  --cap-add SYS_MODULE \
  --sysctl 'net.ipv4.conf.all.src_valid_mark=1' \
  --sysctl 'net.ipv4.ip_forward=1' \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy
 
I fixed it but it still dosnt work

**Comment by moppman** [comment]
You're using the wrong closing quotation mark.

**Comment by Ghutch1** [comment]
what ones than

**Comment by moppman** [comment]
'$2a$12$YjSeDN5bsf0yhB3n9QoBfOsRIasju3L4X78kclEiEomce3C2gAcDi'

**Comment by Ghutch1** [comment]
tysm

**Comment by moppman** [comment]
@Ghutch1 
Glad you got it to work!
(Just to be safe you should consider picking a new password because you posted your hash publicly here)

**Comment by Ghutch1** [comment]
alr ty

**Comment by ANDyCoMaR** [comment]
faced with the same problem, I do not understand what could be the problem?

docker run --detach \
          --name wg-easy \
            --env LANG=de \
              --env WG_HOST=0.0.0.0 \
                --env PASSWORD_HASH='$2a$ 12$RkwpC0w79sNg8Zqylfry4KHseBfUVg9R6KwM1jTStdalU.hkjozVxfV73Pa' \
                  --env PORT=51821 \
                    --env WG_PORT=51820 \
                      --volume ~/.wg-easy:/etc/wireguard \
                        --publish 51820:51820/udp \
                          --publish 51821:51821/tcp \
                            --cap-add NET_ADMIN \
                              --cap-add SYS_MODULE \
                                --sysctl 'net.ipv4.conf.all.src_valid_mark=1' \
                                  --sysctl 'net.ipv4.ip_forward=1' \
                                    --restart unless-stopped \
                                      ghcr.io/wg-easy/wg-easy

**Comment by kaaax0815** [comment]
@ANDyCoMaR the space in the password hash?

**Comment by zoyo94** [comment]
#### 我试过两台服务器一摸一样docker compose.yml
#### HASH密码一模一样
#### 启动之后我在portainer上面看PASSWORD_HASH有一部分省略了，所以一直登录鉴权有问题。
#### 我用docker run执行没问题。
