### ISSUE TITLE
[Bug]: wgpw does not wait for input

### ISSUE THREAD

**Issue by andreaskern** [wg-easy/wg-easy#1455]
### Describe the bug

wgpw does not wait for user input

### Expected behavior

wgpw waits for user input

### Relevant log output

https://github.com/wg-easy/wg-easy/blob/6f2811c6371d8b0d49b68c8f4d45520e6a6604f1/How_to_generate_an_bcrypt_hash.md?plain=1#L18

**Comment by kaaax0815** [comment]
Please post how you run `wgpw`

**Comment by lorenzpfei** [comment]
I can confirm, `docker run -it ghcr.io/wg-easy/wg-easy wgpw` does not wait for a prompt. It does nothing. With a password attached, it works like normal

**Comment by kaaax0815** [comment]
This feature is not in `latest` only in `nightly`.

**Comment by oxxxxxy** [comment]
very helpful, thank you, sweety
