### ISSUE TITLE
[Feat]: Include client remote IP address in api request api/wireguard/client

### ISSUE THREAD

**Issue by Mart-555** [wg-easy/wg-easy#1462]
### Description

Hello.

I plan to start using the api soon for reporting and logging purposes.

When I get the list of clients it doesnt show the client remote ip address.  would it be possible to add this ?

### Suggested Solution

add ip address to result of api call.

**Comment by kaaax0815** [comment]
It does that already
https://github.com/wg-easy/wg-easy/blob/6f2811c6371d8b0d49b68c8f4d45520e6a6604f1/src/lib/WireGuard.js#L192

**Comment by Mart-555** [comment]
ahh, excellent.  I see it was recently added, so I guess I'll see it in the next release.

Many thanks

**Comment by kaaax0815** [comment]
You are correct. I though it was added earlier. You could use `nightly` if you willing to take the risk 😉
