### ISSUE TITLE
[Feat]: No Docker, documentation for installation from scratch

### ISSUE THREAD

**Issue by stondelier** [wg-easy/wg-easy#1464]
### Description

No Docker, documentation for installation from scratch

### Suggested Solution

documentation for installation from scratch

**Comment by Aquathing** [comment]
Docker provides a reproducible environment and makes it easier to deploy stuff, is there do you really need a dockerless installation guide?

**Comment by Coubiac** [comment]
An installation guide without Docker would be useful for installation in a Proxmox container, for example. It would be even better to have an automated installation script, similar to pivpn :)

**Comment by kaaax0815** [comment]
Dockerless install is unsupported/deprecated as of https://github.com/wg-easy/wg-easy/pull/1377.
