### ISSUE TITLE
[Bug]: WG-EASY GUI gives access w/o login

### ISSUE THREAD

**Issue by mitrios-hub** [wg-easy/wg-easy#1473]
### Describe the bug

discovered 15oct2024
Using any other PC any who knows my WG server IP and port can log into GUI without enter password. I tried to login after restart docker and server and WG GUI opens logged in. I'm sure Docker container built with password used in run script. The same issue found in 3 servers used the same wg-easy version (last version from 10 sep).

### Expected behavior

GUI must request password while login after reboot or from new IP.

**Comment by moppman** [comment]
If you want to protect your server instance with a password, you need to set the PASSWORD_HASH environment variable.
Please read the following document very carefully; it's linked from the README and it tells you exactly what you need to do: https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md

Please pay special attention to how you need to add your password hash to the docker-compose file.

**Comment by mitrios-hub** [comment]
Well done! Thank you!
