### ISSUE TITLE
[Bug]: Kubernetes Deployment with multi replicas didn't work well

### ISSUE THREAD

**Issue by nakroy** [wg-easy/wg-easy#1476]
### Describe the bug

I want to deploy wireguard in my kubernetes cluster by using `kind: Deployment` and set `replicas` to `3` for high availability (so that Pods can be running in multi nodes) . And for the Service, I use `type: LoadBalancer` to set up an external IP for wireguard service so that I can access wireguard web-ui. 

But the problem is that when I can visit the website, and try to add a new client , it will response with an Error: `500 Internal Server Error` because the  `GET` method for `http://web-ui-ip:51821/api/wireguard/client` not work.

It seems that wg-easy images do not support running with multi replicas, and set `replicas: 1` didn't occur a problem.

Here is the Deployment yaml file I write: 
[wireguard-deployment.yaml.zip](https://github.com/user-attachments/files/17389504/wireguard-deployment.yaml.zip)

### Expected behavior

Expected wireguard service can load balance with multi replicas Pods running on multi nodes

### Relevant log output

```shell
the web-ui client response:

Request URL:
http://192.168.7.211:51821/api/wireguard/client
Request Method:
GET
Status Code:
500 Internal Server Error
Remote Address:
127.0.0.1:33210
Referrer Policy:
strict-origin-when-cross-origin
```

**Comment by kaaax0815** [comment]
I don't think this will get fixed.
I can't find any documentation on how to run bare WireGuard on Kubernetes with HA.

**Comment by nakroy** [comment]
> I don't think this will get fixed. I can't find any documentation on how to run bare WireGuard on Kubernetes with HA.

I have this situation that it might be over 50~100 colleagues would to use it to connect to the company internal network and visit the web service deployed on Kubernetes. Docker-compose works great and simple to use, but it would be more stable if it can be running with mulit replicas which can avoid unavailability when one node is down or temporally unaccessible. 

Or maybe we can use docker-compose in multi nodes and use the share file system to store volumes to keep config file synchornzing...

**Comment by kaaax0815** [comment]
If you have any information on if this would be possible just using WireGuard e.g. using `https://docs.linuxserver.io/images/docker-wireguard/` I could work on this.

I think this wouldn't even work using Docker Swarm or docker composer replicas

**Comment by nakroy** [comment]
> If you have any information on if this would be possible just using WireGuard e.g. using `https://docs.linuxserver.io/images/docker-wireguard/` I could work on this.
> 
> I think this wouldn't even work using Docker Swarm or docker composer replicas.
> 
> For companies I would recommend a more enterprise solution with e.g. zerotrust

Thanks for your reply, I would like to take a try on it.

**Comment by nakroy** [comment]
@kaaax0815 Well, actually I got another problem that if I have multi replicas, for example, three replicas running on three different nodes in my Kubernetes Cluster, every time the client visit the web UI, the clients list is different, that means the UI data is not sharing between different replicas, so I think using docker-compose replicas would also meet with this problem, so maybe use a PostGreSQL database to persistent the data is a good choice, I would try to review the codes and find a way to do it.

**Comment by kaaax0815** [comment]
I am not familiar with docker swarm or kubernetes. But we are currently using the file system to store everything. And this will not change at least for now
