### ISSUE TITLE
[Bug]:  Error de hash al actualizar wg-easy

### ISSUE THREAD

**Issue by pipounix** [wg-easy/wg-easy#1486]
### Describe the bug

He estado utilizando `wg-easy` y recientemente intenté actualizar a la última versión. Sin embargo, después de realizar los siguientes pasos:

1. Ejecuté `docker stop wg-easy`.
2. Luego, eliminé el contenedor con `docker rm wg-easy`.
3. Finalmente, utilicé `docker pull ghcr.io/wg-easy/wg-easy` para obtener la última versión.
4.  docker run -d   --name wg-easy   
-e WG_HOST=Miservidor.com   
-e PASSWORD=MiPassword 
-e WG_ALLOWED_IPS=192.168.0.0/24   
-v /etc/wireguard:/etc/wireguard   
-p 51820:51820/udp   
-p 51821:51821/tcp   
--cap-add NET_ADMIN   
--cap-add SYS_MODULE   
--sysctl "net.ipv4.conf.all.src_valid_mark=1"   
--restart unless-stopped   
ghcr.io/wg-easy/wg-easy

asi no carga ni el panel 

 docker run -d   --name wg-easy   
-e WG_HOST=Miservidor.com   
-e PASSWORD_HASH=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <-- el hash que corresponde a mi password  
-e WG_ALLOWED_IPS=192.168.0.0/24   
-v /etc/wireguard:/etc/wireguard   
-p 51820:51820/udp   
-p 51821:51821/tcp   
--cap-add NET_ADMIN   
--cap-add SYS_MODULE   
--sysctl "net.ipv4.conf.all.src_valid_mark=1"   
--restart unless-stopped   
ghcr.io/wg-easy/wg-easy
asi es cuando intento acceder a la interfaz web, recibo el siguiente error: "unauhtorized". carga el panel pero no puedo loguearme.

Estoy utilizando Docker versión Docker version 27.3.1, build ce12230 en un servidor con Debian 12.
¿Hay alguna solución conocida para este problema? Aprecio cualquier ayuda que puedan brindar.

Gracias por su trabajo en este proyecto.

### Expected behavior

Work just fine!

**Comment by moppman** [comment]
When using `docker run`, you need to wrap your password hash in single quotes.

Please read this document very carefully:
https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
