### ISSUE TITLE
[Feat]:  OTP auth rather than passwords

### ISSUE THREAD

**Issue by paulgmiller** [wg-easy/wg-easy#1493]
### Description

Passwords are pretty insecure. Using OTP would allow a lot of authenticator apps to be used instead. Specifically, im suggesting RFC 6238 OATH-TOTP 

### Suggested Solution

I use 	github.com/sec51/twofactor but could look up some javascript equivalents maybe this? https://github.com/jiangts/JS-OTP

### Alternatives

passkeys?

**Comment by kaaax0815** [comment]
Noted here https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297
Willing to review a PR for this feature after v15 released
