### ISSUE TITLE
[Feat]: bigger IP range in WG_DEFAULT_ADDRESS

### ISSUE THREAD

**Issue by ckjoris** [wg-easy/wg-easy#1494]
### Description

Not sure if this is a bug or feature request

Looks like WG_DEFAULT_ADDRESS only supports 254 IP addresses (/24 ip range).
But I would like to extend it to a /16, or atleast multiple ranges of /24.

I tried WG_DEFAULT_ADDRESS=172.16.x.x and WG_DEFAULT_ADDRESS=172.16.x.x but both options result in server errors, or the container refusing to start.

### Suggested Solution

I suggest to improve how the WG_DEFAULT_ADDRESS is handled to allow bigger IP range!

**Comment by kaaax0815** [comment]
fixed in #1347. will be released with v15
