### ISSUE TITLE
[Feat]: Allow password_hash for API requests

### ISSUE THREAD

**Issue by J7mbo** [wg-easy/wg-easy#1495]
### Description

API requests are undocumented.

Still, a bunch of us like to use wg-easy and set up things procedurally rather than manually each time.

Currently the password is sent in the body params to make a request, even if `PASSWORD_HASH` is specified.

### Suggested Solution

Allow api request body's to contain `password_hash`, or let `password` also contain a password hash and validate it server side.

**Comment by kaaax0815** [comment]
Would make wg-easy vulnerable to pass the hash attacks[^1]

[^1]: https://en.wikipedia.org/wiki/Pass_the_hash

**Comment by J7mbo** [comment]
Noice, TIL. Thanks.
