### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Zane173** [wg-easy/wg-easy#1496]
### Describe the bug

metrics is not showing up

### Expected behavior

{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics",
  "stack": []
}

### Relevant log output

{
  "statusCode": 404,
  "statusMessage": "Cannot find static asset /metrics",
  "stack": []
}

**Comment by tokKurumi** [comment]
Duplicate of #1373
