### ISSUE TITLE
[Feat]: LDAP User accounts

### ISSUE THREAD

**Issue by CtrlDelJ** [wg-easy/wg-easy#1504]
### Description

I'd love to see a LDAP integration or account system where I can give my network users a login and create/download their .conf to use on wireguard. This way it saves pushing out new ones easier and providing more manageable environment.

### Suggested Solution

Something I seen that works well but can be chaotic too is OpenVPN Access Server it gains similar functionality, but I believe this project can do similar if not better.

**Comment by kaaax0815** [comment]
Already noted here https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297.
Happy to review a PR for it
