### ISSUE TITLE
[Bug]: Unable to pull docker image

### ISSUE THREAD

**Issue by vaclove** [wg-easy/wg-easy#1505]
### Describe the bug

Hi,

I am unable to pull docker image:

```
docker pull ghcr.io/wg-easy/wg-easy
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/wg-easy/wg-easy/manifests/latest": denied: denied
```

### Expected behavior

Work just fine!

**Comment by jursed** [comment]
Likely some temporary glitch with GHCR. I can pull the image just fine (2024-11-03). Is it still reproducible?
