### ISSUE TITLE
[Feat]: option to create either a split tunnel or full tunnel client

### ISSUE THREAD

**Issue by K1WIZ** [wg-easy/wg-easy#1517]
### Description

Awesome project!   Would like the ability when creating clients to create as full or split tunnel.   If split tunnel, allow the specification of allowed IP CIDRs at client creation.   

### Suggested Solution

When creating a client, choose either full tunnel, or split tunnel.   If full tunnel, AllowedIPs: 0.0.0.0/0.     If split tunnel, allow a list of one or more CIDR subnets to be specified, so only that traffic will route over the VPN, and all other client traffic will go out the client's own ISP.

**Comment by kaaax0815** [comment]
Currently only possible to set this for all clients.

Will be implemented in v15.0.0 with #1333
