### ISSUE TITLE
[Feat]: A button to change endpoints user can access

### ISSUE THREAD

**Issue by qvipin** [wg-easy/wg-easy#1520]
### Description

When generating a config, it would be nice to be able to change the endpoints that certain users can access if I wanted to send it to people

### Suggested Solution

Maybe a button like the other 3 buttons with a textbox where you can set allowed endpoints on the local network.

### Alternatives

My alternative solution currently is just to go into the container file system and edit the wg files in there.

**Comment by kaaax0815** [comment]
Setting Allowed Ips implemented in #1333

Configuring Firewall duplicate of #1513

**Comment by qvipin** [comment]
has it already been setup to set allowed ips

**Comment by qvipin** [comment]
i see https://github.com/wg-easy/wg-easy/pull/759

**Comment by kaaax0815** [comment]
Will be implemented in 15.0.0
