### ISSUE TITLE
[Feat]: Users self service ?

### ISSUE THREAD

**Issue by rgarrigue** [wg-easy/wg-easy#1528]
### Description

Hello,

I'd like the users in my small org to have the simplest experience : reach to https://vpn.whatever.com, login using their main account, grab conf & throw it at a WG client. Because it ain't easy to manage [users * apps] accounts when peoples come & go on my end, and it's easier for them if they follow a HowTo with a handful of screenshot at their own pace.  

### Suggested Solution

I guess OIDC support, automatically creating the user & the configuration would do.

### Alternatives

I tried out Firezone. But they removed all self hosting documentation when releasing v1, I guess it'll end up closing source sooner or later. 

I also tried out Headscale. Work-ish, but Taiscale clients aren't really convenient, hiding the "use your own server instead of the official one" quite far in the settings.

**Comment by kaaax0815** [comment]
This is more or less planned with 15.0.0 and #1333. It already includes a stepping stone to multi user auth

Already noted here: https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10264297
related: https://github.com/wg-easy/wg-easy/discussions/1353, https://github.com/wg-easy/wg-easy/discussions/1307#discussioncomment-10405106

Something like support for Authentik (OAuth) or LDAP is noted but would take a lot of resources that I don't have. User support is planned tho
