### ISSUE TITLE
[Bug]: when wg-easy run 'docker run -d' or 'docker compose up -d' up the wg-easy container success, visit any website shows DNS_PROBE_FINISHED_NO_INTERNET

### ISSUE THREAD

**Issue by moontaicn** [wg-easy/wg-easy#1533]
### Describe the bug

[Bug]: when wg-easy run 'docker run -d' or 'docker compose up -d' up the wg-easy container success, visit any website shows DNS_PROBE_FINISHED_NO_INTERNET. And the UI account also shows not connect status.
  
![Image](https://github.com/user-attachments/assets/c03a152b-e200-4230-8e4f-465ca2b4a163)
![Image](https://github.com/user-attachments/assets/63881e5d-74db-4885-b1e7-0c4359c751d1)
![Image](https://github.com/user-attachments/assets/ecd14dab-671b-4f2f-ac4e-692c88a5d8c7)

my docker run is like this:
docker run -d \
  --name=wg-easy \
  -e WG_HOST=xx.xx.x.x \
  -e PASSWORD_HASH='xxx' \
  -e WG_DEFAULT_DNS=8.8.8.8,114.114.114.114,1.1.1.1 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart=unless-stopped \
  ghcr.io/wg-easy/wg-easy

### Expected behavior

Work just fine!

### Relevant log output

```shell

```

**Comment by moontaicn** [comment]
![Image](https://github.com/user-attachments/assets/387d4882-8a5d-4d57-b05f-85440ef96bf4)

When use wg-quick up start, can't visit any website,  
Executing the command `curl ifconfig.me` returns the result `curl: (6) Could not resolve host: ifconfig.me`. 
However, after executing `sudo wg-quick down mac`, I can access some websites again. When I run `curl ifconfig.me`, it also shows my original IP address.

What exactly went wrong? Please help me figure it out. Thank you very much!

**Comment by KBYSHanahira** [comment]
I encountered the same issue as you. I tested about 10 ISPs, and 7 of them could connect successfully, but 3 could not. However, all ISPs can ping my server. I’m not sure about the cause. Could it be related to the DNS server or some other issue?
