### ISSUE TITLE
[Bug]: Wiki: wrong iptables syntax for deletion

### ISSUE THREAD

**Issue by ElDavoo** [wg-easy/wg-easy#1542]
### Describe the bug

Hi,
sorry but looks like GitHub doesn't allow pull requests for wiki.
In the [Restrict-Access-to-Networks-with-iptables](https://github.com/wg-easy/wg-easy/wiki/Restrict-Access-to-Networks-with-iptables) page, the syntax for deletion is wrong. In the two code blocks, 
`iptables -I FORWARD -D wg0 ...`
should actually be
`iptables -D FORWARD -i wg0 ...`

and in the bottom notes, it is explained that the `-i `flag is replaced by `-D`, but this is wrong, `-I` should be replaced by `-D` .

Putting the wrong instructions prevents rule deletion, which does not have a noticeable effect if you don't execute a specific series of actions, so that's why it has gone unnoticed.

### Expected behavior

correct syntax

### Relevant log output

```shell
iptables v1.8.9 (nf_tables): Cannot use -D with -I
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by kaaax0815** [comment]
Thank you. I edited the page. Feel free to look over it again and report any issues
