### ISSUE TITLE
[Feat]: phantun-proxy-port

### ISSUE THREAD

**Issue by lblk** [wg-easy/wg-easy#1546]
### Description

Should we introduce Phantom in our project? Are there any plans for that? If there are no plans, would we consider accepting patches or pull requests?

### Suggested Solution

wireguard-port <=> phantun-server-port <=> internet <=> phantun-client-port <=> wireguard-client

it is just an TCP proxy app.

**Comment by kaaax0815** [comment]
Very good idea. I am looking for a while to bypass udp blocks, but as there is no Mobile App or similar I can't see the use case
