### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by GVALFER** [wg-easy/wg-easy#1551]
### Describe the bug

Hey,

This is simple to understand.
My host server has 2 IPs configured

```bash
185.xxx.xxx.15 (main)
185.xxx.xxx.3 (secondary)
```

In my docker compose i have as WG_HOST the IP  **185.xxx.xxx.3** (This is the ip that i want show in public)

```yml
services:
  wg-easy: 
      - WG_HOST=185.xx.xx.3
```

the vpn connect, and everything works very well... however, the IP that is showing in public is the **185.xxx.xxx.15**  instead of **185.xxx.xxx.3**  as defined on variable WG_HOST.

How can i fix it? 
I want my public ip show as defined on WG_HOST.

full compose:

```yml 
services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    environment:
      - LANG=en
      - WG_HOST=185.xxx.xxx.3
      - PASSWORD_HASH=$$2b$$12$$coPqCsPtcFO.Ab99xylBNOW4.Iu7OOA2/ZIboHN6/oyxca3MWo7fW
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

**Comment by kaaax0815** [comment]
I don't think its something wg-easy can do. It will just use the eth0 interface and its address
