### ISSUE TITLE
[Bug]: WG_PORT behaviour change

### ISSUE THREAD

**Issue by MatteoGalet** [wg-easy/wg-easy#1569]
### Describe the bug

When creating a new container with mapping on different internal vs. external ports (with -p option), I used to specify WG_PORT=external_port
Now I just rebuilt the container after pulling an updated image, and the container would not listen to that port on the host.
I had to put WG_PORT=internal_port to make it work.
Side effect, now the exported conf files for each client are pointing to domain:internal_port instead of the correct domain:external_port
When did this change happen in code? The old behaviour would be better IMHO.

### Expected behavior

WG_PORT pointing to external_port

### Relevant log output

```shell

```

**Comment by kaaax0815** [comment]
As the change to the old behavior would be a breaking change this will not be done.

Just use the same port on the mapping from internal to external

**Comment by whispy** [comment]
@kaaax0815 To clarify, are you saying that wg-easy does not support setting any given external port on the container, and that users _must_ use 51820 and 51821? This seems like a minor security risk to have all wg-easy users standardized on the same port for Wireguard.

**Comment by kaaax0815** [comment]
@whispy No. With `WG_PORT` the port can be changed. But as clients use that port to connect and the server to listen. The mapping in the docker compose file or run command should be the same for both external and internal in most cases

**Comment by whispy** [comment]
@kaaax0815 thanks! I am little confused then. I tried the following (setting the external port to `6001` and internal port to `51821` and was unable to access the web UI:
```
docker run --detach \
...
  --env PORT=6001 \
  --env WG_PORT=51820 \
  --volume ~/.wg-easy:/etc/wireguard \
  --publish 51820:51820/udp \
  --publish 6001:51821/tcp \
...
```

What am I doing wrong here?

**Comment by MatteoGalet** [comment]
What kaaax0815 is saying (and I am NOT agreeing with this modus operandi) is that if you need it to be listening on port 6001 outside (host machine port), you MUST make it run on port 6001 internally (in the container).

Like this:
`docker run --detach \
...
  --env PORT=6001 \
  --env WG_PORT=51820 \
  --volume ~/.wg-easy:/etc/wireguard \
  --publish 51820:51820/udp \
  --publish 6001:6001/tcp \
...`

**Comment by whispy** [comment]
Ah, that makes sense. Thanks, @MatteoGalet!
