### ISSUE TITLE
Update Wireguard version :  1.0.20200102 -> 1.0.20210914

### ISSUE THREAD

**Issue by comassky** [wg-easy/wg-easy#206]
Hello,

The version deployed by wg-easy latest is considered obsolete: 1.0.20200102, it is 2 years old).

Is it possible to upgrade to a more recent version?

https://git.zx2c4.com/wireguard-tools/refs/tags

Last version is : 1.0.20210914

I think upgrade alpine version could resolve this issue.

Regards

**Comment by comassky** [comment]
Update to  docker.io/library/node:17-alpine is ok

![image](https://user-images.githubusercontent.com/48486646/154543008-c22904c9-5d47-4e2e-947c-ec8294fa7244.png)

**Comment by whatdemocracy** [comment]
@comassky Hi friend...Could you explain me how to apply the updated file to the wg-easy container?

**Comment by comassky** [comment]
> @comassky Hi friend...Could you explain me how to apply the updated file to the wg-easy container?

Hi, just update the image inside the Dockerfile (node:alpine-latest

https://github.com/WeeJeWel/wg-easy/pull/209/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

And build the image on your host
