### ISSUE TITLE
Making use of GitHub Releases

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [wg-easy/wg-easy#207]
I don't know when an update to WireGuard Easy is available because there are no new versions announced in the Releases area on GitHub. Taking advantage of this lets us get notifications of new releases from GitHub and over RSS. Thank you.

**Comment by shizunge** [comment]
Could you also please push the image to ghcr.io registry?

**Comment by marvin8** [comment]
If you implement releases could you also please tag docker images with the release/version please.

**Comment by chris-sanders** [comment]
Just wanted to echo pushing to ghcr.io due to API limits on docker.

**Comment by peterlewis** [comment]
Closing as complete.

**Comment by coldshouldermedia** [comment]
@peterlewis  I see that this issue is closed as complete, but I don't understand what path I can take to get rss notifications of new major releases.  Would you be able to clarify how to do this for me?
