### ISSUE TITLE
IP whitelist for web server

### ISSUE THREAD

**Issue by Dubzer** [wg-easy/wg-easy#275]
It would be nice to have an IP whitelist environment variable for the node backend

**Comment by MuratovAS** [comment]
I solved this problem by `nginx proxy manager`. You can read in more detail [here](https://github.com/wejewel/wg-exy/wiki/using-wireguard-exy-with-ssl).
I redirect `Web Server` to https, implement authorization and whitelist through `Access List`

P.S. Clients should also block the Nginx bypass, by means `iptables -A INPUT -i wg0 -p tcp --dport 51821 -j DROP`.
