### ISSUE TITLE
Unable to login in when webui is forwarded by SSH

### ISSUE THREAD

**Issue by sky96111** [wg-easy/wg-easy#326]
In some network condition, unsafe HTTP request will be blocked, so I use `ssh -L 51821:127.0.0.1:51821 root@example.com` to forward 51821 to local.
But after I type in password, web does not login in and shows:  
`NetworkError when attempting to fetch resource.`

In SSH we can find sum of `channel 3: open failed: connect failed: Connection refused`
![](https://s3.bmp.ovh/imgs/2022/07/25/413ac6ae3f236e8e.png)

**Comment by WeeJeWel** [comment]
Open your Console → Network. Which resource fails to load and why?

**Comment by sky96111** [comment]
On frefox, no error http state code. The error dialog appears along with the login POST.  
![](https://s3.bmp.ovh/imgs/2022/08/26/82fdcb2f94439eb4.png)  


On chromium, fetch resource "session" always failed.  
![](https://s3.bmp.ovh/imgs/2022/08/26/11197027814f0c17.png)

**Comment by sky96111** [comment]
![](https://s3.bmp.ovh/imgs/2022/08/26/e8f2718c2d374070.png)
