### ISSUE TITLE
wireguard-go support for VPSes without wireguard kernel module enabled.

### ISSUE THREAD

**Issue by archont94** [wg-easy/wg-easy#327]
Cheap VPSes ususally are using outdated kernels (in my case its 4.19.0) and it is not possible to use regular wireguard (as it isn't possible to load extra modules to kernel). As a workaround, it is possible to run wireguard in user namespace, i.e. [wireguard-go](https://git.zx2c4.com/wireguard-go) implementation.

There is already a [proper docker image](https://github.com/masipcat/wireguard-go-docker) which allow to run wireguard in user namespace, but it is lacking nice UI.

By combine of `wireguard-go-docker` and `wg-easy`, it is possible to create simple VPN even on cheap VPSes.

Example dockerfile:

```
FROM masipcat/wireguard-go:0.0.20220316 as wireguard-go

FROM weejewel/wg-easy:latest

# Copy wireaguard-go and wg* binaries - this will replace standard binaries, which depend on kernel module
COPY --from=wireguard-go /usr/bin/wireguard-go /usr/bin/wg* /usr/bin/
```

I tested it on 2 different VPSes and it seems to work just fine - of course performance will be worse than with native kernel support, but its fast enough saturate my 100Mb/s connection (which isn't a case for i.e. open-vpn), so it should be enough for home users which want to use VPN to their own VPS.

Is it possible, that you will add extra tag to `wg-easy` which will use wireguard-go implementation (based on example above)?

**Comment by WeeJeWel** [comment]
Would be nicest to just include it, and fallback when kernel support isn't detected. Zero-config setup for anyone! :)

**Comment by zodiacg** [comment]
I would also suggest taking a look at [boringtun](https://github.com/cloudflare/boringtun). It has smaller memory footprint.

I've successfully build an image and running an instance for my openvz7 vps ([my repo](https://github.com/zodiacg/wg-easy)). The boringtun binary I used is compiled with `cargo build --release --target=x86_64-unknown-linux-musl` from the official repo and manually put in the wg-easy building directory.

There are two things I haven't figured out to make a usable pull request. I don't have the node.js experience to merge such scenario into the normal one. And I haven't merged the building process of boringtun into the Dockerfile.

**Comment by IvanCarapovic** [comment]
Does this feature have any chance of being picked up for any future release? I am having exact the mentioned problem, of using a cheap VPS that doesn't support WG. I am using https://github.com/irctrakz/docker-wireguard-tiny which works, but it lacks any, yet alone beautiful UI.
