### ISSUE TITLE
Option to disable DNS

### ISSUE THREAD

**Issue by DerSeb90** [wg-easy/wg-easy#359]
Hello,
because i use Wireguard Primary for RoadWarrior access to Private Networks it would be awesome to have an option to disable/delete the DNS Setting in the downloaded config files or QR Codes. My actual workaround is the to pass null to the DNS env variable.

**Comment by DoTheEvo** [comment]
I know too little to really have some better say... but DNS straight up stopped working once the tunnel was up on my arch linux machine. Even when the env_variable was set to generic 1.1.1.1 or fully recreated containers with 8.8.8.8 and resolvectl showed what seem correct stuff.
Seemed that it worked fine with windows though.

IMO there should be no DNS tinkering by wireguard if the DNS is not spelled out in the setting. That means the default should be empty instead of 1.1.1.1

but if people dont really complain on this.. I guess maybe I and few other edge cases just have not ideally configured DNS.

**Comment by r0bj** [comment]
Issue is still valid.

**Comment by peterlewis** [comment]
> I know too little to really have some better say... but DNS straight up stopped working once the tunnel was up on my arch linux machine. Even when the env_variable was set to generic 1.1.1.1 or fully recreated containers with 8.8.8.8 and resolvectl showed what seem correct stuff. Seemed that it worked fine with windows though.
> 
> IMO there should be no DNS tinkering by wireguard if the DNS is not spelled out in the setting. That means the default should be empty instead of 1.1.1.1
> 
> but if people dont really complain on this.. I guess maybe I and few other edge cases just have not ideally configured DNS.

I understand and appreciate the sentiment here. If we were to not set a default, going forwards, then many instances of wg-easy would experience an undesirable breaking change.

Can you please propose what you feel would be appropriate logic for disablement of DNS for those edge cases where no DNS servers is desired, given that for the majority DNS is not only desired, but required.

Whilst any implementation would—of course—also be subject to the approval of @WeeJeWel and @pheiduck (I have no "skin in the game", I already set my DNS as to my requirements, I would suggest that a potential route would be to allow for a `$WG_NO_DNS` variable to be set to `true`, as opposed to removing DNS when `$WG_DEFAULT_DNS` is unset.

**Comment by r0bj** [comment]
My use case is that I use VPN to route only specific networks (not 0.0.0.0/0) and I use default DNS on the client host so I don't want to send DNS requests over VPN.
> I understand and appreciate the sentiment here. If we were to not set a default, going forwards, then many instances of wg-easy would experience an undesirable breaking change.

> Can you please propose what you feel would be appropriate logic for disablement of DNS for those edge cases where no DNS servers is desired, given that for the majority DNS is not only desired, but required.

There is no need to alter the default settings. An option akin to 'WG_DNS_DISABLED' would be sufficient. This would prevent the DNS settings from being configured in the WireGuard configuration.

**Comment by sprt** [comment]
I'm evaluating wg-easy for my setup and this is relevant to me as my router doesn't support NAT loopback, so I want to just inherit the system DNS (maps my domain to my private IP in my network, public one otherwise). Wouldn't passing `WG_DEFAULT_DNS=` be sufficient or am I missing something?

**Comment by peterlewis** [comment]
Many will likely leave `$WG_DEFAULT_DNS` blank. This means that if we make the change to respect the null of this field then loads of setups would break.

**Comment by sprt** [comment]
Apologies if I'm missing something obvious but looking at the code, it seems passing `WG_DEFAULT_DNS=` is functionally different from not passing that env var at at all (the former indeed leaves it blank in the config per my testing). So it looks like the current approach is fine if users are educated to use `WG_DEFAULT_DNS=` to not specify a default at all, and to not do anything to retain the current 1.1.1.1 default.

**Comment by peterlewis** [comment]
> Apologies if I'm missing something obvious but looking at the code, it seems passing `WG_DEFAULT_DNS=` is functionally different from not passing that env var at at all (the former indeed leaves it blank in the config per my testing). So it looks like the current approach is fine if users are educated to use `WG_DEFAULT_DNS=` to not specify a default at all, and to not do anything to retain the current 1.1.1.1 default.

Oh that is interesting! Thank you, I was not aware of that functionality! @r0bj can you please test setting `WG_DEFAULT_DNS` to a null value and report back?

Thanks!

**Comment by peterlewis** [comment]
> Hello, because i use Wireguard Primary for RoadWarrior access to Private Networks it would be awesome to have an option to disable/delete the DNS Setting in the downloaded config files or QR Codes. My actual workaround is the to pass null to the DNS env variable.

Doh, sorry, I note that this exact method of application is mentioned in the original comment! Do we really need *another* variable if simply setting this to blank works as intended? It feels like maybe just a cheeky documentation tweak is in order.

**Comment by r0bj** [comment]
> Oh that is interesting! Thank you, I was not aware of that functionality! @r0bj can you please test setting WG_DEFAULT_DNS to a null value and report back?
I was using workaround with `WG_DEFAULT_DNS=null` before but `WG_DEFAULT_DNS=` is even better because it's not setting `DNS` parameter in WireGuard at all. Thanks for that.
