### ISSUE TITLE
after connecting to vpn domains on the host become unreachable 

### ISSUE THREAD

**Issue by crzp** [wg-easy/wg-easy#360]
Hello,
i have the following problem:

I have Proxmox running with multiple VMs. The host has one public IP. My internal network is 10.0.0.0/24
There is one machine with NGINX reverse proxy to provide webaccess for all my services and VMs if needed.
This is done by iptable rules to forward all traffic on the public ip for port 80/443 to the reverse proxy.

Then i installed wg-easy on my docker machine, forwarded the UDP port using iptable rules.
I gave it the internal network 10.10.0.0/24 and left the rest per default settings.

After that i got an SSL cert for vpn.mydomain.tld and forwarded the TCP port to the docker machine via proxy, so i can access the webui on port 443 per domain.

So far, everything works fine. 
I create a user, import the profile, and connect to the vpn. 

After that, all my domains which are routed through the reverse proxy become unreachable.
Everything else works.

I guess there are routing problems with my internal/docker networks?
Not sure where to start. 
Maybe you are able to help me/point me in the right direction?

Best regards
Chris

**Comment by AdvancedAssistiveTech** [comment]
Same issue on my machine. Any news/info/progress on this?

**Comment by cleversonahum** [comment]
In case it helps, I fixed my setup by changing the iptables rules. I had to add a rule in the INPUT chain to accept packets from the `docker_gwbridge` interface in my cluster. Therefore, it wasn't a problem with wg-easy.
