### ISSUE TITLE
Nothing gets routed when disabling masquerade

### ISSUE THREAD

**Issue by moritzbeck13** [wg-easy/wg-easy#361]
**Describe the bug**
I cannot access anything when I try to disable the masquerading. Otherwise, it works fine.

**To Reproduce**
1. Set the environment variable `WG_POST_UP` to `iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;` (Basically the default just without the masquerading rule.)
2. Restart the container.
3. Connect from a cellular network.

**Expected behavior**
Instead of the IP address of the docker container the assigned device IP can be seen, e.g. in access logs.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21 FE 5G
 - OS: Android 12 OneUI 4.1

**Additional context**
I have a network of 10.0.0.0/16.
My default gateway is 10.0.0.1.
I run Pi-hole as my sole DHCP and DNS server in a Docker container on 10.0.10.10.
I've tried setting up static routes for different network and gateways, with no success so far.

10.0.0.0-10.0.8.255 are for static or reserved IPs.
10.0.8.0/24 is used for Wireguard.
10.0.9.0/24 is used for DHCP.
10.0.10.0/24 is used for all my Docker containers, which are on a macvlan network.

Wireguard DNS is set to 10.0.10.10, allowed IPs to 10.0.0.0/16
Usually I can see that my Wireguard DNS request are coming from 10.0.10.60, which is the container IP.
After changing a bunch of stuff I did somehow manage to see a successful request from the 10.0.8.0/24 subnet in there, but nothing ever gets routed or resolved, besides obviously the gateway and Wireguard server IP.
10.0.8.1, the Wireguard internal server IP, is pingable from the network, connected devices are not. Therefore I think there is an issue with the return routing, in my network or with Docker.

**Comment by dParikesit** [comment]
I encountered the exact same problem. 

The solution is to change masquerade line in PostUp into
```
iptables -t nat -A POSTROUTING ! -d ${module.exports.DOCKER_SUBNET} -o ${module.exports.WG_DEVICE} -j MASQUERADE;
```
other PostUp stays the same. Note that you have to put your docker network subnet as your env.

You also need to add NET_ADMIN to your pi hole compose config (it's also in your wg-easy compose config). Then run this command to add the ip route
```
docker exec adguard ip route add <DOCKER_SUBNET> via <wg-easy ip>
# for example, docker exec adguard ip route add 10.2.1.0/24 via 10.1.0.3
```
