### ISSUE TITLE
 WireGuard exited with the error: Cannot find device "wg0"

### ISSUE THREAD

**Issue by wmlunge** [wg-easy/wg-easy#364]
docker can't work.
logs:
2022-08-31T08:28:13.550Z Server Listening on http://0.0.0.0:51821
2022-08-31T08:28:13.551Z WireGuard Loading configuration...
2022-08-31T08:28:13.552Z WireGuard Configuration loaded.
2022-08-31T08:28:13.553Z WireGuard Config saving...
2022-08-31T08:28:13.554Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9

docker run -d --name=wg-easy -e WG_HOST=XXX.XXX.XX.XX -e PASSWORD=XXXXXXXXXXX -e WG_DEFAULT_ADDRESS=10.10.10.254 -e WG_DEFAULT_DNS=8.8.8.8 -e WG_ALLOWED_IPS=10.10.10.0/24 -e WG_PERSISTENT_KEEPALIVE=25 -v /data/appData/wireguard:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart unless-stopped weejewel/wg-easy

**Comment by eandersons** [comment]
There are bunch of issues that this one is duplicating or is similar to: <https://github.com/WeeJeWel/wg-easy/issues?q=is%3Aissue+Cannot+find+device+%22wg0%22>.
For example, see #293 for answer.

**Comment by pmodlin** [comment]
This helped me: yum install iptables-services
