### ISSUE TITLE
VPN port don't open

### ISSUE THREAD

**Issue by damnkrat** [wg-easy/wg-easy#369]
**Describe the bug**
Can't connect to WireGuard due to port not open

**To Reproduce**
Steps to reproduce the behavior either on docker or tipi:
1. Install WireGuard
2. Add client in GUI
3. Try to connect or scan for WireGuard ports
4. No internet

**Expected behavior**
Use WireGuard VPN with internet

**Desktop:**
 - OS: Debian 11
 - Browser Firefox
 - Version 103.0.2

**Smartphone:**
 - Device: Samsung Galaxy S20+
 - OS: Android 12
 - Browser Samsung internet
 - Version 18.0.0.58

**Comment by eandersons** [comment]
If port is not open, then you should open it in server's firewall.
If the necessary ports are already open, then it probably is DNS related issue.

Did the client connect to WireGuard successfully or it could not connect at all?

How exactly did you create the WireGuard Easy container (a full `docker run` command or content of `docker-compose.yml` would be useful)?

**Comment by dannkunt** [comment]
My docker command:
```bash
sudo docker run -d \
  --name=wg-easy \  
  -e WG_HOST=redacted \
  -e PASSWORD="strongpass" \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 8082:8082/tcp \   
  --cap-add=NET_ADMIN \                  
  --cap-add=SYS_MODULE \                     
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \             
  --restart unless-stopped \                 
  weejewel/wg-easy 
```

runtipi config:
![изображение](https://user-images.githubusercontent.com/32395839/188266343-9d7c9cbe-3b16-4a84-8f70-a56a55952fe9.png)

Any other ports open easy, for example web GUI of wg-easy,

**Comment by dannkunt** [comment]
I checked that Tailscale works perfectly, but I don't like that I have to depend on other services to log in, So it's exactly not firewall problem or something like that

**Comment by eandersons** [comment]
This part is still not clear:

> Try to connect or scan for WireGuard ports

Did mobile client connect to WireGuard successfully but without access to internet or did not it make a connection at all?

**Comment by dannkunt** [comment]
No connection at all, due to port not opened

**Comment by eandersons** [comment]
If the port is not open, then, as I said before, it should be opened in firewall.

Seems that Tailscale is not using the default WireGuard UDP port: [What firewall ports should I open to use Tailscale?](https://tailscale.com/kb/1082/firewall-ports/).
You could examine the Tailscale container to see which UDP port is exposed and mapped to host to make sure if Tailscale is using the same port as WireGuard or not.
So it seems to be a firewall related problem after all.

**Comment by dannkunt** [comment]
And changing port in wg0.conf to 8102 gives no effect, On this port homarr running perfectly, on testing time I turned homarr off

**Comment by eandersons** [comment]
Homarr is using TCP port not UDP, and that is the reason why the port 8102 is not working with WireGuard Easy.
Even if the UDP port 8102 would be open, did you recreate the container with the appropriate port mapping before manually changing `ListenPort` in `/etc/wireguard/wg0.conf`?

---

> After some research, I realized that there is no default firewall on Debian.

That is not entirely true according to [Debian firewall wiki](https://wiki.debian.org/DebianFirewall):

> Prior to version 5 (Lenny), a default Debian installation did not have a default firewall enabled.
> ...
> The default Debian installation comes with the program [iptables(8)](https://manpages.debian.org/man/8/iptables), configured to allow all traffic.

Although it seems that the default firewall configuration does not have any restrictive rules.

---

> It can't be router or something like that because I am testing on a local network

I am no expert in networking, but I would advise to check router as well, as at some point you will probably need external access to your WireGuard Easy instance anyway.

**Comment by bigjimmy546** [comment]
I'm encounting the same issue on my Aliyun ECS, I open the port 51820 51821 TCP and UDP, but was not able to access wgeasy.  the same config works just fine in my home and digitalocean.  I use docker-compose.yml to run.

`version: "3.8"
services:
  wg-easy:
    environment:
      # Required:
      # Change this to your host's public address
      - WG_HOST=external ip

      # Optional:
      - PASSWORD=password
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_MTU=1420
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1`

running Ubuntu 18.04 64, UFW not enabled

**Comment by bigjimmy546** [comment]
> If port is not open, then you should open it in server's firewall. If the necessary ports are already open, then it probably is DNS related issue.
> 
How to check if it's DNS related issue?
I scan the port and it's refusing connection, I can't connect to the UI, hence can't try to connect with client.
Thanks
