### ISSUE TITLE
I don't have port 51820 available, if I change the WG_PORT to a different one, the configuration is still using 51820

### ISSUE THREAD

**Issue by K92Pi** [wg-easy/wg-easy#372]
**Describe the bug**
Hi There! I've been trying to make this work, but I can't use port 51820 because it's already occupied. I'm not sure this is the reason why the VPN connection doesn't work. Could you help me to find a solution to make this work?
**To Reproduce**
Change port 51820 for something else.

**Expected behavior**
To be able to use custom port on the server.

My config: 
DietPi v8.8.1
Device model : RPi 4 Model B (aarch64)

Wg-easy is deployed in Docker (Portainer). I have a Pi-hole DNS server running outside of Docker.

My docker file:
`version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=wg.xxxx.cc #own domain

      # Optional:
      - PASSWORD=pass
      - WG_PORT=10081 #custom port
      - WG_DEFAULT_ADDRESS=10.35.67.0
      - WG_DEFAULT_DNS=192.168.1.5 #Pi-hole address
      - WG_MTU=1280
      - WG_ALLOWED_IPS=0.0.0.0/0, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=echo "iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      - WG_POST_DOWN=echo "iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE" > /etc/wireguard/post-down.txt
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "10081:10081/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1`

Generated wg0.conf file:

```
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = xxxxx
Address = 10.35.67.0/24
ListenPort = 51820
PreUp = 
PostUp = echo "iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE" > /etc/wireguard/post-up.txt
PreDown = 
PostDown = echo "iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE" > /etc/wireguard/post-down.txt


# Client: John (9106f326-eb64-4fc0-bfaa-eab0e80d9d26)
[Peer]
PublicKey = xxxxx
PresharedKey = xxxxx
AllowedIPs = 10.35.67.0/32
```

Logs:
```
2022-09-05T15:40:16.752Z Server Listening on http://0.0.0.0:51821
2022-09-05T15:40:16.757Z WireGuard Loading configuration...
$ wg genkey
$ echo ***hidden*** | wg pubkey
2022-09-05T15:40:16.813Z WireGuard Configuration generated.
2022-09-05T15:40:16.814Z WireGuard Config saving...
2022-09-05T15:40:16.821Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2022-09-05T15:40:17.044Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2022-09-05T15:40:17.121Z WireGuard Config synced.
2022-09-05T15:44:34.538Z Server New Session: xxxx
2022-09-05T15:46:28.592Z Server Listening on http://0.0.0.0:51821
2022-09-05T15:46:28.597Z WireGuard Loading configuration...
2022-09-05T15:46:28.601Z WireGuard Configuration loaded.
2022-09-05T15:46:28.603Z WireGuard Config saving...
2022-09-05T15:46:28.609Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2022-09-05T15:46:28.847Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2022-09-05T15:46:28.923Z WireGuard Config synced.
2022-09-05T15:50:26.281Z Server New Session: xxxx
$ wg genkey
$ echo xxxxx | wg pubkey
$ wg genpsk
2022-09-05T15:50:32.753Z WireGuard Config saving...
2022-09-05T15:50:32.757Z WireGuard Config saved.
2022-09-05T15:50:32.758Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2022-09-05T15:50:32.853Z WireGuard Config synced.

```

**Comment by bernmic** [comment]
The port is hardcoded 51820 as you can see in the discussion here: [https://github.com/WeeJeWel/wg-easy/discussions/299](https://github.com/WeeJeWel/wg-easy/discussions/299)

**Comment by eandersons** [comment]
For this specific case a simple port mapping in `docker-compose.yml` should be enough:

``` yml
...
services:
  wg-easy:
    ...
    ports:
      - "10081:51820/udp"
      - "51821:51821/tcp"
    ...
```

**Comment by garret** [comment]
Ok, but then the `WG_PORT=` variable is just something broken? What is its purpose?

**Comment by eandersons** [comment]
`WG_PORT` is used in client peer configuration to point to the host's publicly available port:

```ini
[Interface]
...

[Peer]
...
Endpoint = wireguard.example.org:51234

```

Client configuration is generated in [`src/lib/WireGuard.js` (lines 199 to 211)](https://github.com/WeeJeWel/wg-easy/blob/f364e0775ab9bae81f3e5d4b5b1391db55f50296/src/lib/WireGuard.js#L199):

```js
    return `
[Interface]
PrivateKey = ${client.privateKey}
Address = ${client.address}/24
${WG_DEFAULT_DNS ? `DNS = ${WG_DEFAULT_DNS}` : ''}
${WG_MTU ? `MTU = ${WG_MTU}` : ''}
[Peer]
PublicKey = ${config.server.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${WG_ALLOWED_IPS}
PersistentKeepalive = ${WG_PERSISTENT_KEEPALIVE}
Endpoint = ${WG_HOST}:${WG_PORT}`;
```

A [simple search](https://github.com/WeeJeWel/wg-easy/search?q=WG_PORT) can help to find out where a specific string is used in the code.
