### ISSUE TITLE
Add wiki entry for setup with nginx-proxy

### ISSUE THREAD

**Issue by nickelswitte** [wg-easy/wg-easy#380]
**Describe the bug**
For my setup, I am using [nginx-proxy/nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) together with the [nginx-proxy/acme-companion](https://github.com/nginx-proxy/acme-companion) for proxy and SSL. I tried to use your guide [Using WireGuard Easy with nginx SSL](https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL) to setup your vpn behind my proxy, and finally figured out what the solution is! Maybe you can add it to the wiki :)

Here is the `docker-compose.yml`
```docker
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - wg-easy_data:/etc/wireguard
    restart: always
    environment:
      VIRTUAL_HOST: my.cool.domain.tld
      LETSENCRYPT_HOST: my.cool.domain.tld
      WG_HOST: my.cool.domain.tld
      PASSWORD: supersecurepassword
      VIRTUAL_PORT: 51821
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  wg-easy_data:

networks:
  default:
    name: nginx-proxy
```

Cheers!

**Comment by quyentruong** [comment]
You should check out [Nginx Proxy Manager](https://nginxproxymanager.com/). It's easy to setup and support SSL and auto renew SSL
