### ISSUE TITLE
[feature request]: Configuration reload

### ISSUE THREAD

**Issue by kshcherban** [wg-easy/wg-easy#390]
Hello,

I try to implement HA setup using 2 instances of wg-easy and mounted over fuse S3 configuration.
The problem I encountered is that when the first instance changes config on FS the second doesn't pick up changes.

Unfortunately I don't know JS to fix it myself.
Here're few improvements that can help with HA setup:
- add api endpoint to reload config, that can be useful to call from remote every time config changes
- reload config from disk on every operation, even list clients
- support some DB as a config storage

**Comment by loso2255** [comment]
i'm encounter same problem every time i add a new peer i need to reload the entire container
to take effect

**Comment by pvntim** [comment]
Hi! I have the exact same scenario, even including S3 storage.

Did you found a way to HA?
