### ISSUE TITLE
after adding a new device can't connet to other peer

### ISSUE THREAD

**Issue by loso2255** [wg-easy/wg-easy#391]
i encounter a problem

when i add a new per in the gui with "new" button, i need to reload the container in order
to take effect, if i don't do it the new peer can't connect to the other peer 

some one knew why?

here is the config file

[docker-compose.yml.txt](https://github.com/WeeJeWel/wg-easy/files/9756460/docker-compose.yml.txt)

**Comment by geozeke** [comment]
Are you restarting the wg-easy container or the Wireguard container? Wireguard actually requires a restart when operating in client mode and `wg0.conf` changes, so this is expected behavior. See here: [Client Mode](https://github.com/linuxserver/docker-wireguard#client-mode).

**Comment by loso2255** [comment]
i mean the wg-easy container

**Comment by loso2255** [comment]
i use wg-easy container in server mode.

if i add a peer on wg-easy UI, i need to restart wg-easy container in order to take effect

or the new client i add can't connect to wg-easy container
