### ISSUE TITLE
Q: How to change network interface to ens160?

### ISSUE THREAD

**Issue by sMohammad14** [wg-easy/wg-easy#403]
Hi
How can we change network card to ens160 or another?
I run your code and web UI work prefect, but when i want to connect WG, WG client say connected but no any traffic transfer
I think I must change network interface from eth0 (it is set by default in you code) to my network interface (mine is ens160)
Can everyone help me?
Thanks

**Comment by sMohammad14** [comment]
I modify wg0.conf but after run docker, wg0.conf was changed to eth0

**Comment by Shepherd7** [comment]
Same for me.
my network Card is bond1.
How we can edit this?

**Comment by sMohammad14** [comment]
> Same for me. my network Card is bond1. How we can edit this?
@Shepherd7 
Are you try for change your network interface name to eth0?

**Comment by Shepherd7** [comment]
> > Same for me. my network Card is bond1. How we can edit this?
> 
> @Shepherd7 
> 
> 
> 
> 
> 
> Are you try for change your network interface name to eth0?
> 
> 
> 
> 


No cant edit the Network Interface, because my maschiene is a synology 918+.
I have 2 lan Interface in the bond1.
I think i cant change the Name drin the Interface.
I must change the Interface Name in the config file from weg easy.

**Comment by joeroback** [comment]
https://github.com/WeeJeWel/wg-easy/pull/500
