### ISSUE TITLE
Multiple VPNs using wg*.conf

### ISSUE THREAD

**Issue by UmutAlihan** [wg-easy/wg-easy#406]
Hi,

Is it posible to use wg-easy with multiple VPNs on a single server via wg1.conf, wg2.conf, wgN.conf ?

**Comment by eandersons** [comment]
First of all, this question belongs more in [discussions](https://github.com/WeeJeWel/wg-easy/discussions).

Secondly, what is your use case for your requirement? That would help others to help you.

What about setting up multiple WireGuard Easy containers? Would that achieve the desired?

**Comment by UmutAlihan** [comment]
Sorry about misplacement of the question. Should I continue on discussions by creating new entry?

My use case would be to seperate different devices via wiregaurd VPNs so that I minimze the exposures of different systems to another. For example In case of a security breach on a device X, I want to be able to isolate that device X via another network aside from other devies.

I though about running multiple containers but as I could see the docker-compose file don't generate a bridge network instead uses the host network. Does this cause a clash between different containers using the same host network?

I will further investigate that method by the way. Thank you

**Comment by eandersons** [comment]
Well, [`docker-compose.yml`](/WeeJeWel/wg-easy/blob/master/docker-compose.yml) does not contain any instructions to use host's network, unless explicitly specified with [`network_mode`](https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode). Docker's [default network driver is `bridge`](https://docs.docker.com/network/#network-drivers).
