### ISSUE TITLE
error  Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by matador7495** [wg-easy/wg-easy#414]
get error 

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

i change version 3.8 to 3.3 its worked

**Comment by hadi-dindar** [comment]
change docker-compose Ver to 3.6
edit it in top of docker-compose.yml file

**Comment by eandersons** [comment]
Seems that the Docker Compose file version depends on the installed Docker Engine version: <https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix>.
