### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by ogienkoS** [wg-easy/wg-easy#418]
Hello everyone, please tell me where to find the file "docker-compose.yml"

**Comment by manythingsatonce** [comment]
Here: https://github.com/WeeJeWel/wg-easy/blob/master/docker-compose.yml

**Comment by ogienkoS** [comment]
> Here: https://github.com/WeeJeWel/wg-easy/blob/master/docker-compose.yml

where to find it directly on the server?

**Comment by megoRU** [comment]
> > Here: https://github.com/WeeJeWel/wg-easy/blob/master/docker-compose.yml
> 
> where to find it directly on the server?

upload it yourself there

**Comment by ogienkoS** [comment]
> > > Здесь: https://github.com/WeeJeWel/wg-easy/blob/master/docker-compose.yml
> > 
> > 
> > где его найти прямо на сервере?
> 
> залей туда сам

I want to change the password for accessing the web panel, I need to find it so that I can edit it, I don’t want to reinstall the container

**Comment by megoRU** [comment]
So what's the problem? nano docker-compose.yml

> > > > Здесь: https://github.com/WeeJeWel/wg-easy/blob/master/docker-compose.yml
> > > 
> > > 
> > > где его найти прямо на сервере?
> > 
> > 
> > залей туда сам
> 
> I want to change the password for accessing the web panel, I need to find it so that I can edit it, I don’t want to reinstall the container

So what's the problem? `nano docker-compose.yml`
And change the password there

**Comment by megoRU** [comment]
Могу тебе помочь по дискорду

**Comment by ogienkoS** [comment]
> Могу тебе помочь по дискорду `mego#5338`
как тебя найти там?

**Comment by megoRU** [comment]
> > Могу тебе помочь по дискорду `mego#5338`
> 
> как тебя найти там?

![image](https://user-images.githubusercontent.com/23276305/202477935-4fa92026-8502-453b-834c-c121655892af.png)
