### ISSUE TITLE
WG_PORT variable ignored 

### ISSUE THREAD

**Issue by antoniocamas** [wg-easy/wg-easy#420]
**Describe the bug**

Including the WG_PORT environment variable is to having the desired behavior. 

**To Reproduce**
Add the WG_PORT var to the docker run

**Expected behavior**
The Tunnel is listening in the inner port stated by WG_PORT

**Screenshots**
Check the content of wg0.conf file 
ListenPort is still with the default value
the same for PostUp 

I have tested in the image and tag: 
weejewel/wg-easy:7
DIGEST:sha256:79288cac4782dd9c37c2fc20d26eb663d2df9fa1d3a09b278d5c76411310ec0c

https://registry.hub.docker.com/layers/weejewel/wg-easy/7/images/sha256-79288cac4782dd9c37c2fc20d26eb663d2df9fa1d3a09b278d5c76411310ec0c?context=explore

**Other Info**
I have modified the Exposed Port, I believe my test is ok

**Comment by Laverlin** [comment]
Seems like a bug. In the config generation code the port number is hardcoded.
https://github.com/WeeJeWel/wg-easy/blob/master/src/lib/WireGuard.js
```
# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = 51820                                   // <-------------
PreUp = ${WG_PRE_UP}
PostUp = ${WG_POST_UP}
PreDown = ${WG_PRE_DOWN}
PostDown = ${WG_POST_DOWN}
```

**Comment by eandersons** [comment]
From `WG_PORT` description in [Options](/WeeJeWel/wg-easy#options):

> The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.

Value of `WG_PORT` is used in peers configuration. Interface will allways use the default WireGuard port (51820) within container. So what you described is the intended behavior.

Also, please [search for similar issues](/WeeJeWel/wg-easy/issues?q=is%3Aissue+WG_PORT) before posting your own! [A search in pull requests](/WeeJeWel/wg-easy/pulls?q=is%3Apr+WG_PORT) could give some additional insight as well.
