### ISSUE TITLE
Clients manually added to wg0.json/wg0.conf do not show up in WebUI without restart. Adding clients through webUI overwrites any manually added clients.

### ISSUE THREAD

**Issue by EspressoDS** [wg-easy/wg-easy#422]
**Describe the bug**
Currently, the WebUI cached JSON config is the sole 'source of truth' for administrating clients through the webUI. 

If a client is added manually to the wg0.json and wg0.conf files it will not show up in the UI and the UI will continue to assign 'next IP addresses' from the last IP address known to it.

In addition, when a new client is added through the web UI, the IP offered is determined from the next IP available from the cached JSON, not from the next IP available in the current system JSON if that file has changed since the node server was started.

It is sometimes useful to be able to bulk-add clients, for example when automating a roll-out. It is simple enough to add the configuration details into the .json file and generate a .conf file from that. It would be useful if the UI would maintain a sync with the state of the .conf during use rather than only loading the configuration on start.

The current internal logic results in any clients added to the .JSON and .CONF file being removed if a client is added via the webUI unless the wg-easy service is restarted after manually adding the clients.

At the least, the cached client list should be refreshed from the on-disc JSON configuration when the webUI is loaded or refreshed.

**To Reproduce**
1. Start wg-easy
2. Manually add a client to wg0.json and wg0.conf
3. Add a client via the webUI
4. See that the manually added client(s) are removed as the previously cached JSON is used to create the on-disc JSON and CONF files.

**Expected behavior**
The server should periodically refresh the client list based on the on-disc, not the cached, JSON.
When adding a new client, the IP address offered should be generated from the next available IP on the on-disc JSON, not the cached JSON.
On adding or removing a client, on-disc .JSON should be used, rather than modifying the cached JSON and then re-writing to disc.

**Additional context**
For large-scale deployments, the ability to bulk-add clients to the .JSON and .CONF is useful. Current UI behaviour means that these changes will be over-written if a new client is added via the UI without restarting wg-easy manually after the bulk add.

**Comment by EspressoDS** [comment]
I have made some minor changes to Wireguard.js that achieve the functionality that I was looking for.

They are attached below. Appologies for what I am sure us poor code. I'm OK with basic JS but not great on promises and asynchronicity.

Basically, to achieve this there are three main changes.

1. in getConfig, the promise for the configuration is renewed if mtime of wg0.json is different from the last time getConfig was called. In addition, the loop only brings up wg0 if the interface does not exist. The wg-quick up/down cycle is not longer executed. To cope with this, wg-quick down wg0 should be moved to the systemd .service file as an execStop.
2. For the functions that call saveConfig, the config array is now passed between the functions and worked on directly.
3.  saveConfig no longer gets the config file from the getConfig promise. Instead the configuration as modified by the webUI is passed directly to the function and then written.

I think the logic in getConfig might be wrong and the config file may be read every time, but 'it works for me' now. 

The end effect of this is that you can modify the .JSON file from either the webUI or some external program and the changes show up in the UI in realtime and are not overwritten by configuration changes at the UI (I think).

[WireGuard.zip](https://github.com/WeeJeWel/wg-easy/files/10084030/WireGuard.zip)

**Comment by gaby** [comment]
@EspressoDS Can you share your changes in here: https://gist.github.com 

There's no way im going to open that zip 🤣

**Comment by EspressoDS** [comment]
100% ;)

https://gist.github.com/EspressoDS/67f5be7830e74ce44a2f43ebdb69957b
