### ISSUE TITLE
Communication between peers?

### ISSUE THREAD

**Issue by SpudnikEX** [wg-easy/wg-easy#423]
Hello, is it possible to configure peer to peer communication, similar to a LAN? I am using default POSTUP and POSTDOWN configs, and enabled the Allowed IPs to be the same as the WG network (10.8.0.0/24)
Pinging from peer to peer results in Request timed out

**Comment by ad84** [comment]
If I understand your question correctly it's the allowed ips on the client config that does this...like, to get to my home subnet(10.29.29.0/24) and wire guard subnet (10.29.2.0/24) along with route all other traffic through wireguard on my phone for instance I use  - 0.0.0.0/0, 10.29.29.0/24, 10.29.2.0/24, ::/
See the Cryptokey Routing section at https://www.wireguard.com/ for more info.

**Comment by DoTheEvo** [comment]
I am also interested in this

**Comment by ItsHass** [comment]
Hi - I'm interested in this. 

I also need this to be able to start testing on port forwarding. 

I want my peer which has a server running on 8080, to be able to publish that to the 'ens3' main external server ip

Thanks
