### ISSUE TITLE
Disable PSK

### ISSUE THREAD

**Issue by zjonesz** [wg-easy/wg-easy#426]
Is there a way to disable PSK?
Trying to connect an ESP32 but the library does not work with PSK enabled.

**Comment by daniel100097** [comment]
Simple edit and mount this file:

    volumes:
      - ./wg:/etc/wireguard
      - ./WireGuard.js:/app/lib/WireGuard.js

**Comment by RastaTaz** [comment]
Same problem here: wanted to do some IOT throught wireguard to avoid loading MQTT with TLS (seems heavier that wireguard): PSK is not supported by wireguard libs for ESP32...
=> Workaround is to stop wg-easy, edit the JSON file by removing preSharedKey value (set it to ""), then restart wg-easy...
