### ISSUE TITLE
More than 255 hosts

### ISSUE THREAD

**Issue by AHidalgoP** [wg-easy/wg-easy#430]
What is the proper way to allow wireguard for managing more than 255 clients?

**Comment by mitrios-hub** [comment]
try to change IP settings in /etc/wireguard/wg*.conf

Address = 10.8.0.1/24 change to:
Address = 10.8.0.1/16

Keep in mind that here is WG-EASY web ui project FOR wureguard but not wireguard service community.

**Comment by megoRU** [comment]
> try to change IP settings in /etc/wireguard/wg*.conf
> 
> Address = 10.8.0.1/24 change to: Address = 10.8.0.1/16

Does not save after restarting and does not change anything without restarting

**Comment by megoRU** [comment]
https://github.com/WeeJeWel/wg-easy/blob/736c62b4369dc7a6502139a3cbd3a177d3f61727/src/lib/WireGuard.js#L97

**Comment by mitrios-hub** [comment]
> https://github.com/WeeJeWel/wg-easy/blob/736c62b4369dc7a6502139a3cbd3a177d3f61727/src/lib/WireGuard.js#L97

Да, я забыл что wg-easy сам настраивает конфиги, и даже в конфигах написано, что изменения будут исправлены. Надо менять код самого сервиса. У вас получилось?

**Comment by megoRU** [comment]
> Ваш вариант рабочий? Проверяли?

Я пересобирал проект у себя с этими изменениями. Но проблема вообще в другом.

https://github.com/WeeJeWel/wg-easy/blob/736c62b4369dc7a6502139a3cbd3a177d3f61727/src/lib/WireGuard.js#L233-L248

Исходя из данного кода, он только 1 цифру меняет 10.8.0.`x`/ По идеи нужно сделать какой-то другой калькулятор ip. Чтобы он перебирал все доступные а не проверял только 255

**Comment by mitrios-hub** [comment]
Да, вы правы. Интересно, автор исправит? С одной он не реагирует на сообщения, с другой - софт обновлен в августе прошлого года. Это же надо писать скрипт, который будет по маске определять диапазон ip и создавать нужный цикл for... 🙈 хотя по сути ничего сложного

**Comment by mitrios-hub** [comment]
Да, вы правы. Интересно, автор исправит? С одной он не реагирует на сообщения, с другой - софт обновлен в августе прошлого года. Это же надо писать скрипт, который будет по маске определять диапазон ip и создавать нужный цикл for... 🙈 хотя по сути ничего сложного

В общем, я провел такой эксперимент:
1. Установил wg-easy
2. Вручную настроил конфиги и js скрипты так, что wg-easy заработал на сети 192.169.0.0/16 с адресом 192.169.0.1
3. Вручную добавил 2 пира (как уже было сказано, wg-easy умеет только 4й байт адреса менять)
4. первый пир = 192.169.0.255/32
5. второй пир = 192.169.1.0/32
6. соединил эти два узла между собой по этим адресам

Значит wireguard нормально работает с CIDR/16, в чем сомневатся не было причин. Нужно переписывать скрипты wg-easy.

@AHidalgoP you have to change configs for server to run with CIDR/16, and manually change IPs to new added clients:
1. in WireGuard.js cnahge lines 97 and 202 (don't change wg0.conf):
   Address = ${config.server.address}/16

2. in config.js change line with iptables MASQUERADE (/24 to /16)

3. add new client via GUI and then change its IP to desired using CIDR/16 scope (the IP will changed in wg0.conf and wg0.json)

4. send config to client

IMHO If you want to use WG-EASY there is no another way until the author makes changes to the app

**Comment by redsawah** [comment]
Ребят, т.е. вы хотите сажать на один сервер больше 253 пользователей?

**Comment by megoRU** [comment]
> Ребят, т.е. вы хотите сажать на один сервер больше 253 пользователей?

чтобы не удалять неактивных для реселеров)

**Comment by mitrios-hub** [comment]
> Ребят, т.е. вы хотите сажать на один сервер больше 253 пользователей?

На самом деле при использовании инсты, онлифанс, тиктока и прочей ереси; хохляцких сайтов и получить microsoft тулзы для установки винды, можно и больше. у меня на сервере 1 ядро 2 гига и 60 юзеров, из которых онлайн обычно не более 30 - 40%, грузят его не более чем на 30% по памяти и проц вообще мочу, простаивает. Всё упирается в сеть, которой даже не 100мбит вполне хватает, но у меня больше. Почему бы не повесить на сервак пару тысяч, если поднять ядра и память? Это теория, рассуждаю. Плюс, соглашусь с @megoRU - у меня есть такие, кто не оплатил и они в паузе отключены. Но адреса заняты.

**Comment by nevalashka** [comment]
> > Ребят, т.е. вы хотите сажать на один сервер больше 253 пользователей?
> 
> На самом деле при использовании инсты, онлифанс, тиктока и прочей ереси; хохляцких сайтов и получить microsoft тулзы для установки винды, можно и больше. у меня на сервере 1 ядро 2 гига и 60 юзеров, из которых онлайн обычно не более 30 - 40%, грузят его не более чем на 20% по памяти и проц до 20%. Всё упирается в сеть, которой даже при 100мбит вполне хватает, но у меня больше. Почему бы не повесить на сервак пару тысяч, если поднять ядра и память? Это теория, рассуждаю. Плюс, соглашусь с @megoRU - у меня есть такие, кто не оплатил и они в паузе отключены. Но адреса заняты.

А можно ли отключать конфиги не через веб панель? Я выдаю юзерам конфиг, в названии дата - когда доступ должен пропасть. Но проблема в том, что на серваке все конфиги хранятся в wg0.conf. А баш скриптами или руками его править никак нельзя. Хочу автоматизировать этот процесс, чтобы скрипт проходися по всем строчкам, если дата наступила - то конфиг удаляется.

**Comment by mitrios-hub** [comment]
> > > Ребят, т.е. вы хотите сажать на один сервер больше 253 пользователей?
> > 
> > 
> > На самом деле при использовании инсты, онлифанс, тиктока и прочей ереси; хохляцких сайтов и получить microsoft тулзы для установки винды, можно и больше. у меня на сервере 1 ядро 2 гига и 60 юзеров, из которых онлайн обычно не более 30 - 40%, грузят его не более чем на 20% по памяти и проц до 20%. Всё упирается в сеть, которой даже при 100мбит вполне хватает, но у меня больше. Почему бы не повесить на сервак пару тысяч, если поднять ядра и память? Это теория, рассуждаю. Плюс, соглашусь с @megoRU - у меня есть такие, кто не оплатил и они в паузе отключены. Но адреса заняты.
> 
> А можно ли отключать конфиги не через веб панель? Я выдаю юзерам конфиг, в названии дата - когда доступ должен пропасть. Но проблема в том, что на серваке все конфиги хранятся в wg0.conf. А баш скриптами или руками его править никак нельзя. Хочу автоматизировать этот процесс, чтобы скрипт проходися по всем строчкам, если дата наступила - то конфиг удаляется.

Ты можешь править скрипты в /App и wg-easy будет нужные конфиги делать

**Comment by nevalashka** [comment]
А что за конкретные файлы? я залез внутрь докер контейнера, не увидел там файлы, в которых были бы конфигурации

**Comment by mitrios-hub** [comment]
> А что за конкретные файлы? я залез внутрь докер контейнера, не увидел там файлы, в которых были бы конфигурации

Ну да, вы же используете докер... Я ипользую локально приложение WG-EASY. Ищите в докере папку /App

**Comment by megoRU** [comment]
@goosegit11 конечно продаем) я даже бота создал в телеге
