### ISSUE TITLE
2 FA

### ISSUE THREAD

**Issue by Ju17091** [wg-easy/wg-easy#435]
Is any kind of 2 factor authetification planned ? TOTP or similar ? 
To add more security to the admin interface
That would be great. Thanks in advance

**Comment by nhendin** [comment]
I'm new to wg-easy, having been recommended to check it out by a colleague for my home server.  Just setting it up now, so some of this is speculative:  One could, I assume, use a reverse-proxy like traefik and a 2FA solution like authelia  or traefik-forward-auth to get https and 2FA on the web UI.
