### ISSUE TITLE
[Feature Request]  "set AllowedIPs" at creating new Clients

### ISSUE THREAD

**Issue by ronny80** [wg-easy/wg-easy#444]
Thanks for this great tool.

On my previous Wireguard-Installation withoout WG-easy I created more Config-Files for my clients with different AllowedIPs for only local or the complete Datatransfer through VPN
Conf1 = ... AllowedIPs = 192.168.0.0/24
Conf2 = ... AllowedIPs = 0.0.0.0/0, ::/0

Is it possible to set the allowed IPs at Creation-Time in the GUI - [+New] -> Name + IPs with prefilled "0.0.0.0/0, ::/0" for "all"?

![image](https://user-images.githubusercontent.com/33128735/210140462-7b956180-43f6-4dfa-ba70-cdad4c4f5d2d.png)

Thanks

**Comment by kellertobias** [comment]
Same here. Would be awesome to connect an external site
