### ISSUE TITLE
Webpanel not working

### ISSUE THREAD

**Issue by yxsyn** [wg-easy/wg-easy#448]
![image](https://user-images.githubusercontent.com/92877164/210456923-93e2f82b-3b7f-4bc3-8312-ea11c99de1d0.png)
 Web panel is not working on 0.0.0.0:51821

Please help

**Comment by eandersons** [comment]
With the provided amount of information nobody will be able to help you.

What is output of the command `docker logs wg-easy`?

If I had to make a guess, there will be the error `WireGuard exited with the error: Cannot find device "wg0"`. If so, search through [issues that contains this phrase](https://github.com/WeeJeWel/wg-easy/issues?q=is%3Aissue+%22WireGuard+exited+with+the+error%3A+Cannot+find+device+wg0%22+) as in some of them you might find a solution.

**Comment by Aekyios** [comment]
hello, didn't work too and always is working 
![image](https://user-images.githubusercontent.com/71457884/211417510-7e9a273d-abaf-4f94-a1f6-2fab9bf782fc.png)

**Comment by steinauf85** [comment]
I have the same output from my logs and also cannot open the webpanel. No Docker log saying it cannot find device wg0. I ran ifconfig in the console inside the container and found wg0. It's not visible outside the container but I believe that's because it's in bridge mode.
