### ISSUE TITLE
How to set the effective time for client access

### ISSUE THREAD

**Issue by zhoujiahua** [wg-easy/wg-easy#454]
**Hello everyone,**

How do we set an available time range for each accessed client?
For example, I want to make this access client available for **_30 days_** or between **_January 10, 2023 and February 10, 2023_**.

**Comment by themegabyte** [comment]
This will be a completely new system altogether. You cannot acheive this with the native wg/wg-easy implementation.

This can be achieved by leveraging the existing enable/disable mechanism to disable any clients that are past the expiration. Expiration dates can saved in the .json file and can be checked every minute by cron.

**Comment by zhoujiahua** [comment]
> This will be a completely new system altogether. You cannot acheive this with the native wg/wg-easy implementation.
> 
> This can be achieved by leveraging the existing enable/disable mechanism to disable any clients that are past the expiration. Expiration dates can saved in the .json file and can be checked every minute by cron.

Thank you for your answer, it is a very good suggestion.

**My current solution.**
- Step 1: when I create the client I add a calendar plugin that allows me to select the time interval, when I create the client successfully I will write the data of this set time to the json file together with the original data.
- Step 2: I added a timed task script on the server side, I will poll all the json data once in 3 seconds, if there is any expired data I will remove this data from the json file.

Currently it works, but one problem is that when we have multiple users at the same time, if there is expired data at this time the timer will update the json file, whether it will affect the use of other users, I am testing this problem.

If you have a better suggestion please let me know, thank you.

**Comment by themegabyte** [comment]
Ah Intresting!

Please do report back if your script causes any problems for the connected users. My theory is it shouldn't drop any clients from the server.
