### ISSUE TITLE
wg0 backup

### ISSUE THREAD

**Issue by hadi-dindar** [wg-easy/wg-easy#461]
hello i have a wg0.conf and wg0.json file from previous vps now my server ip changed and i run wg-easy in new vps but when i upload wg0 files to directory not work .

**Comment by Pleonazm** [comment]
wg0.conf is always changed by the container, so there is no point in changing it.
I my case turning off the container, then changing json file worked (wg0.conf was recreated automatically).
Note, you may rebuild the container with updated environment variables, then stop container and change wg0.json file.
I did not try to change config.json file manually
