### ISSUE TITLE
Performance is terrible when compared to native wg on linux

### ISSUE THREAD

**Issue by benisai** [wg-easy/wg-easy#463]
**Describe the bug**
This container has a nice UI, but the performance of WG itself is just terrible. I have two VPS's connected via native linux Wireguard (A--->B) and it works flawless with Grafana(A) fetching data from the other VPS Prometheus (B). 
I setup WG-easy, do the same config, and the performance/throughput is terrible. if I send too many data via the tunnel, it just stalls. 

**To Reproduce**
Native vs wg-easy to reproduce. 

**Expected behavior**
similar if not the same performance as native WG

**Desktop (please complete the following information):**
 - OS: Macos 13.1
 - Browser chrome
 - Version 108.0.5359.124

**Comment by benisai** [comment]
I set my MTU to 1500 in both WG0.conf, but still lacking, and very slow pulling back data from my prometheus database. Same with my influxdb.

**Comment by 12354** [comment]
Try setting the mtu lower to like 1300 for testing purposes

**Comment by shizunge** [comment]
I am curious whether you also see the problem if you set network mode to host?

**Comment by mfominov** [comment]
WG_MTU parameter is applied to newly generated configs.
For existing peer config u have change it manually.
I've set WG_MTU to 1384 by faced an issue there is no server configuration.
So i made some small fix by my self for me https://github.com/mfominov/wg-easy/commit/6144b3b2b7c6a44d6d58edd1916e3acd166b3a58

thank for advice
https://gist.github.com/nitred/f16850ca48c48c79bf422e90ee5b9d95

**Comment by Roan-V** [comment]
Can confirm it often stalls for me too, an iperf benchmark looks especially interesting
![image](https://user-images.githubusercontent.com/77012724/225229529-2804d52e-466a-4f18-a694-90b685a473aa.png)

If you managed to find a fix please let me know!
