### ISSUE TITLE
Client creation uses Server IP if I set WG_DEFAULT_ADDRESS=10.8.0.x (anything not the default) 

### ISSUE THREAD

**Issue by Simeon613** [wg-easy/wg-easy#470]
weejewel/wg-easy             latest    c90b263d8a38   7 months ago    142MB
I set: 
WG_DEFAULT_ADDRESS=172.16.20.1
or 
WG_DEFAULT_ADDRESS=192.168.80.1
or
WG_DEFAULT_ADDRESS=10.10.251.1

Every time I try to create a client, it uses the same address as the server and then does not let me create any additional clients. 
When I try to create an addition client I get "Maximum number of clients reached."

**Comment by eandersons** [comment]
As you can see in [Options](/WeeJeWel/wg-easy#options), the last part of `WG_DEFAULT_ADDRESS` has to be `x`.

At [`src/lib/WireGuard.js` line 233](/WeeJeWel/wg-easy/blob/f364e0775ab9bae81f3e5d4b5b1391db55f50296/src/lib/WireGuard.js#L233) starts the part that calculates the next available IP address and assigns it to clients by replacing `x` in the value of `WG_DEFAULT_ADDRESS` with the calculated value.

**Comment by LordPanda95** [comment]
Thanks, I was able to fix it by changing 
WG_DEFAULT_ADDRESS=10.8.0.1
to
WG_DEFAULT_ADDRESS=10.8.0.x
