### ISSUE TITLE
Allow a specific IP within a network

### ISSUE THREAD

**Issue by mrduszek** [wg-easy/wg-easy#471]
I have a router and a home network, in it there is a media player. My router has a built-in WireGuard server and client function. 

I have successfully set up a WireGuard server on an external VPS using wg-easy. I have successfully imported the generated config file into my router and the connection works fine. All the traffic goes through the VPN-Tunnel. So far, so good.

But now I want to configure the configuration file so that within my home network only one specific device (media player) gain access to the VPN tunnel via Wireguard. I did play with the "Allow IP...." but it won't work. Any ideas?

**Comment by csilva49** [comment]
This is mostly because you can't really configure the Allowed IPs in the Web UI for every client.

If you try to change it manually by modifying the wg0.conf or the wg0.json, your changes get rewritten.

Would be a VERY nice feature to have :P.
