### ISSUE TITLE
dns issue

### ISSUE THREAD

**Issue by sat-dish** [wg-easy/wg-easy#478]
**Describe the bug**
The readme states that the WG_DEFAULT_DNS default is 1.1.1.1 but it appears to be using the Hosts DNS if that is not configured. (It does not list any DNS entries in the WG config) 
If you select a different value like 1.1.1.1 or 8.8.8.8 the DNS fails to resolve. I am guessing a DNS mismatch. If I select the same DNS as the host things work correctly. (Likely an IP tables rule problem) Sorry I am not very familiar with IP tables but the readme suggests you can change the DNS easily which does not seem to work as intended.

**To Reproduce**
Listed above

**Expected behavior**
If you select 8.8.8.8 like the documentation suggests it should work. 

**Screenshots**

Server- 
OVH VPS Server

Client - 
Tested on Google Pixel 6 - Android - Latest Wireguard from App Store

**Comment by sat-dish** [comment]
As a follow up to this it looks like by default docker uses the host for DNS requests and this can be changed at the container level using the  --dns flag, as long as that matches what you have set in the wiregaurd config this seems to work.

**Comment by ffidan61** [comment]
Can you share your Dock Compose file? I think I have the same problem. Everything worked but somehow it stopped working 2 days agos without any changes from me.

**Comment by sat-dish** [comment]
Currently I am just using the host VPS machines DNS address, so whatever was in /etc/resolv.conf.
I took the DNS in /etc/resolv.com and used that in "WG_DEFAULT_DNS= " and that works fine.
I belive all you need to do is tell the container itself to use a matching DNS server and this will still work.

Example .

services:
  Wireguard:
    image: weejewel/wg-easy
    container_name: Wireguard
    dns:
      - "8.8.8.8"
      - "8.8.4.4"

________________________________

**Comment by toto99303** [comment]
+1 on this issue and I can't get it to work in Unraid. I tried setting the --dns flag and also WG_DEFAULT_DNS but it still doesn't resolve queries....

**Comment by sat-dish** [comment]
Try setting the DNS to the same as the host. This command should show your DNS in unRAID. 
Cat /etc/resolved.conf 
Then whatever number show up there, use that in the WG_DEFAULT_DNS= 
You can remove the other DNS entry. This should work.

**Comment by toto99303** [comment]
The problem is I want to use different DNS server than my Unraid host. For example my internal pi-hole which my Unraid is NOT using.

**Comment by sat-dish** [comment]
Ahh yes, that makes sense. Guess we need to wait for the developer to fix the issue.

**Comment by wassereimer86** [comment]
+1 with Unraid and when I want to use my AdGuard Server

**Comment by choque88** [comment]
Not fixed.
