### ISSUE TITLE
Is it possible to implement fullcone NAT?

### ISSUE THREAD

**Issue by YiGeRen-yl** [wg-easy/wg-easy#480]
Thanks a lot for the script, I'm a gamer, Is it possible to implement full cone NAT？I want to know.

**Comment by dr3st** [comment]
You can do this by yourself, just use the hook scripts to create some firewall rules (iptables -t nat -I PREROUTING | POSTROUTING). I use this by myself to interrupt the default masquerade rule.
In case you use docker, you have to keep in mind, that you have to NAT outside the container too, or define further ports in docker-compose to forward.
