### ISSUE TITLE
Masquerade UDP as TCP

### ISSUE THREAD

**Issue by senseiod** [wg-easy/wg-easy#485]
I want to add a feature.

Use tools such as Phantun to disguise UDP as TCP traffic in order to deceive Chinese network operators.

[Reason]
Chinese network operators do not use QOS to manage UDP packets, but limit the speed or even discard UDP packets.

[So...]
My computer skills are not very strong. After trying it myself, I found that everything is too complicated. The reason why I like this project is also because of its convenience and simplicity. Whether this feature can be added to the project, I will do my best to help the project complete this feature

Thanks!

**Comment by x066it** [comment]
I think that cloaking options is out of scope of this project. You should probably use something like Amnezia VPN or Outline VPN.
