### ISSUE TITLE
Feature request: Log view from UI

### ISSUE THREAD

**Issue by bestrocker221** [wg-easy/wg-easy#489]
First of all, thanks for the project!  Very useful, functional, and no hassle at all.

In case you look for feedback I have one. It would be a great value if it's possible to add in the UI a simple button with a log list of connect/disconnect events.
Eventually, logging in an SQLite DB would be nice, more importantly, the possibility to see logs is what matters here.

Thanks

**Comment by Shabinder** [comment]
+1 for this

**Comment by zackmuc** [comment]
+1 too

**Comment by florian-asche** [comment]
+1 really important!

**Comment by evanses** [comment]
+1! I'm trying to send log from wg to graylog right now
