### ISSUE TITLE
wg-easy + MikroTik mangle rule

### ISSUE THREAD

**Issue by krotish** [wg-easy/wg-easy#495]
Hey, I'm using **wg-easy** as docker within my MikroTik network. 

In my case MikroTik is marking (via mangle rule) and routing selected traffic via some different remote l2tp tunnel. Here's rules:
`/ip firewall mangle add disabled=no action=mark-routing chain=prerouting dst-address-list=to-l2tp \
    new-routing-mark=to-l2tp passthrough=yes`
`/ip route add disabled=no distance=1 dst-address=0.0.0.0/0 gateway=l2tp pref-src="" \
    routing-table=to-l2tp scope=30 suppress-hw-offload=no target-scope=10
`
**wg-easy** clients should be able to use it:-)

So, well, the issue is that if wg client is part of address-list networks that is affected by mangle rule — nothing (pings, traceses, etc) is working for client.

but. If:
- client is not part of address-list that is operated by mangle 
- mangle rule is disabled 
- wg client is connecting directly to MikroTik wireguard instead of wg-easy

everything works perfect

questions:
What should I allow on my router side or what should I change on wg-easy side.

Thanks in advance.

**Comment by mechjman** [comment]
I went the easy route and just port forward with my mikrotik router to the container. Is that not an option for you?

**Comment by krotish** [comment]
@mechjman of course, it's done already, without this nobody can connect.

The problem is that with mangle rule and routing this traffic people from mangled networks cannot connect.
