### ISSUE TITLE
not a bug, but a question:)

### ISSUE THREAD

**Issue by pasitiff** [wg-easy/wg-easy#504]
**Describe the bug**
could you please write more details for LAMERS, command, how to change some params?

**To Reproduce**
not clear, how to work with it:

"These options can be configured by setting environment variables using -e KEY="VALUE" in the docker run command."

**Comment by eandersons** [comment]
From [`docker run` reference regarding environment variables](https://docs.docker.com/engine/reference/run/#env-environment-variables):

> Additionally, the operator can set any environment variable in the container by using one or more `-e` flags [..]

Linked section contains some examples as well.

Or take a look at [`environment`](https://docs.docker.com/compose/compose-file/compose-file-v3/#environment) if Docker Compose is used.

`docker run` command in documentation section [Run WireGuardEasy](/WeeJeWel/wg-easy#2-run-wireguard-easy) and [`docker-compose.yml`](/WeeJeWel/wg-easy/blob/master/docker-compose.yml) contains examples on how to set WireGuard Easy specific environment variables.
