### ISSUE TITLE
Add quantum-resistant cryptography with rosenpass?

### ISSUE THREAD

**Issue by konstantin1722** [wg-easy/wg-easy#510]
Hi, can anyone add an integration with https://github.com/rosenpass/rosenpass?
Looks simple enough: https://rosenpass.eu/#start

**Comment by donBarbos** [comment]
@WeeJeWel, would like to see updates here

**Comment by donBarbos** [comment]
Maybe someone can help with setting up wg-easy with rosenpass, help with instructions

@konstantin1722, do you know how to use rosenpass and wg-easy together? Maybe you learned something new on this topic.

**Comment by konstantin1722** [comment]
> @konstantin1722, do you know how to use rosenpass and wg-easy together? Maybe you learned something new on this topic.

No, I've only used it with wireguard. I looked at how hard it would be to add it to wg-easy and I came to the conclusion that it's not possible to add it "with a swoop", at least for me, since ReactJS is not my thing. And I don't have the time to do it.

Although if someone takes up this, I am ready to help in any way I can, I know linux, C ++, bash, Python, JavaScript, TypeScript quite well, but I am not familiar with reactive frameworks.

**Comment by donBarbos** [comment]
> No, I've only used it with wireguard. I looked at how hard it would be to add it to wg-easy and I came to the conclusion that it's not possible to add it "with a swoop", at least for me, since ReactJS is not my thing. And I don't have the time to do it.

Okay, but firstly, I didn’t find the use of React here, and secondly, Rosenpass is not related to frontend, it's needed for key exchange.

**Comment by konstantin1722** [comment]
> Okay, but firstly, I didn’t find the use of React here, and secondly, Rosenpass is not related to frontend, it's needed for key exchange.
I watched this a year or more ago. Really no ReactJS. Apparently confused it with something else. I had intended to add Rosenpass to the GUI, of course it's possible not to do that, though it's odd in my opinion.
