### ISSUE TITLE
Connected, but how to use Internet connection

### ISSUE THREAD

**Issue by Mitch187** [wg-easy/wg-easy#516]
Hi,

How can i Use the Internet connection of the Wireguard Easy Server? Is it possible? From my Android mobile Phone.

Best Regards,
Mitch

**Comment by bcookatpcsd** [comment]
By default, you are routed through the host.. 

You are still limited by your connection to the server.. then the server has its limitations..

![image](https://user-images.githubusercontent.com/55087301/227647012-902b1fd9-66f0-45f9-9128-fcbcd6d411bd.jpeg)


Please provide more details.

**Comment by Mitch187** [comment]
Hallo,

here i have a AVM Firtz Box with a Router. When i connected to Wireguard Easy from the mobile phone net to my home-network, i can use ssh or http and local services from my home-network. But, wenn i connected to my home-lan, i cannot use internet connection from my phone. http-connections and other connections from my android phone does not work anymore.

Here ist my Docker Konfiguration:
`docker run -d --name=WireGuard-Easy --hostname=wg-easy -e WG_HOST=test.mmyhomnet.de -e PASSWORD=XXXXXXXX -v wireguard_config:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart always weejewel/wg-easy:latest`

![image](https://user-images.githubusercontent.com/70914017/227689239-4127577a-4c27-4837-8ec4-4dae6ab6710f.png)

**Comment by bcookatpcsd** [comment]
I think I understand your problem..

Set up docker to use host mode networking..

 --network host

You will modify your run commands.. removing the port options..

This will also demystify the nat and simplify the networking..

After this is working and you are able to log into the gui, you will need to generate a new configuration for your android device..

You will be leaving your fritz box the same way but will have encrypted connection on your lan..

we-easy would be used in a situation where the server is outside of your lan.. or you would connect to your server while out in the world..

In your case, when this works.. your mobile phone could connect to your fritz box while you are on the telephone network.. 

Hope this helps.. thanks for the details.

**Comment by Mitch187** [comment]
Hi,

thank you for your help. I have changed my configuration:
`docker run -d --name=WireGuard-Easy --hostname=wg-easy --network=host -e WG_HOST=home.netw0rk.de -e PASSWORD=XXXXXXXX -v wireguard_config:/etc/wireguard --cap-add=NET_ADMIN --cap-add=SYS_MODULE weejewel/wg-easy:latest`

After that, i put the new wireguard-config on my phone and quit the wlan direktly on the phone. then i connect to wireguard over mobile network.

After that, i can ping the docker-host from the phone, but not the ohter clients and the fritz.box in this lan network.


Bets Regards,
Mitch

**Comment by pernetz** [comment]
Hi @Mitch187 ,

make sure IP forwarding is supported by your docker host machine.
You may want to run the wg-easy container with `--sysctl="net.ipv4.ip_forward=1"`

Cheers, Lucas
