### ISSUE TITLE
User Connectivity Issue Resolved by Account Enable/Disable

### ISSUE THREAD

**Issue by amirdana** [wg-easy/wg-easy#517]
Sometimes one or more users are unable to connect, but disabling and enabling their accounts resolves the issue. I'm not sure why this happens, and any help would be appreciated.

**Comment by cometurrata** [comment]
I might have  a related  issue. I Figured out that killing the desktop app (user side ) and starting it fresh solves the problem too. Is this the case for you too ?

**Comment by HarshadkCon** [comment]
Are you still facing issue?

this could be unrelated to the code.

When you enable disable, effectively you are stopping and starting service with new config.

To eliminate the possibility, Worth trying tunnel start stop instead of account enable/disable.

**Comment by cometurrata** [comment]
> Are you still facing issue?

Yes actually, 

> When you enable disable, effectively you are stopping and starting service with new config.

I'm not doing it from the Wireguard Easy UI but from the wireguard desktop app 


<img width="603" alt="image" src="https://github.com/wg-easy/wg-easy/assets/23616466/67fd36e4-d3ae-4a87-9e0c-4fb4494bf595">


I have 3 instances of wireguard, and I have this issue on one of them mostly.

This issue MIGHT appear on the other instances but not as much and not as strongly .

I might reinstall it from scratch just to confirm

**Comment by peterlewis** [comment]
If this continues to be an issue then if it's ok with you it'd be great to continue this over in [Discussions](https://github.com/wg-easy/wg-easy/discussions). Tidying up the issues... :)
