### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tgssaa** [wg-easy/wg-easy#520]
How to modify the udp port 51820? Can you tell me the steps in detail?

Thank you very much for your contribution

**Comment by eandersons** [comment]
Do you want to change WireGuard port on the host or in the container? If on the host, then the host's port value can be changed in the port mapping.

**Comment by tgssaa** [comment]
Thank you for your reply!

What I want to know is, if I want to change 51820 to 60000, how should I carry out the specific steps?
I'm a linux idiot and just trying to use wireguard as a vpn.
Thank you so much!

**Comment by eandersons** [comment]
Just find `51820:51820/udp` in the `docker run` command or Docker Compose file (whichever you are using to start the WireGuard Easy container) and replace it with `60000:51820/udp`. This will map the host's port 60000 to the container's port 51820.
