### ISSUE TITLE
Add IP to a Peer's AllowedIPs

### ISSUE THREAD

**Issue by JasSmiths** [wg-easy/wg-easy#527]
Hi @WeeJeWel 

Just having a play around with WG-Easy now and so far I'm really impressed, great work! 

Is it possible to manually add an IP into a Peers AllowedIPs? I need to add this for just one of my peers and I cant seem to find a way to do it?

e.g.

`[Peer]`
`PublicKey = Redacted`
`PresharedKey = Redacted`
`AllowedIPs = 10.0.4.13/32,10.0.0.0/24`

Thanks

**Comment by Regis-Loyaute** [comment]
you can with docker-compose

version: "3.8"

networks:
  vpn-network:
    external:
      name: vpn-network

services:
  wg-easy:
    environment:
      - WG_HOST=
      - PASSWORD=
      - WG_DEFAULT_DNS=10.100.1.254
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=192.168.0.0/16, 10.0.0.0/8
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "51822:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - vpn-network

**Comment by yo3ibw** [comment]
@Regis-Loyaute , no it can't be done like that. WG_ALLOWED_IPS is only for the Interface, not for the Peer section. I have the same problem like @JasSmiths ... Would be nice to have this option. :)

**Comment by Inosss** [comment]
> @Regis-Loyaute , no it can't be done like that. WG_ALLOWED_IPS is only for the Interface, not for the Peer section. I have the same problem like @JasSmiths ... Would be nice to have this option. :)

https://github.com/WeeJeWel/wg-easy/blob/master/src/lib/WireGuard.js#L114

seems to be hardcoded. I think best way is fork this repo and build all yourself.

**Comment by dossec** [comment]
I entered into the container to add it, and wg-quick down wg0 && wg-quick up wg0, but it can't restart the  container, I don't know if there is another better way

**Comment by Inosss** [comment]
> I entered into the container to add it, and wg-quick down wg0 && wg-quick up wg0, but it can't restart the container, I don't know if there is another better way

Hello. There is one workaround.

Options for container stored in .wg-easy/wg0.json
We can manual edit this file like that:
"address": "10.8.0.0/24,10.8.0.2",

We need to add allowed network with netmask before peer ip and restart container. In this case all works fine, but when we create new user in web ui, it iterate last user's ip by one, and new user creation will be... some tricky. Anyway - this is a crutch.

**Comment by Inosss** [comment]
Or u can take another repo like https://github.com/ngoduykhanh/wireguard-ui

**Comment by dossec** [comment]
> Or u can take another repo like https://github.com/ngoduykhanh/wireguard-ui

tks,It is already in use now，and met all my needs

**Comment by gdtv** [comment]
any update ? I need this feature

**Comment by kaaax0815** [comment]
@gdtv this is now possible with v15
