### ISSUE TITLE
How to connect to configuration with already connected customers /etc/wireguard/wg0.conf? 

### ISSUE THREAD

**Issue by Paul1804** [wg-easy/wg-easy#540]
How to connect to configuration with already connected customers /etc/wireguard/wg0.conf ?

**Comment by VATICAN-PSYCHO** [comment]
After fast code analyze, i can say that wg0.conf (or any other config file of WG) is based on wg0.json (in my case and probably in yours).

Depending on size of your network you can: rewrite by hand (or by script know something) everything to JSON.
**However**, in my opinion, (re-)implementation would be better. This way you will avoid any problems related to importing.

File: `/etc/wireguard/wg0.conf`
Content: `# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = PRIVATE_KEY
Address = 10.8.0.1/24
ListenPort = 51820
PreUp =
PostUp =  iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
PreDown =
PostDown =


# Client: CLIENT_NAME (UUID)
[Peer]
PublicKey = PUB_KEY_OF_HOST
PresharedKey = PRE_KEY
AllowedIPs = 10.8.0.2/32`

File: `/etc/wireguard/wg0.json`
Content: `{
  "server": {
    "privateKey": "PRIVATE_KEY",
    "publicKey": "PUBLIC_KEY",
    "address": "10.8.0.1"
  },
  "clients": {
    "UUID": {
      "name": "CLIENT_NAME",
      "address": "10.8.0.2",
      "privateKey": "PRV_KEY_OF_HOST",
      "publicKey": "PUB_KEY_OF_HOST",
      "preSharedKey": "PRE_KEY",
      "createdAt": "2023-05-04T21:06:29.001Z",
      "updatedAt": "2023-05-04T21:16:31.791Z",
      "enabled": true
    }
  }
}`

Of course, do not forgot about tunning this config to your environment.
