### ISSUE TITLE
How to prevent wireguard to set wrong route in a docker setup when using none default ip 10.8.0.0/24

### ISSUE THREAD

**Issue by RudiOnTheAir** [wg-easy/wg-easy#542]
Hi

See screenshot from inside container. Due to a 2nd wireguard vpn i can't use the default 10.8.0.0/24 range. The containerconfig is:

...
  -e WG_DEFAULT_DNS=8.8.8.8 \
  -e WG_DEFAULT_ADDRESS=10.5.0.x \
  -v ~/.wg-easy:/etc/wireguard \
...

![Image 2023-05-05 at 09 45 17](https://user-images.githubusercontent.com/47517341/236414944-15a97bf2-b508-41fc-a7a9-94010be45747.jpeg)

Thanks in advance

**Comment by VATICAN-PSYCHO** [comment]
Could you post config of 1st docker container? In my opinion it looks like both of them use same settings/configs because of this: `-v ~/.wg-easy:/etc/wireguard `

**Comment by RudiOnTheAir** [comment]
Uuups, ur right. That should be the problem. Don't know, why that happens Does it need more than fixing it in wg0.conf? Because of:

`# Note: Do not edit this file directly.
 Your changes will be overwritten!
`

> 
...Server
[Interface]
PrivateKey = iFX****************************************=
Address = 10.8.0.1/24
ListenPort = 51820
PreUp =
PostUp =  iptables -t nat -A POSTROUTING -s 10.5.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --d>
PreDown =
PostDown =

Thanks...

**Comment by jack3308** [comment]
> Uuups, ur right. That should be the problem. Don't know, why that happens Does it need more than fixing it in wg0.conf? Because of:

Did this work for you? I'm wanting to do something similar but struggling a bit.
