### ISSUE TITLE
client receives no data

### ISSUE THREAD

**Issue by baptisterajaut** [wg-easy/wg-easy#547]
Good day everyone.
I've tried twice to setup a simple wg vpn with wg-easy, twice i failed.
First was a docker container, second was without docker (bare-metal), twice the same issue : 
While i'm connected to the vpn and can ping myself, i can't even ping the wg host in 10.7.0.1. Of course i can't access anything as well. If i check the conf of wireguad, i can see the server receiving and sending data : 
```bash
$ wg show
interface: wg0
  public key: ...
  private key: (hidden)
  listening port: 51820

peer: ...
  preshared key: (hidden)
  endpoint: clientip:56791
  allowed ips: 10.7.0.2/32
  transfer: 16.33 KiB received, 10.15 KiB sent
```
but the client receives nothing

```bash
poki@Poki-RedGyarados ~ % sudo wg show
interface: bayesiawg
  public key: ...
  private key: (hidden)
  listening port: 56791

peer: ....
  endpoint: serverip:51820
  allowed ips: 10.0.0.0/8
  transfer: 0 B received, 740 B sent
```

I want to note that i just want to route the 10.0.0.0/8 traffic into wireguard (private network i want to access)

Thanks. I belive this is a WG issue and not much a wg-easy issue, but i don't know what to do more.

**Comment by Pleonazm** [comment]
I would check NAT settings.
Do you have port forwarding on your firewall/gateway/NAT thingy configured?
Maybe add keepalives to your config (PersistentKeepalive = 25)
Also, do you need a static port declaration on the client? I often make only static port declarations on the server, on clients only giving server IP.

**Comment by baptisterajaut** [comment]
I didn't do much in terms of NAT, i just fixed this in config.js so it would match my interface
```
iptables -t nat -A POSTROUTING -s ${module.exports.WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ens192 -j MASQUERADE;
iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;
iptables -A FORWARD -i wg0 -j ACCEPT;
iptables -A FORWARD -o wg0 -j ACCEPT;
```

I want to point out , on the client side i'm using network manager to connect to WG. I believe i did not set up a static port?

```bash
cat /etc/wireguard/wg0.conf 

# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ...
Address = 10.7.0.1/24
ListenPort = 51820
PreUp = 
PostUp =  iptables -t nat -A POSTROUTING -s 10.7.0.0/24 -o ens192 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; 
PreDown = 
PostDown = 


# Client: rajaut 
[Peer]
PublicKey = ...
PresharedKey = ...
AllowedIPs = 10.7.0.2/32
```

For the keepalive part, how do i add this through wg-easy?

**Comment by claudiutraistaru** [comment]
As always , the problem in my case was between the keyboard and the chair :) , I was forwarding the wg-port as TCP , should be UDP.
