### ISSUE TITLE
Client/peer interface subnet issue

### ISSUE THREAD

**Issue by skiby7** [wg-easy/wg-easy#552]
Inside `getClientConfiguration` in [src/lib/WireGuard.js#L202](https://github.com/WeeJeWel/wg-easy/blob/master/src/lib/WireGuard.js#L202), peer address is set to `Address = ${client.address}/24`: shouldn't it be `/32`? Every time I set up a client via other automated methods (pivpn or [linuxserver/wireguard](https://hub.docker.com/r/linuxserver/wireguard) container), the subnet mask of the interface created is set to `/32`, while setting up a client with wg-easy, it's set to /24. Does that make a difference?

# wg-easy config imported on iPhone
![wg-easy](https://github.com/WeeJeWel/wg-easy/assets/70918126/cce4230d-92ee-4ad3-bcf0-6bea6051d5ca)

# linuxserver/wireguard config imported on iPhone
![linuxserver/wireguard](https://github.com/WeeJeWel/wg-easy/assets/70918126/de087377-ef94-40db-9944-9961d387976f)

**Comment by wofkka** [comment]
same question
