### ISSUE TITLE
Unable to start on DSM7.2 Container

### ISSUE THREAD

**Issue by davisstu** [wg-easy/wg-easy#557]
**Describe the bug**
wg-easy fails to start on DSM 7.2 with the new container function on DS220+

<img width="1023" alt="image" src="https://github.com/wg-easy/wg-easy/assets/8912521/bb13b96b-d7b4-45fd-9e1e-b6d4248d09de">

**Comment by magefesa** [comment]
SAme problem here !

**Comment by RickGW** [comment]
Same problem here.

**Comment by RickGW** [comment]
> Probably have to install a newer version of the WireGuard service.
> 
> I've followed https://www.blackvoid.club/wireguard-spk-for-your-synology-nas/ which has new packages to install for 7.2 (also steps to roll your own).

Confirmed, works here as well! Thanks!

**Comment by magefesa** [comment]
Thanks!

**Comment by aleksey-vi** [comment]
after installing WG packages for DSM 7.2, I start it but after a few seconds it says "stopped manually" please help me solve this problem
