### ISSUE TITLE
Slow upload fast Download

### ISSUE THREAD

**Issue by Dulox24** [wg-easy/wg-easy#561]
I have the problem on my laptop that as soon as I am connected to the wireguard server that the upload speed decreases to 1 mbps where it is in this hotel 100 mbps.

Is there anything I can do to make the upload speed normal? 

I am using a Raspberry Pi 4B for and have the Wireguard installed via Docker as in the tutorial,.
I tried to find the config file to change the MTU, but I am very new to this whole docker and Pi stuff so i can't find the files....

Who could help me out ?

**Comment by rgriffogoes** [comment]
Network speeds are always dependent on all devices in the chain. 

For example, just did some tests on my side:

Phone on 5g/Celluar data = 460Mbps 
Phone on > home wifi repeater router > verizon =  246Mbbps
Phone on Cel data > wireguard home (bare metal PiVPN Raspberry Pi 3b+) > wifi repeater router > verizon = 10mbps
Phone on Cel data > wireguard2 home (wg-easy docker Raspberry Pi 3a+) > wifi main router > verizon = 20 mbps

As you can see, I'm getting major bandwidth drop when using VPN, but I would likely atribute it to RPi 3 hardware. My dockerized wg server is actually faster (cant really tell why, maybe it is just a much newer version of wg + linux kernel)
