### ISSUE TITLE
wg-easy running in Docker on Ubuntu VPS: Connected client loses all outside internet connection; host networking not working

### ISSUE THREAD

**Issue by Nezteb** [wg-easy/wg-easy#562]
**Describe the bug**
There are a few similar issues to this:
- https://github.com/wg-easy/wg-easy/issues/516
- https://github.com/wg-easy/wg-easy/issues/539

The comments for each issue do not provide a final solution. I have the same problem as them. I've got `wg-easy` set up via Docker compose on a normal Ubuntu 22.04 VPS I'm paying for. The VPS has access to the outside internet. After following [the Docker compose nginx/ssl docs](https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL), I open the web UI, I create a client, I use that client config to join the WireGuard network on my laptop, and then I lose all Internet access. This seems like a common usecase for `wg-easy`, especially if you're using Docker compose, so I'm surprised that this isn't documented.

The main problem is that neither [the main `README.md` Docker docs](https://github.com/wg-easy/wg-easy/blob/5e5506eea073e94a3cadf91a18df41972d805ae6/README.md#2-run-wireguard-easy) nor [the Docker compose nginx/ssl docs](https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL) mention how to configure host networking.

There's a bunch of different links I've tried to follow to set up host networking properly with this Docker compose setup, but I couldn't get anything working:
- https://www.reddit.com/r/docker/comments/t0vqy7/dockercompose_with_networking/
- https://stackoverflow.com/questions/56582446/how-to-use-host-network-for-docker-compose
- https://github.com/compose-spec/compose-spec/blob/master/spec.md#network_mode
- https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
- https://forums.docker.com/t/option-network-mode-host-in-docker-compose-file-not-working-as-expected/51682

If I try to enable host networking for the main `wg-easy` container, my `nginx` container randomly keeps restarting. If I try to define separate networks for host/bridge networking and use those, I get errors about only one host network being allowed (similar to the above Reddit thread). If I try to enable host networking for both `wg-easy` and `nginx`, the `nginx` container still constantly restarts. 🤷‍♂️ 

On another note, this portion of [the Docker compose nginx/ssl docs](https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL) is not ideal:

> Then run once:
> 
> ```
> $ docker exec -it nginx /bin/sh
> 
> cp wg-easy.conf /etc/nginx/conf.d/.
> 
> $ certbot --nginx --non-interactive --agree-tos -m webmaster@google.com -d ⚠️wg-easy.myhomelab.com
> $ nginx -s reload
> $ exit
> ```

If you happen to restart your Docker compose stack (or just the `nginx` container), you will lose all of your configs and have to reconfigure everything.

**Comment by Hamsterman** [comment]
I am running on Ubuntu 22.04 aswell and got the same issue.
I used to run the "regular" wireguard docker on Ubuntu 20.04 with no issues.
On that I put in this in the config
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

I tried to convert that into the wg-easy but no luck. But my guess is that if that would work we could make wg-easy work. As I remember that was the solution on 20.04.

**Comment by pythonSB** [comment]
I have encountered the same problem, try to change the key and use

**Comment by JamesOsborn-SE** [comment]
A workaround is to set `WG_POST_UP` with iptable rules

Warning, I am not an networking expert. 

I prepend the env var `WG_POST_UP` with clearing the tables because `WG_POST_DOWN` is not guaranteed to be called.

notes on the below:
`eno2` is the device connected to your lan
`51820` is wg port

set `WG_POST_UP` to
`iptables -P INPUT ACCEPT; iptables -P FORWARD ACCEPT; iptables -P OUTPUT ACCEPT; iptables -t nat -F; iptables -t mangle -F; iptables -F; iptables -X; iptables -t nat -A POSTROUTING -o eno2 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;`

after that I was able to connect to the internet and other devices on my lan.

**Comment by peterlewis** [comment]
Hi @JamesOsborn-SE! Please note that the setting of a specific MTU was implemented, but has now been reverted by @pheiduck. Apologies for any inconvenience.

I note that the issue described here is somewhat different to that you raised in https://github.com/truenas/charts/pull/1931, so if there are outstanding concerns then I would be pleased to hear them so that we can work together to a common goal!

**Comment by cornradio** [comment]
I have the same problem.
I guess it's a problem with the VPS network configuration, my vps ubuntu version 22.04 
I have a home server (with public ip), ubuntu 22.04 can vpn normally and use internet.

Need solution

**Comment by thehatware** [comment]
I was having trouble with this off of the default configuration provided for clients, which sets AllowedIPs to 0.0.0.0/0, ::0/. When I take away "::0/" the internet tunnel began working. I ended up with AllowedIPs = 0.0.0.0/0, 10.8.0.0/24 to have all traffic tunneled and access peers on the WG network.

I'm not sure why the IPv6 catch-all was causing issues, but may be a good idea to change this default until IPv6 is more common.

**Comment by JamesOsborn-SE** [comment]
Update: It's working for me now in TrueNas Scale, even with the `AllowedIPs to 0.0.0.0/0, ::0/` and not setting the `WG_POST_UP`
