### ISSUE TITLE
Which file contains download and upload amount?

### ISSUE THREAD

**Issue by Iman-Sh** [wg-easy/wg-easy#564]
there is a json file that contains all the clients but i can't find the file which contains users used traffic!

**Comment by eandersons** [comment]
I do not think that WireGuard Easy has such file.

The closest to what you are seeking would be data that is availabe in user interface or to execute the command `wg show` within container, as this command ([`wg shown wg0 dump`](/wg-easy/wg-easy/blob/master/src/lib/WireGuard.js#L152)) is used to get data transfer values to display in user interface, but I guess that these values are not persisted across container restarts/recreations.
