### ISSUE TITLE
add client via wireguard client?

### ISSUE THREAD

**Issue by Jumbo125** [wg-easy/wg-easy#567]
Hello
I try to add a new client via my Smartphone. In the app isn't any function.
I'm sometomes not at home in my homenetwork, but i need a new client for a other pc.

Can i add a new client via my Smartphone?

**Comment by oplexz** [comment]
> add client via wireguard client?

If you're referring to the instance of WireGuard running on your device -- that is impossible.

If you need to access the Web UI outside of your home network, you can:

a) Assuming you managed to expose the WireGuard port to WAN (51820 by default), you could expose 51821 (the Web UI) as well. Having the Web UI exposed to WAN means not just you, but everyone else can access it too. Make sure you're using a password if you're planning to expose the Web UI.

b) Connect to your WireGuard server, and access the Web UI at http://10.8.0.1:51821/
`10.8.0.x` is the default IP range, if you have changed `WG_DEFAULT_ADDRESS` -- access the first IP in that range (ex.: for range `10.10.10.x`, the desired address will be http://10.10.10.1:51821/ instead.
