### ISSUE TITLE
installation without docker

### ISSUE THREAD

**Issue by FIONover** [wg-easy/wg-easy#569]
https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-without-Docker

In the moment with wg-easy.service file, we need to download the file, but https://envs.sh/QQK.txt doesn't work (or give other output)

**Comment by nghialele** [comment]
@WeeJeWel

**Comment by WeeJeWel** [comment]
I didn't write this wiki article.

**Comment by LPTP1Dev** [comment]
any news on this one? having the same issue.
