### ISSUE TITLE
Wireguard on Xpenology

### ISSUE THREAD

**Issue by mandgeo** [wg-easy/wg-easy#576]
I was successfully using wireguard on DSM 7.1 installed after this tutorial https://www.blackvoid.club/wireguard-vpn-for-your-synology-nas/
After I've updated DSM to 7.2, wireguard container doesn't want to start. I get this error " {"message":"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown"}"
I've tried installing and reinstalling in every possible way, launched script with docker-compose, cleaned unused docker images...same result.
Another detail...after DSM upgrade, the wgeasy container didn't started, maybe because it needed the correct spk installed, so I've reinstalled. The problem was that I couldn't delete the container. I had to manually delete the btrfs volume. 
Do you have any idea what I can do to make it work again?

Thank you!

**Comment by hassansf** [comment]
I've a similar issue, when I try creating my own spk, I get the following error:
Cloning into 'pkgscripts-ng'...
[2023-08-25 00:07:39,526] ERROR: PlatformNotAvailableError
[2023-08-25 00:07:39,526] ERROR: [v1000] is not available platform.
[2023-08-25 00:07:39,526] ERROR: pkgscripts-ng/EnvDeploy -p v1000 -v 7.2 failed!

using 7.2  (DS2422+)
