### ISSUE TITLE
Can't connect to web interface. 

### ISSUE THREAD

**Issue by Micromot20** [wg-easy/wg-easy#580]
When i try to connect it just says:

```
 Unable to connect
 Firefox can’t establish a connection to the server at 0.0.0.0:51821.
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

```

**Comment by eandersons** [comment]
Are you trying to open WireGuard Easy user interface on the same computer where containers are running?

**Comment by Micromot20** [comment]
> Are you trying to open WireGuard Easy user interface on the same computer where containers are running?

No I'm trying to get into it from a different computer, the wg easy is running on my raspberry pi.

**Comment by eandersons** [comment]
In that case you have two options:

- use the IP address of the server if you are trying to access WireGuard Easy user interface from the local network;
- use a reverse proxy to access WireGuard Easy user interface from Internet via hostname/domain and  standard web ports.

**Comment by SeryiBaran** [comment]
> In that case you have two options:
> 
> * use the IP address of the server if you are trying to access WireGuard Easy user interface from the local network;
> * use a reverse proxy to access WireGuard Easy user interface from Internet via hostname/domain and  standard web ports.

I'm try to connect by IP from lan, but even ping doesn't work =(

**Comment by 404king** [comment]
I was in similar situation (running in portainer on Linux Mint)

This is still a steep learning curvefor me still, but ended up restarting Linux before it worked
