### ISSUE TITLE
Multiple Allowed IP Ranges

### ISSUE THREAD

**Issue by TheRouce** [wg-easy/wg-easy#581]
Hey, I did my best to check around and see if this is a duplicate, but let me know if I missed something and I'll close this.

### Different Levels of Access for wg-easy Instances

I am exploring a use case where I want to run a single  wireguard server, but with clients having different levels of access.

**Group of Clients 1:** The management group would have access to everything. Using the default range.

**Group of Clients 2:** This group would have access to the range 10.5.2.220 through 10.8.2.255.

**Group of Clients 3:** The final client group would have access to the IP range 10.5.2.0 through 10.8.2.25.

The eventual goal is to reflect these different access levels in the web UI as groups, so instead of everything in the one group "clients" you would be able to make a group with a certain allowed IP range and name them accordingly.

![webui](https://i.imgur.com/ohNJtCa.png)

So, I'm wondering if this is something that could possibly be introduced as a future feature, and if there's anything I can do to help move this along as a feature. Also, please let me know if something like this already exists as that would be interesting to look into as well.

**Comment by TheRouce** [comment]
I should note, the image provided and the overall idea is just spitballing the final look. 

But, I think an easier thing to start would probably just be adding a couple more fields to when you click new. So, instead of just adding a name you can add overrides for the default settings. Though, I have no experience with y'all's code base so I don't know if this is actually any easier.

**Comment by megoRU** [comment]
It looks cool. Will there be problems with merging clients with the Stable branch? And how is the API?
My wrapper: [WG-easy-wrapper](https://github.com/megoRU/wg-easy-wrapper
)

**Comment by bmarinov** [comment]
Any chance to get the issue reopened? Im also interested in this and was hoping to see something about it from the maintainer 🥇 
CC @WeeJeWel 

My use case is that I need two configs per client: full-tunnel config (allowed ips 0.0.0.0/0) and subnet-only (10.x.x.x/24). Currently this involves manual edits for the file and the QR code feature is also not usable. 
The alternative seems to be an API wrapper or a second instance of wg-easy (ouch). I might end up writing my own wrapper so I can better fit it to my use cases.

**Comment by Xitee1** [comment]
I also need groups or per profile settings (at best both).
@bmarinov how did you assign subnets per client? I have only two config files and I cannot find the allowedIPs setting for the clients anywhere. So far I found out that they must be generated automatically.

**Comment by bmarinov** [comment]
> I also need groups or per profile settings (at best both). @bmarinov how did you assign subnets per client? I have only two config files and I cannot find the allowedIPs setting for the clients anywhere. So far I found out that they must be generated automatically.

I solved the problem by .. generating two config files and modifying one of them (added IP ranges) manually. I guess this is something we should open a new issue for.

**Comment by kaaax0815** [comment]
This would only change the generated config (which doesn't improve security).
just create multiple clients.
Adding Allowed Ips to Clients is possible with #1333
