### ISSUE TITLE
Readme/Screenshot should clarify that keys are for devices (1 on 1) and not for users/humans

### ISSUE THREAD

**Issue by thomasmerz** [wg-easy/wg-easy#595]
Due to the fact that wireguard uses keys to **authenticate a device** and not a user this should be clearly stated and shown on Readme by a screenshot with "tom's computer", "tom's laptop", "tom's smartphone-private", "tom's smartphone-work", …
See also https://serverfault.com/questions/948816/wireguard-user-authentication for details.

**Comment by thomasmerz** [comment]
@WeeJeWel , could you please update the screenshot in the Readme so that it's clear that WireGuard authenticates per device and not per user/human? Thanks a lot! 😗

**Comment by WeeJeWel** [comment]
You can make a PR for a better screenshot :-)

**Comment by thomasmerz** [comment]
I wish I could… but unfortunately I'm using plain WireGuard without your great tool anymore… 🤷🏼‍♂️ But I can and will add some nice text to the screenshot that clarifies how WG authenticates via a PR.

**Comment by thomasmerz** [comment]
Won't be fixed as nobody seems to be able to provide a screenshot that clarifies that WireGuard keys are for Emile's, Jason's, Linus' and Adam's **device** and not for the persons themself. 😞
