### ISSUE TITLE
lib/WireGuard.js - ListenPort is hardcoded as 51820

### ISSUE THREAD

**Issue by whithil** [wg-easy/wg-easy#602]
Greetings, 

First of all, thanks for this great tool. It saved my life today.

Yet, while attempting to use the generated wg0.conf as a volume into a regular apt-intalled WireGuard (because I love your U.I.)
I've noticed this value is not following the docker env:
https://github.com/wg-easy/wg-easy/blob/642d6d62edb95a96e57b704966b65135f4f3ea94/src/lib/WireGuard.js#L98C10-L98C10

I edited the value manually to `${WG_PORT}` and now it works fine.
Please consider editing it so it carries the defined WG_PORT from env.

cheers,

**Comment by eandersons** [comment]
From WG_PORT description in [Options](https://github.com/WeeJeWel/wg-easy#options):

> The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.

Value of WG_PORT is used in peers configuration. Interface will allways use the default WireGuard port (51820) within container. \
Your use case is out of scope of this project.

Also, please [search for similar issues](/WeeJeWel/wg-easy/issues?q=is%3Aissue+WG_PORT) before posting your own! [A search in pull requests](/WeeJeWel/wg-easy/pulls?q=is%3Apr+WG_PORT) could give some additional insight as well.

**Comment by pothi** [comment]
If you are using a non-default UDP port, you have to change it in two places while creating the docker container...

1. The port that exposed to the host
2. The value of `WG_PORT`

Here's the sample configuration that uses a non-default UDP port of 55555...

```
docker run -d \
  --name=wg-easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \

  -e WG_PORT=55555 \
  -p 55555:51820/udp \

  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy
```

**Comment by jisukuke5** [comment]
I found 2 bugs,
the first bug is in "/src/config.js",you can find "iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;".
And"--dport 51820" should be "--dport ${module.exports.WG_PORT}".
another bug is in "/src/lib/Wireguard.js",you can find "ListenPort = 51820",
and it should be"ListenPort = ${WG_PORT}".

**Comment by tourshi** [comment]
I'm facing the same issue. Even changing it as @pothi  suggested, but it appears port 51820 is hardcoded

**Comment by jisukuke5** [comment]
> I'm facing the same issue. Even changing it as @pothi suggested, but it appears port 51820 is hardcoded

you need to edit the two files in the docker's container "weejewel/wg-easy" to fix bugs.
