### ISSUE TITLE
Problem installing on Linux machine running on OpenVZ, Cannot find device "wg0"

### ISSUE THREAD

**Issue by roointan** [wg-easy/wg-easy#609]
**Describe the bug**
The Docker container keeps restarting, after running the [docker run](https://github.com/wg-easy/wg-easy#2-run-wireguard-easy) command.

```
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
```

running the add wg0 interface manually:
```
root@Ubuntu18:~# ip link add dev wg0 type wireguard
RTNETLINK answers: Operation not supported
```

As explained [here](https://wiki.openvz.org/VPN_using_Wireguard): 
As Virtuozzo is very keen on security and stability, we don't allow creation of any unverified network interface inside Containers.
Only those which are safe (verified and considered properly virtualized) are allowed.
(If I guessed the cause of the problem right)

**To Reproduce**
Try running on an Ubuntu machine running in OpenVz 

**Expected behavior**
Expect some hacks to work around this and make it work, please :) 

**Desktop**
 - OS: Ubuntu 18.04.6 LTS

**Additional context**
[VPN Using Wireguard from OpenVz Wiki](https://wiki.openvz.org/VPN_using_Wireguard) and [install Wireguard on OpenVz VPS](https://www.reddit.com/r/WireGuard/comments/rtfi58/easy_way_to_install_wireguard_on_a_openvz_vps/) and [wireguard-go](https://d.sb/2019/07/wireguard-on-openvz-lxc) might help fix this.
I could install and useOpenVPN on this server. The tun interface was created without problem.

**Comment by kindomLee** [comment]
This works for me: https://github.com/wg-easy/wg-easy/issues/245#issuecomment-1114054686

> `sudo modprobe wireguard` was giving me an error; if it doesnt, i guess it means its already installed and you dont have the same issue as me.
`sudo apt-get install linux-headers-$(uname -r)` to install the headers needed

**Comment by MystWeb** [comment]
Error：This usually means that your host's kernel does not support WireGuard!

1、中文：
      这是由于你的操作系统内核找不到 wireguard 模块，解决方案：升级内核至 5.6及更高版本并加载该内核模块
      English：
      This is because your operating system kernel cannot find the Wireguard module, solution: upgrade the kernel to 5.6 and higher versions and load the kernel module

2、中文：你可能还需要启动内核：iptable_nat，规避异常：can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
      English：You may also need to start the kernel: iptable_ Nat, avoiding exceptions: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
      
3、中文：升级内核后启动需要的内核模块：[root@localhost ~]# modprobe iptable_nat wireguard
      English：Starting the required kernel modules after upgrading the kernel：[root@localhost ~]# modprobe iptable_nat wireguard

**Comment by Kwallie010** [comment]
I do not have the same OS, but I did run into the same error. I finally solved the error with the following docker compose: 

```version: "3.8"
services:
  wg-easy:     
    image: weejewel/wg-easy
    container_name: wireguard
    restart: unless-stopped
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51822:51820/udp"
      - "51821:51821/tcp"
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${PASSWORD}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1```
