### ISSUE TITLE
How to add traffic obfuscation? (mask VPN traffic)

### ISSUE THREAD

**Issue by donBarbos** [wg-easy/wg-easy#617]
VPN protocols are easily detected (using DPI), so they're easily blocked and don't help mush against real (strict) censorship,
 I would like to know how to mask my VPN traffic through `Stunnel` or `Shadowsocks` or `SSTP` or something else. I heard it's better to use shadowsocks.
 Can you tell me how to solve this problem with this wonderful manager?

**Comment by chebakoff** [comment]
Cloak например, как подключить?
