### ISSUE TITLE
/32 is forced in the allowed ips

### ISSUE THREAD

**Issue by ajmandourah** [wg-easy/wg-easy#619]
**Describe the bug**
So basicly I set up a site to site connection and i wanted to use wg-easy for its simpliciy and interface. A list of allowed ip should be set to achieve a site to site setup . I was forced to make a workaround where in the json file i set up the allowed ips as "X.X.X.X , Y.Y.Y.Y" where Y is the ip of the peer. with this i noticed that the script is forcibly adding /32 to the end of the str. I dunno if this is connected in what you set the interface Address . but as a suggestion a more customizable approach is needed for other situations. 

**To Reproduce**
1. Go to 'wg0.json or the interface'
2. Click on 'ips in the intereface to change the allowed ip . 
3. it is basicllly forcing a /32 

**Expected behavior**
A more customizable allowed ip . in case i want to include another network

**Comment by deveth0** [comment]
This seems to originate from here:
https://github.com/wg-easy/wg-easy/blob/master/src/lib/WireGuard.js#L114

afaics this completly breaks the WG_ALLOWED_IPS functionallity

**Comment by ajmandourah** [comment]
I agree. as with this you are forced to allow an entire network . instead of a certain device . which should be the default in a site to site connection .

**Comment by pierluigizagaria** [comment]
I'm currently trying to set a customized allowed ips list using WG_ALLOWED_IPS, but id doesn't work
