### ISSUE TITLE
Coudn't connect to wg-client Mikrotik's subnet from wg-server

### ISSUE THREAD

**Issue by Sarevok933219** [wg-easy/wg-easy#631]
Hello. I have a working wg-easy server in docker on Centos7, deploying in cloud. The other site is client on Mikrotk device. WireGuard tunnel connection is ok. Cloud local subnet is 10.0.0.0/24, server has an IP = 10.0.0.19. Docker subnet is 172.150.88.0/24 and the container with wg-easy has an IP = 172.150.88.10/32. Wg subnet is 10.100.10.0/24 wg interface in docker (wg0) gets IP 10.100.10.1, Mikrotik IP wireguard interface gets IP = 10.100.10.2 and Mikrotik local subnet is 192.168.1.0/24 (bridge has an IP = 192.168.1.1, hosts - 192.168.1.x/24). From Mikrotik and it's local subnet I can access to hosts behind wg-server and also directly to wg-easy container. But wg-server and cloud host behind the server (subnet 10.0.0.x/24) can't access to Mikrotik subnet 192.168.1.0/24, but have access to Mikrotik wireguard interface (10.100.10.2/32). In docker container I added route  ip ro add 192.168.1.0/24 via 10.100.10.2 but ping 192.168.1.1 returns strange message:  "ping: sendto: No error information". 
iptables in wg-easy container
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DOCKER_OUTPUT
-N DOCKER_POSTROUTING
-A PREROUTING -i wg0 -j DNAT --to-destination 10.0.0.19
-A OUTPUT -d 127.0.0.11/32 -j DOCKER_OUTPUT
-A POSTROUTING -d 127.0.0.11/32 -j DOCKER_POSTROUTING
-A POSTROUTING -o wg+ -j MASQUERADE
-A POSTROUTING -o eth0 -j MASQUERADE
-A DOCKER_OUTPUT -d 127.0.0.11/32 -p tcp -m tcp --dport 53 -j DNAT --to-destination 127.0.0.11:45181
-A DOCKER_OUTPUT -d 127.0.0.11/32 -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.11:48863
-A DOCKER_POSTROUTING -s 127.0.0.11/32 -p tcp -m tcp --sport 45181 -j SNAT --to-source :53
-A DOCKER_POSTROUTING -s 127.0.0.11/32 -p udp -m udp --sport 48863 -j SNAT --to-source :53
 routes in docker container
 default via 172.150.88.1 dev eth0
10.0.0.19 via 172.150.88.10 dev eth0
10.100.10.0/24 dev wg0 proto kernel scope link src 10.100.10.1
172.150.88.0/24 dev eth0 proto kernel scope link src 172.150.88.10
192.168.1.0/24 via 10.100.10.2 dev wg0
Allowed_IPs = 10.100.10.0/24, 10.0.0.0/24, 192.168.1.0/24, 172.150.88.10/32
Please help, what's wrong? Where can be mistake?

**Comment by KaesDingeling** [comment]
Hi,

i also route from an MicroTik client over the wg-easy container an Subnet (10.0.0.0/16, and others). I settet in the MirkTik the Allowed-IPs to WireguardLAN (10.8.0.0/24), MikroTikLAN (10.0.0.0/16). Then the Mirotik allowes Access from Wireguard to the local subnets.
To route subnets on the wg-easy container then you changed the config on `/etc/wireguard/wg0.conf`. Wg-easy dosn´t support this and override the config when you make changes on the GUI or restart the container.

Here an example of my config:
```
...

# MikroTik publish 10.0.0.0/16 | Keep-Alive on Mikrotik must be > 0 also connection didn´t work
[Peer]
PublicKey = ...
PresharedKey = ...
AllowedIPs = 10.0.0.0/16, 10.8.0.2/32

[Peer]
PublicKey = ...
PresharedKey = ...
AllowedIPs = 10.8.0.3/32

[Peer]
PublicKey = ...
PresharedKey = ...
AllowedIPs = 10.8.0.4/32

...
```

On the client-side of .3 and .4 you add 10.0.0.0/16 to Allowed-IPs, not on server-side. I didn´t add iptable rules. After the change you can apply the config via `wg-quick down wg0 && wg-quick up wg0`.
For me works this, i hope can help you.

I found also an Issue to this Feature: #581
