### ISSUE TITLE
Restrict WebUi to local network only 

### ISSUE THREAD

**Issue by BlaCkMatiK** [wg-easy/wg-easy#633]
Hi ! Sorry i'm a little new in all this but i wanted to know if it's possible to being able to connect to the WebUi only through the VPN (so only inside my local network) and no outside.
If it's possible, how can i achieve this ? 
Thanks in advance ! (Sorry for any mistakes, i'm French)

**Comment by geekifier** [comment]
Assuming you have WireGuard running behind some router/firewall, simply do not open the web UI port externally. Only open the UDP port for WG.

**Comment by NeoSlugman** [comment]
> Hi ! Sorry i'm a little new in all this but i wanted to know if it's possible to being able to connect to the WebUi only through the VPN (so only inside my local network) and no outside. If it's possible, how can i achieve this ? Thanks in advance ! (Sorry for any mistakes, i'm French)

Comme le dit @geekifier : 
Si tu n'exposes pas le port de l'interface sur l'extérieur dans ta config pare-feu, tu n'y auras pas accès autrement que via le tunnel wireguard.
Tu peux le tester en essayant de te connecter avec une machine qui n'est pas dans le réseau wireguard sur le port de la WebUI (51821 par défaut).

**Comment by BlaCkMatiK** [comment]
Merci à vous pour vos réponses. J'utilise ufw (il est activé) mais le port 51821 n'est pas autorisé mais je peux me connecter à la WebUI en 4g sur mon téléphone par exemple.
Je pense que je passe à côté de quelque chose de simple... 😅

**Comment by phplego** [comment]
The easiest way is to bind only for local interface   -p **127.0.0.1**:51821:51821/tcp

```
$ docker run -d \
  --name=wg-easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 127.0.0.1:51821:51821/tcp \                 <<<<<--------------- here is change
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy
```

**Comment by nexus-chebykin** [comment]
> The easiest way is to bind only for local interface -p **127.0.0.1**:51821:51821/tcp
> 
> ```
> $ docker run -d \
>   --name=wg-easy \
>   -e WG_HOST=🚨YOUR_SERVER_IP \
>   -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
>   -v ~/.wg-easy:/etc/wireguard \
>   -p 51820:51820/udp \
>   -p 127.0.0.1:51821:51821/tcp \                 <<<<<--------------- here is the change
>   --cap-add=NET_ADMIN \
>   --cap-add=SYS_MODULE \
>   --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
>   --sysctl="net.ipv4.ip_forward=1" \
>   --restart unless-stopped \
>   weejewel/wg-easy
> ```

In fact if you want to access the Web-UI only if you are connected to the VPN, you can delete this line altogether. Then you can access the UI via the server's Wireguard IP, e.g. 10.8.0.1:51821
