### ISSUE TITLE
Hope the Host field supports domain names

### ISSUE THREAD

**Issue by willisworley** [wg-easy/wg-easy#637]
-e WG_HOST=🚨YOUR_SERVER_IP \
   -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \ 

Hope the Host field supports domain names

**Comment by willisworley** [comment]
and hope support 🚨ipv6

**Comment by henryford** [comment]
could've read about one line further which clearly states that you can use hostnames ("domain names" as you call them) as well. IPv6 currently isn't supported.

**Comment by WeeJeWel** [comment]
It does.
