### ISSUE TITLE
成功自建wireguard后，某台主机连上之后，该台主机立马就断网？

### ISSUE THREAD

**Issue by basaltfiber** [wg-easy/wg-easy#640]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nativu5** [comment]
我猜因为你的 AllowIPs 设置成了 0.0.0.0/0。
