### ISSUE TITLE
Edit the Server Config

### ISSUE THREAD

**Issue by Mar04craft** [wg-easy/wg-easy#641]
Hello, 

I would like to edit the server config, but if I look into It it says:

```
# Note: Do not edit this file directly.
# Your changes will be overwritten!
```

Is it possible to edit the config in any way that it will not be overwritten?
Maybe I am just in the wrong file, im using ~/.wg-easy as it is listed in the Description, is that even the Server Configuration file?

Thanks!

**Comment by Hamsterman** [comment]
You gotta use the parameters of docker run / compose to do this instead.
Like adding WG_POST_UP can overwrite that section.
