### ISSUE TITLE
Revisiting the license

### ISSUE THREAD

**Issue by harishpillay** [wg-easy/wg-easy#649]
I am reviewing the closed issue https://github.com/wg-easy/wg-easy/issues/42 around OSI-approved licenses.

I would like the project to review the license and take one of the OSI-approved ones. Perhaps a AGPL will fit the concerns of the author.

Thanks.

**Comment by WeeJeWel** [comment]
Unfortunately AGPL does not forbid commercial use.

As far as I know there is no OSI license that’s free for personal use but restrictive for commercial use. 

I am trying to prevent a company to bundle this and sell it for profit. They may do so if they have my permission though.

**Comment by peterlewis** [comment]
Thank you for this Issue. This has been on the tips of our tongues in recent days, and posting a reply as reassurance that it has not been disregarded!

Thanks again!

**Comment by harishpillay** [comment]
> Unfortunately AGPL does not forbid commercial use.
> 
> As far as I know there is no OSI license that’s free for personal use but restrictive for commercial use.
> 
> I am trying to prevent a company to bundle this and sell it for profit. They may do so if they have my permission though.

An OSI-approved license does not prevent commercial use. If that is a concern, you might want to explore dual licensing. It might not work unless all those who have contributed to the repo agree to do so.

Harish

**Comment by pheiduck** [comment]
We moved to [CC BY-NC-SA 4.0](https://github.com/wg-easy/wg-easy/blob/master/LICENSE) License which was suggested by the founder @WeeJeWel

**Comment by harishpillay** [comment]
> We moved to [CC BY-NC-SA 4.0](https://github.com/wg-easy/wg-easy/blob/master/LICENSE) License which was suggested by the founder @WeeJeWel

Thank you for the update. The targeted use of CC licenses is for non-software content, but, yes, software can be on a CC license as well. By placing this on a CC BY-NC-SA 4.0 make the code non Free Software from an Open Source Initiative perspective. 

I'd encourage @WeeJeWel to consider dual licensing as an option. Place your code on GPLv3  or AGPLv3 *and* for those who want to commercialise to contact you. By stating the objectives, it becomes clear and obvious. 

Thanks.

**Comment by pheiduck** [comment]
Solved by @peterlewis
