### ISSUE TITLE
Custom WG_PORT ignored in iptable rules

### ISSUE THREAD

**Issue by pawi** [wg-easy/wg-easy#650]
Hi,

I had difficulties getting wg-easy to work and identified my issue with the custom WG_PORT setup I initially tried.

The custom port is ignored in the iptable rules during WG_POST_UP phase. 
I think the port 51820 should be replaced with `${module.exports.WG_PORT}`
https://github.com/wg-easy/wg-easy/blob/642d6d62edb95a96e57b704966b65135f4f3ea94/src/config.js#L23

Kind regards

**Comment by eandersons** [comment]
Well, `WG_PORT` is used in client configuration, it is not used internally inside WireGuard easy container:

> The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.

**Comment by pawi** [comment]
Sorry, I published the custom ports on host and container. By keeping the container port default and only change the host port everything works. Thank You!
