### ISSUE TITLE
Managing firewall/routing within wireguard clients

### ISSUE THREAD

**Issue by NazgulCoder** [wg-easy/wg-easy#651]
**Describe the bug**
Hi, is there a way to manage multiple clients in wg-easy and modify the config for each client?
e.g. I have 2 clients, 1 client (my phone) I want to let it go 0.0.0.0/0 through the VPN. The other client (another phone) I want to let it go through the VPN only towards this subnet 192.168.1.0/24. How is this doable? I know you can configure in ***AllowedIPs = 0.0.0.0/0, ::/0*** but this applies from the peers, and not from the VPN server, I believe it's not a safe measure.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] any
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung
 - OS: [e.g. iOS8.1] Android 13
 - Browser [e.g. stock browser, safari] any
 - Version [e.g. 22] N/A

**Additional context**
Thanks for everybody who wants to clarify this to me

**Comment by rudasn** [comment]
Maybe have the AllowedIPs setting of client 2 to just be the cidr you want traffic to go though (and back), ie`AllowedIPs = 192.168.1.0/24`.

That way only traffic within that range will go to the vpn peer.

**Comment by NazgulCoder** [comment]
> Maybe have the AllowedIPs setting of client 2 to just be the cidr you want traffic to go though (and back), ie`AllowedIPs = 192.168.1.0/24`.
> 
> That way only traffic within that range will go to the vpn peer.

ok but i can put it clientside only, if i want to distribute the certificate to third parties they can easily remove those "limits"

**Comment by eandersons** [comment]
[Discussions](/wg-easy/wg-easy/discussions) is the right place for questions like these.

A solution possibly could be custom iptables rules (which can defined with the environment variable `WG_POST_UP`), but I am not really sure about it.
You will have to explore iptables to see if the desired outcome can be achieved with its rules.

**Comment by rudasn** [comment]
> > Maybe have the AllowedIPs setting of client 2 to just be the cidr you want traffic to go though (and back), ie`AllowedIPs = 192.168.1.0/24`.
> > That way only traffic within that range will go to the vpn peer.
> 
> ok but i can put it clientside only, if i want to distribute the certificate to third parties they can easily remove those "limits"

Right, they can. So to "fix" that, on the VPN configuration, on device's 2 [Peer] section, the `AllowedIPs` setting should just be `192.168.1.0/24`, meaning that for device 2 the VPN interface will only route (send **and** receive) traffic that is destined within that range.

**Comment by NazgulCoder** [comment]
> > > Maybe have the AllowedIPs setting of client 2 to just be the cidr you want traffic to go though (and back), ie`AllowedIPs = 192.168.1.0/24`.
> > > That way only traffic within that range will go to the vpn peer.
> > 
> > 
> > ok but i can put it clientside only, if i want to distribute the certificate to third parties they can easily remove those "limits"
> 
> Right, they can. So to "fix" that, on the VPN configuration, on device's 2 [Peer] section, the `AllowedIPs` setting should just be `192.168.1.0/24`, meaning that for device 2 the VPN interface will only route (send **and** receive) traffic that is destined within that range.

However, editing the wg0.conf file it's a risk since any new client added will result in configuration overwritten...

I'll check the WG_POST_UP like others suggested
