### ISSUE TITLE
change ip adress, can't find config file

### ISSUE THREAD

**Issue by Jumbo125** [wg-easy/wg-easy#653]
Hello 
i use your create work since a few months on my odroid, armbian.

i needed to change my server ip-adress for a few days. Since i changed the server ip-adress i can'T conntect the server via vpn.
so i think, i need to change the ip-adress in the config. 
But i don't find any config file. in the wg0.conf and *.json file isn't the old ip-adress.

i have some clients in use, so i don't want to lose this settings

The directory etc/wireguard not exist....

can you help me, please.

**Comment by wial88** [comment]
Hello, 
since I encountered the same issue a few days ago... 
Have you already updated the port forwarding settings on your router to the new server IP address? 
I initially forgot to do this myself.
i forgot this first.

**Comment by freetushkan** [comment]
It's a Docker, so you just need to stop and remove current container, then run the new one again with same parameters, except the new server address.

**Comment by Jumbo125** [comment]
> It's a Docker, so you just need to stop and remove current container, then run the new one again with same parameters, except the new server address.

okay. thank you.
how can i stop a "docker"????
can i list all current docker services?
how can i set or remove a docker from the autorun?

**Comment by Jumbo125** [comment]
okay list all docker container can do with: sudo docker ps

**Comment by freetushkan** [comment]
To list your containers do:
docker ps

To sop and remove:
docker stop <container_name>
docker rm <container_name>

Then repeat command from main page.
