### ISSUE TITLE
Cannot access dockers on Br0 [Unraid]

### ISSUE THREAD

**Issue by ImNoahDev** [wg-easy/wg-easy#655]
Hi,

I am running Wg-Easy on Unraid. I have it set up and I am able to access any dockers on the bridge or host interface and I can access the internet. My issue is that I cannot access any docker containers on custom networks (br0). Do I need to set up a static route on my router. How do I fix this?

Thank you!

**Comment by rpanizzon** [comment]
Check your iptables in the container using  “iptables -L -v -t nat”.
My guess is that the Masquerade postroute has eth0 as the network interface, not your bridge (br0). You may need to use the environment variable WG_POST_UP to overcome this as WG-DEVICE does not appear to work.
