### ISSUE TITLE
Custom wg0.conf content - Is This Possible?

### ISSUE THREAD

**Issue by voyager529** [wg-easy/wg-easy#656]
Hey there, friends!

My goal is to implement 2FA on Wireguard connections. I did some searching, and found this tool: https://tunsafe.com/user-guide/2f .

It looks like it will fulfill my needs. However, I've hit a bit of a snag in connecting it to WG-Easy. This probably has a bit more to do with me being a docker n00b than the project, but in order to integrate TunSafe, I have to add a line to the server config:

_[Peer]
RequireToken = totp-sha1:SECRET,digits=6,period=30,precision=15_

And, of course, editing wg0.conf is pointless because it gets overwritten...but adding the line as an ENV variable doesn't seem to have the desired effect...it just causes the container to fail to load. Editing wg0.json wasn't a solution, either.

So...how do I add this config to a wg-easy container in a way that it won't be overwritten?

Thank you!

**Comment by tarruda** [comment]
The code which generates the config is straightforward: https://github.com/wg-easy/wg-easy/blob/master/src/lib/WireGuard.js#L91 , so it would be easy adding support for an extra env var which allows custom config (eg `WG_EXTRA_CONFIG`) which is appended to the end of the config string.

I also needed to add some extra config and was considering to send a PR, but it seems this project is no longer maintained. Even security updates from months ago are not merged: https://github.com/wg-easy/wg-easy/pull/588
