### ISSUE TITLE
Impossible to espose ip addresses to the rest of docker

### ISSUE THREAD

**Issue by ggvick** [wg-easy/wg-easy#661]
I am trying to expose the vpn ips to the rest of the network and not just use the one container ip.

**Expected behavior**
The ips that are shown ex: "10.8.0.2" would be the one used for each individual client instead of the container ip address for each and every client.

**Desktop (please complete the following information):**
 - OS: ubuntu jammy

**Comment by peterlewis** [comment]
Hi there! Thanks for this issue. Please do feel free to submit a PR if you feel that this is an area that could benefit from development though, as WireGuard operates at layer 3 of the OSI I'm not sure how straightforward this would be,
