### ISSUE TITLE
No access to anything other then the Server

### ISSUE THREAD

**Issue by JasonB73** [wg-easy/wg-easy#662]
Hi,
     I have a fresh install of PhotonOS-4 in ESXi 7 ( kernel VER. 5.10.200-2.ph4-rt)

Allow promiscuous mode Yes, Allow forged transmits Yes, Allow MAC changes Yes on the ESXi host.

All of my other VM's running Docker are fine. using a MacvLan or bridge into my Hosted four subnets.

Whats been done.
EdgeMax X router > port forward 
51820 UDP to Docker wg-easy server using ISP-IP: Address
51821 TCP using DNS-Name Forwarding to My NPM Docker's IP on a different host & server in the subnet. 
NPM sslcert for WebGUI on CNAME.

What works > WebGUI from anywhere using https://CNAME.com address.
     
( Phone Cell & Windows 10 install ) I can make a connection and I can ping the wg-easy docker ip 10.8.0.1. 

What I can't do > ping device A to B or B to A.
I see traffic one way only in the WebGUI. 

Docker-Compose yml
------------------------------
version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=(ISP Static IP)
      - PASSWORD=(Defined)
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.1.10.1
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=10.1.10.0/24
      - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

For the above PRE up and down they are default.

Because of this issue I also created a fresh ubuntu 20.04 server using the same step as my PhotoOS-4 server and it has the same issue.
Am I forgetting a step?
I've only been using dockers for the past year and I'm still Noobish.
I can't use ubuntu at work because of the snap security holes.
I've been in I.T. for years now but that's not helping my Docker knowledge at all.  

Any insight to this would be great.
Thanks for creating this container !!

**Comment by idf3da** [comment]
Hi. I have similar issue as well. Have you managed to resolve it?

**Comment by idf3da** [comment]
If anyone has this issue set the keepalive to 24 sec since all routers reset the connections behind NAT after 25 sec.
Hope it helps someone. 🫡

**Comment by JasonB73** [comment]
I had been using esxi7, not sure what my issues was in it.
I ended up moving over to one of my PI's and it worked just fine.
Only thing to workout now is the vpn sees everything on both subnets.

I have the route coming from a public router into the PI which has two nics then it sees the corp / production devices. 

I need to lock it down to just a few devices. not sure yet if WG_ALLOWED_IPS=device1,device2,device3 etc will work.

Thanks
