### ISSUE TITLE
docker-compose ImportError 'ContextAPI'

### ISSUE THREAD

**Issue by Nymax77** [wg-easy/wg-easy#670]
**Describe the bug**
docker-compose error, can't import ContextAPI 

**To Reproduce**
0. freshly installed raspberry system.
1. follow the tutorial on https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL#nginxserverswg-easyconf until "Save these files, edit the variables marked with and run docker-compose up -d in the same directory."
2. go to wg-easy folder
3. cmd "docker-compose up -d"
4. Error: "ImportError: cannot import name 'ContextAPI' from 'docker' (/home/rpi/.local/lib/python3.9/site-packages/docker/__init__.py)" 

**Expected behavior**
Docker compose builds software.

**Desktop (please complete the following information):**
 - OS: Raspberry Pi Os Lite

**Additional context**
- Possilby version conflict in python modules?
**Describe the bug**
docker-compose error, can't import ContextAPI 

**To Reproduce**
0. freshly installed raspberry system.
1. follow the tutorial on https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL#nginxserverswg-easyconf until "Save these files, edit the variables marked with and run docker-compose up -d in the same directory."
2. go to wg-easy folder
3. cmd "docker-compose up -d"
4. Error: "ImportError: cannot import name 'ContextAPI' from 'docker' (/home/rpi/.local/lib/python3.9/site-packages/docker/__init__.py)" 

**Expected behavior**
Docker compose builds software.

**Desktop (please complete the following information):**
 - OS: Raspberry Pi Os Lite

**Additional context**
- Possilby version conflict in python modules?

**Comment by eandersons** [comment]
Basically you are on your own as you are following an user provided Wiki article, and this issue is not related to WireGuard Easy because the cause is in your setup.

Web search engines always are your friends. A quick search led to this issue: https://github.com/docker/compose/issues/8366. Does its comment resolve your issue?

**Comment by Nymax77** [comment]
Thanks for your answer. 
The problem was indeed the version of docker. But not, that it was too old and docker-py was used.
The problem was, that in docker version 7.0.0, other than previous versions, a function no longer expected the ssl_version argument. 

User [marcsc13](https://github.com/marcsc13) described it in [docker-py](https://github.com/docker/docker-py/issues/3194 ) very good:

> In compose/cli/docker_client.py on line 124 the call of kwargs_from_env expects the function signature to be `kwargs_from_env(environment=None, ssl_version=None)` but it was changed to
> 
> `def kwargs_from_env(environment=None):`
> 
> (See file docker/utils/utils.py line 344)

I could resolve the issue by installing docker version 6.1.3, like recommended [here](https://github.com/docker/docker-py/issues/3194#issuecomment-1848402039). I did this by 
```
pip uninstall docker 
pip install docker==6.1.3
```

**Comment by peterlewis** [comment]
Glad you got your issue sorted! 😀
