### ISSUE TITLE
WG_PORT option does not work

### ISSUE THREAD

**Issue by rootsnet** [wg-easy/wg-easy#672]
**Describe the bug**
The WG_PORT option does not work.

**To Reproduce**
1. set WG_PORT option 
2. create container
3. check config file in container as below.
$ cat wg0.conf
...
ListenPort = 51820
PreUp =
PostUp =  ... 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
...

**Expected behavior**
The port values have to be changed as configured WG_PORT value.

**Comment by eandersons** [comment]
Did you even read what this environment variable is supposed to do?

> The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.

Also there is already a lot of similar [issues](/wg-easy/wg-easy/issues?q=is%3Aissue+WG_PORT) and related [pull requests](/wg-easy/wg-easy/pulls?q=is%3Apr+WG_PORT), you should search before creating a new issue to make sure that it is not already adressed.

**Comment by rootsnet** [comment]
I think I had a misunderstanding about port options.
Thank you for your reply.
