### ISSUE TITLE
ENDPOINTIP

### ISSUE THREAD

**Issue by unknown1818** [wg-easy/wg-easy#673]
Hi,

My configuration looks like 

Client (wg-easy - NAT) -> Server

How i can add endpointip to client side because after restart its deleted

Or this wg-easy is only server side?

wg0.conf is not persistent but how i can provide endpointip in .json file?

**Comment by eandersons** [comment]
Seems that you started your container without persistent volume.

**Comment by unknown1818** [comment]
> Seems that you started your container without persistent volume.

Its persistent folder but wg-easy replacing cutom wg0.conf after reboot

**Comment by eandersons** [comment]
That, if I am not mistaken, is by design, because all the information is stored in and restored from `wg0.json`.

**Comment by peterlewis** [comment]
Closing as not an issue per-se. if this is an ongoing concern please do raise in [Discussions](https://github.com/wg-easy/wg-easy/discussions) and we will be happy to help!

**Comment by madswaord** [comment]
> That, if I am not mistaken, is by design, because clients information is stored in and restored from `wg0.json`.
> 
> > wg0.conf is not persistent but how i can provide endpointip in .json file?
> 
> Do you mean endpoint address in the downloaded configuration?
> 
> ```
> [Interface]
> ...
> 
> [Peer]
> ...
> Endpoint = wireguard.example.org:51820  # This?
> ```
> 
> If so, this value (excluding port) is controlled by the environment variable `WG_HOST`. It will not affect those clients that have created tunnels before changing value of `WG_HOST` though.

i think he would like to use the wg-easy side as client, and try to connect peer as server, seems like the wg-easy docker can only be the server side. the "WG_HOST" was for the peers to connect wg-easy only, but what if we need to visit peer's lan network, there is a endpoint for peer side.
