### ISSUE TITLE
Can't install it in clean ubuntu 22.04.3 server

### ISSUE THREAD

**Issue by argoodaki** [wg-easy/wg-easy#676]
Hi, I have rented a new vm in hetzner with ubuntu 22.04.3.
I have installed docker as I always do:
`curl -fsSL https://get.docker.com -o get-docker.sh
chmod +x get-docker.sh
sh get-docker.sh`

then i do from terminal logged in as root:
docker run -d \
  --name=wg-easy \
  -e WG_HOST=my.server.ip. \
  -e PASSWORD=apassword \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy

and i get back: Unable to find image 'pull:latest' locally
docker: Error response from daemon: pull access denied for pull, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

but if i do: docker pull weejewel/wg-easy
it actually pulls the image, i have logged in to docker hub even though this wasn't needed.
After I pull the image manual, I run again the initial command but i get the same error.
I have done two times reinstall of the vm in case i did something wrong.
I use the install method for over 2 years now without problems, just now with this VM.
Any ideas?

**Comment by eandersons** [comment]
It seems that your multi-line `docker run` command is missing backslashes. Take a closer look at the `docker run` command that is provided in the [description](/wg-easy/wg-easy#2-run-wireguard-easy).

**Comment by peterlewis** [comment]
Images have now been moved from Docker to GitHub Container Registry. Please pull from `ghcr.io/wg-easy/wg-easy` instead. Thanks!
