### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by webair-studio** [wg-easy/wg-easy#701]
After the update steps specified [here](https://github.com/wg-easy/wg-easy#updating), will user profiles be saved?

**Comment by eandersons** [comment]
This is a question, not an issue, therefore it should be asked in [discussions](/wg-easy/wg-easy/discussions).

**Comment by peterlewis** [comment]
Thanks @eandersons, yes indeed Discussions would be best place for this. The answer is yes, it *should* retain all configs, so long as you haven't gone too-far off-piste with your volume config.
