### ISSUE TITLE
Date and volume of consumption

### ISSUE THREAD

**Issue by masoudnariman** [wg-easy/wg-easy#704]
Please add expiration date and volume limit to each user

**Comment by peterlewis** [comment]
Hey! Thank you for the suggestion. I would say "please feel free to submit a PR" but I feel that this would be somewhat at odds with the KISS principal that we are aiming to continue with wg-easy at this time, i.e. a feature that is of benefit to the minority. Paging @pheiduck and @WeeJeWel incase they feel differently about it.

If you're; happy to develop this feature then would love to see the results, but it isn't something that is likely to feature on the wg-easy roadmap, as far as I can see...

Thanks!

Peter :)
