### ISSUE TITLE
Allow for internal container port and wg interface to be defined in variables

### ISSUE THREAD

**Issue by centralhardware** [wg-easy/wg-easy#713]

**Comment by centralhardware** [comment]
https://github.com/wg-easy/wg-easy/issues/692#issuecomment-1872491105

**Comment by centralhardware** [comment]
Is it any plans to include custom wire guard interface in v10?

**Comment by peterlewis** [comment]
Hey @centralhardware. This will not make it into the v10 release. We understand the appetite for this feature and need to consider the most appropriate way to allow users to set both the facing port and the container port in the most appropriate manner. Something for us to look to progress in nightly and look for inclusion in a the v11 release, maybe.
