### ISSUE TITLE
Getting "not Logged in" message when using SWAG reverse proxy

### ISSUE THREAD

**Issue by Bajiio** [wg-easy/wg-easy#716]
Hello,
I'm currently trying to use SWAG reverse proxy to access wg-easy web-dashboard but I always end up with and error message "not Logged in" and I can't find in the wg-easy code where it could came from. I can still access without any problem the interface if I don't go through the reverse-proxy, and the "not Logged in" message doesn't seems to be due to a gateway error from the reverse proxy. So I conclude it could came from a header or a cookie not correctly send but cannot figure out much more. Does anyone already had this kind of problem ?

Error message:
![image](https://github.com/wg-easy/wg-easy/assets/60874928/25840444-676e-4644-b48a-0542f8bec5f0)

Reverse-proxy conf:
![image](https://github.com/wg-easy/wg-easy/assets/60874928/ee180b64-8c56-4eec-a0d0-6eb7766a8c74)

Proof that both machine are on same network:
wg-easy:
![image](https://github.com/wg-easy/wg-easy/assets/60874928/9b5ac8cd-2299-4c01-b047-1b328aa92ce1)
SWAG:
![image](https://github.com/wg-easy/wg-easy/assets/60874928/118f32b8-63b9-4c71-977e-ce0dfb194e5d)

wg-easy dockerfile
![image](https://github.com/wg-easy/wg-easy/assets/60874928/e334f879-7e2e-4eb4-9027-c6398e206952)

If I can bring any additional information, feel free to ask.
Thanks in advance for your help :)

**Comment by Bajiio** [comment]
After comparing few videos, It seems like adding '/' as the end of proxy_pass line resolve this issue (see below). 
But now another problem shows up, every request for wg-easy website end up being the HTML code (js ressource getting replaced by html code). I think it's now more of a proxy problem now, but if anyone has a solution I will be glad to read it.

Fix : 
![image](https://github.com/wg-easy/wg-easy/assets/60874928/d4cd8ecc-fd09-4ead-8cc6-21c424644af8)
New error:
![image](https://github.com/wg-easy/wg-easy/assets/60874928/29878935-0073-4bb5-a2b3-c3b2534eee2c)

**Comment by peterlewis** [comment]
Sounds like a `content-type` issue to me. Try:

`add_header Content-Type: text/html; charset=utf-8`

**Comment by Bajiio** [comment]
> Sounds like a `content-type` issue to me. Try:
> 
> `add_header Content-Type: text/html; charset=utf-8`

Do you have any links or source for this fix ? It didnt' work for me but maybe I did it wrong so I would like to check. I tried with add_header and proxy_set_header. Here is my full reverse config.
![image](https://github.com/wg-easy/wg-easy/assets/60874928/3fa6041a-79e8-4c92-803a-2391caf3c0b9)

Do you know if webapp of wg-easy has access logs so I can check if the header is correctly added ?
