### ISSUE TITLE
Cant access to vpn server, loos internet on vpn client

### ISSUE THREAD

**Issue by Jumbo125** [wg-easy/wg-easy#717]
Hy
I use this great work for my network at home. Works great.

But i can't install it for my brother.
He use the same rasperry and os for the vpn server. 
i installed docker and can start the server.

The difference between me and my brother:

We have different routers. 
He use the MR 600 TP-Link Router

His Router use the ip range: 192.168.1.x
My Router use the ip range: 10.0.0.x

I can setup the dynudns in my router
He need to solve this with dynuddns api

The problem:
when i try to connect to his vpn, i loos my internet on the vpn client and the vpnc client shows me handsahke out of time

**Comment by peterlewis** [comment]
Sorry to hear you're having issues. From what you've posted it sounds like an environment as opposed to issue with wg-easy. I'm going to close this as it's not really an Issue, but please feel free to re-raise in [Discussions](https://github.com/wg-easy/wg-easy/discussions)!

**Comment by Jumbo125** [comment]
Okay 
I will do this
Thank you
