### ISSUE TITLE
[request] make a github release

### ISSUE THREAD

**Issue by jdeath** [wg-easy/wg-easy#746]
I really like wgeasy. I packaged a homeassistant addon based on this, so other home assistant users can easily use it without docker expertise. Is there anyway to make a github release when you build a new named release docker image? That will help my autodownloader keep up with releases to ensure the addon is not out of date.

**Comment by peterlewis** [comment]
That makes sense, and thanks for your addon! This should be doable with a simple GitHub action. I’ll just get this seconded by @pheiduck before making that.

**Comment by pheiduck** [comment]
You can use the Package which will be deployed when a Release is published to our `production` branch:
https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy/165495787?tag=10

**Comment by jdeath** [comment]
Yes, I use that package. The autodownloader code I use, based on https://github.com/dvershinin/lastversion requires a github or dockerhub tag release to know if a new package is available. That is not available since you moved image locations.

**Comment by pheiduck** [comment]
Okay, then maybe we need to find a way to publish a github release.
I have some knowledge to do this, but not the time at the moment.

**Comment by jdeath** [comment]
Thanks for considering it. The autodownloader addon was updated to handle this case, so no need to make releases for this purpose.
