### ISSUE TITLE
[Request] Add ability to change Allowed IPs per peer for Full tunnel and split tunnel peers

### ISSUE THREAD

**Issue by ghTravis** [wg-easy/wg-easy#758]
I'd really like the ability to create two peers, one for split tunnel just for DNS and another peer for full tunnel in the case where I want to push all my traffic through wireguard. In the current implementation I'd have to run two different wg-easy containers for the different AllowedIPs config value.

There was a similar request #656 that never got any response. Hoping to see if this is on anyone radar to implement.

Thanks!

**Comment by peterlewis** [comment]
https://github.com/wg-easy/wg-easy/pull/737
