### ISSUE TITLE
Can wg-easy be installed on a machine without iptables installed without using docker?

### ISSUE THREAD

**Issue by doyoman** [wg-easy/wg-easy#760]
**Screenshots**
![a](https://github.com/wg-easy/wg-easy/assets/63859866/aee06127-bf1b-4ddf-a9ff-a31f7db3cc85)

I tried to use wg-easy through systemd on an intranet machine without a firewall, but it failed to start because iptables was missing. Is it possible to start wg-easy without using iptables?

**Comment by pheiduck** [comment]
Sure see: https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-without-Docker
