### ISSUE TITLE
Command line installation, the listening port cannot be modified.

### ISSUE THREAD

**Issue by doyoman** [wg-easy/wg-easy#761]
Because this line hardcodes the port, the listening port specified in the systemd file does not take effect. This should be a bug.

wg-easy/src/lib/WireGuard.js

![b](https://github.com/wg-easy/wg-easy/assets/63859866/709a188b-1026-4fcd-a69d-6449b43c0261)

**Comment by centralhardware** [comment]
https://github.com/wg-easy/wg-easy/issues/713

**Comment by peterlewis** [comment]
> https://github.com/wg-easy/wg-easy/issues/713

👆
