### ISSUE TITLE
Iphone safari wrong markup 

### ISSUE THREAD

**Issue by centralhardware** [wg-easy/wg-easy#762]
**Describe the bug**

incorrect markup on smartphone

**To Reproduce**
1. Open wg-easy from smartphone

**Expected behavior**

the site fits the screen size

**Screenshots**
![image](https://github.com/wg-easy/wg-easy/assets/26829359/7a011afb-d725-4029-8e93-7a3eaa9c8d28)
![image](https://github.com/wg-easy/wg-easy/assets/26829359/cf59b3fd-667c-4fd9-8a05-57b66424da34)

**Smartphone (please complete the following information):**
 - Device: Iphone 13
 - OS: ios 17.2.1
 - Browser: Safari

nginx proxy manager: latest nightly docker image.

**Comment by peterlewis** [comment]
Yup default zoom in iOS is not perfect. Thank you. This needs fixing.

**Comment by NISHANT210106** [comment]
First of all, iOS 15.2 has been released, so you'll want to back up your iPhone, then update:

[Update your iPhone, iPad, or iPod touch](https://support.apple.com/HT204204)



If you're still having the issue, restart your iPhone. A restart can resolve unexpected issues:

[Restart your iPhone](https://support.apple.com/HT201559)



Then, check your Safari settings:

[Customize your Safari settings on iPhone](https://support.apple.com/guide/iphone/customize-your-safari-settings-iphb3100d149/15.0/ios/15.0)



You'll also want to check for any Accessibility settings which may be inadvertently enabled:

[Get started with accessibility features on iPhone](https://support.apple.com/guide/iphone/get-started-with-accessibility-features-iph3e2e4367/15.0/ios/15.0)

**Comment by centralhardware** [comment]
Am, I think it's impossible for me to downgrade to iOS 15.2 right now

**Comment by centralhardware** [comment]
Whatever no one will do this even if it's fix problem

**Comment by pheiduck** [comment]
@centralhardware See: https://github.com/wg-easy/wg-easy/pull/319
It's still in WIP due slow response from contributer.

**Comment by suxscribe** [comment]
@pheiduck this is almost fixed in `feat-stats` branch, needs some minor tuning

**Comment by pheiduck** [comment]
@suxscribe thanks for your hint #873 will close this issue.

**Comment by centralhardware** [comment]
all ok now, thanks
