### ISSUE TITLE
Download configuration file as .conf file

### ISSUE THREAD

**Issue by navilg** [wg-easy/wg-easy#796]
**Describe the bug**
Currently when we download configuration file of a peer, It downloads as .txt file. But to import the configuration using wireguard app, It needs either .conf or .zip file.

**To Reproduce**

**Expected behavior**
When we download a configuration file, It should be downloaded as .conf file which is compatible extension for wireguard.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows, Linux, Android and iOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eandersons** [comment]
Similar issue: #417 

This seems to be a browser specific problem, but since you did not care to provide detailed information, it is hard to tell if this is the case.

**Comment by navilg** [comment]
Oh. I thought it application issue and cared not to share browser details. Here are more details

Desktop (please complete the following information):

    OS: Ubuntu 23.04
    Browser [e.g. chrome, safari]: Firefox
    Version [e.g. 22]: 122.0

Smartphone (please complete the following information):

    Device: [e.g. iPhone6]: Samsung
    OS: [e.g. iOS8.1]: Android 14
    Browser [e.g. stock browser, safari]: Firefox
    Version [e.g. 22]: 122.0.1

**Comment by eandersons** [comment]
Yes, this seems to be the same issue as in #417.

For me on Arch Linux peer configuration file is downloaded with correct file name with both Firefox (122.0) and Firefox Developer Edition (123.0b5), but not with Fennec (122.0.0; based on Firefox for Android) on Android phone.

As I mentioned in #417:

> Downloaded file's name is determined from the header [`Content-Disposition`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) which [WireGuard Easy sends](https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/lib/Server.js#L122) (for example: `Content-Disposition: attachment; filename="client-name.conf"`), but seems like Firefox on mobile overwrites the extension [..]

WireGuard Easy sets the header `Content-Disposition` with `peer-name.conf` in it:

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/lib/Server.js#L122

Response in Fennec also contains `peer-name.conf`:

```
content-disposition: attachment; filename="peer-name.conf"
```

but Fennec (Firefox for Android) downloads the configuration file as `peer-name.txt`.

I have no idea why this happens, but this seems to be an issue specifically with Firefox for Android.
Maybe someone with more knowledge could chip in.
Maybe an issue should be filed on Bugzilla.

Does the same happens for you also with Firefox on desktop?

**Comment by navilg** [comment]
> Does the same happens for you also with Firefox on desktop?

I think I mixed up. Just tested on firefox browser on desktop and file extension looks good there. Sorry for  that. This happen in firefox on android.
