### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by elchmartin** [wg-easy/wg-easy#80]
hi!
I just tried to set this up on a fresh ubuntu-VPS-machine, sticking to the guide.
my Ubuntu-Version ist 20.04.3 LTS, kernel is 5.4.0-88-generic.

When running docker-compose (after filling in my host and password) I get:
`root@localhost:~/wg-easy# docker-compose up --detach
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/`

I now changede the version in the docker-compose to 3.3 and it runs. but sould I actually do that?

**Comment by benisai** [comment]
Change the version to 3.3 and it works.

**Comment by bluepuma77** [comment]
Interesting to see that on Debian Bullseye 
```
sudo apt-get install docker-compose
```
does not seem to install the latest version of compose
