### ISSUE TITLE
Add the ability to adjust/confine certain clients to only specific subnets

### ISSUE THREAD

**Issue by K1WIZ** [wg-easy/wg-easy#801]
I have a use case for narrowing the scope of what some clients can access.   By default, the behavior is a full tunnel for all clients.   I want to be able to click on a client and alter the config (like an advanced button maybe?) so that on a per-client basis, I can restrict routing of only specific subnets only.   

This is useful for instances where I only want to provide specific access to say services on 10.12.2.0/24   but not other subnets on the network.   Also in such case, this client would essentially operate as a split tunnel, and only route traffic for 10.12.2.0/24.

**Comment by peterlewis** [comment]
#737
