### ISSUE TITLE
After upgrading the non-container version of wg-easy, I found that the page still prompts that it has not been upgraded.

### ISSUE THREAD

**Issue by maojianyou** [wg-easy/wg-easy#803]
The partial upgrade operations are as follows, with the configuration modification part omitted.

```
mv /app /app_20240201
mv /node_modules /node_modules_20240201

cd /opt/
git clone https://github.com/WeeJeWel/wg-easy
cd /wg-easy/
cd /opt/wg-easy/
cp -rp src /app
cd /app
npm ci --production
cp -r node_modules ..

Configuration omitted

systemctl restart wg-easy.service
```

The final notification remains unsuccessful
![image](https://github.com/wg-easy/wg-easy/assets/55315920/bc9dd097-4271-47a2-a809-c0ad5ddf31ef)

**Comment by eandersons** [comment]
What is shown in browser's console?
There should be printed current and latest release numbers:

```
Current Release: 10
Latest Release: 10
```

The latest release's number is retrieved from <https://wg-easy.github.io/wg-easy/changelog.json>: 

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/www/js/app.js#L290-L302

and the installed version is retrieved from `src/package.json`:

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/www/js/app.js#L289

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/www/js/api.js#L32-L37

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/lib/Server.js#L39-L41

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/config.js#L3-L5

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/package.json#L2

Is the release number in `/app/package.json` 10 or is it something else?

**Comment by Fastidious** [comment]
Experiencing this same issue while using Docker.

**Comment by eandersons** [comment]
@Fastidious, your issue is different. See #788 for solution.
