### ISSUE TITLE
How do I perform container updates? Is it possible to specify it better?

### ISSUE THREAD

**Issue by tigernero79** [wg-easy/wg-easy#809]
I installed casaos on a zimaboard on an ubuntu server 24.0.3 LTS system and when I launch the container it notifies me to update nodejs

how can I update?

Is it possible to have a guide on how to carry out upgrades on this container or in general how to do it? Thank you

![Senza titolo](https://github.com/wg-easy/wg-easy/assets/35575744/6034bb12-d100-42f8-8bbe-77f53e91f62e)

**In the readme you specify like this:**

Updating
To update to the latest version, simply run:

```
docker stop wg-easy
docker rm wg-easy
docker pull ghcr.io/wg-easy/wg-easy
And then run the docker run -d \ ... command above again.
```

what does it mean: And then run the docker run -d \ ... command above again.

What commands should be given to get the container with the updated jnode back or in general for future updates?

I tried to launch this command but then nothing starts up as a container on the OS

`sudo docker run -d --name=wg-easy -e WG_HOST=mio ip -e PASSWORD=mypsw  -v ~/.wg-easy:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart unless-stopped ghcr.io/wg-easy/wg-easy`

**Comment by eandersons** [comment]
> Is it possible to have a guide on how to carry out upgrades on this container or in general how to do it?

```shell
docker stop wg-easy
docker rm wg-easy
docker pull ghcr.io/wg-easy/wg-easy
docker run -d \
  {full `docker run` command from the example above in the same page}
```

> what does it mean: And then run the docker run -d \ ... command above again.

It refers to the `docker run` example that can be found in the same page:

```shell
$ docker run -d \
  --name=wg-easy \
  -e LANG=de \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy
```

> nothing starts up as a container on the OS

How did you came to that conclusion?

What does the following commands output:

- `docker container --all | grep wg-easy`;
- `docker container logs wg-easy`?

**Comment by tigernero79** [comment]
the second command gives me this info after installing wireguard inside casaos. and it notifies me to update nodejs, how should I proceed from the terminal?

tiger@zimaserver:~$ sudo docker container logs wg-easy
2024-02-03T10:29:38.174Z Server Listening on http://0.0.0.0:51821
2024-02-03T10:29:38.186Z WireGuard Loading configuration...
2024-02-03T10:29:38.205Z WireGuard Configuration loaded.
2024-02-03T10:29:38.206Z WireGuard Config saving...
2024-02-03T10:29:38.214Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
$ wg syncconf wg0 <(wg-quick strip wg0)
2024-02-03T10:29:38.521Z WireGuard Config syncing...
2024-02-03T10:29:38.618Z WireGuard Config synced.
2024-02-03T10:29:42.508Z Server New Session: RXAhxybd_52JVhv4cIKAXmDaAzKluIlq

**Comment by eandersons** [comment]
> the first command tells me I don't know the --all parameter
Sorry, I omitted `ls` - the correct command is `docker container ls --all`.

**Comment by eandersons** [comment]
So you have WireGuard Easy container that runs on `weejewel/wg-easy:7` not on `ghcr.io/wg-easy/wg-easy` (the latter contains the updated Node.js). This most probably means that you did not stop and remove container `wg-easy` before running `docker run` command.

Did you run the following commands before `docker run`:

```shell
docker stop wg-easy
docker rm wg-easy
docker pull ghcr.io/wg-easy/wg-easy
```
?

**Comment by tigernero79** [comment]
yes I executed those commands first and then I gave

`sudo docker run -d --name=wg-easy -e WG_HOST=eolotiger.duckdns.org -e PASSWORD=Roloc79@ -v ~/.wg-easy:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart unless-stopped ghcr.io/wg-easy/wg-easy`

**Comment by tigernero79** [comment]
this with the command

```
docker stop wg-easy
docker rm wg-easy
docker pull ghcr.io/wg-easy/wg-easy
```

![image](https://github.com/wg-easy/wg-easy/assets/35575744/fb8c93b3-4ef8-40bf-9644-d059b7cc7e58)

this with the command

`sudo docker run -d --name=wg-easy -e WG_HOST=eolotiger.duckdns.org -e PASSWORD=Roloc79@ -v ~/.wg-easy:/etc/wireguard -p 51820:51820/udp -p 51821:51821/tcp --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl="net.ipv4.conf.all.src_valid_mark=1" --sysctl="net.ipv4.ip_forward=1" --restart unless-stopped ghcr.io/wg-easy/wg-easy`

![image](https://github.com/wg-easy/wg-easy/assets/35575744/4b0ff9d5-2143-47d5-af29-f57a8fac4e55)

finally I refresh the casaos page and I get this

![image](https://github.com/wg-easy/wg-easy/assets/35575744/fb9bea43-e40e-46d9-af8e-133cde8b6187)

wireguard to rebuild, which I don't know how to do

**Comment by eandersons** [comment]
Well, how did you set up WireGuard Easy before you tried to upgrade it?

**Comment by tigernero79** [comment]
directly from casaos from here.

![image](https://github.com/wg-easy/wg-easy/assets/35575744/086060aa-ad0b-4cfe-b5b5-2e6250072d1d)

![image](https://github.com/wg-easy/wg-easy/assets/35575744/c01a6b98-3da7-4569-b78f-e241046e08da)

**Comment by eandersons** [comment]
Then CasaOS most probably is using an outdated image.

I have no experience with CasaOS, so this is as much as I can help, and you are on your own, unless someone else has similar setup and has successfully upgraded WireGuard Easy and is willing to share.

Maybe the following resources will help you: 

- <https://wiki.casaos.io/en/guides/manually-update-compose-app-with-latest-tag>;
- <https://www.reddit.com/r/CasaOS/comments/yavfvx/comment/jbmluag/>.

**Comment by tigernero79** [comment]
Thank you for everything, but especially for your time.

CASAOS also allows you to import your own yaml file or write your own script.

So all I had to do was save the yaml file that they had in their reposity and change the path of the image.

and the problem was solved.

I preferred it this way because they had more options and the Italian language was also set. so I didn't modify their official yaml path but created a container with specifications taken from you yaml files and put in their data fed to casaos and everything is ok. my mistake was believing that they used the same image as you, I hadn't noticed the different paths

modified these entries in the yaml file allowing them to download. placing entries in your yaml file

```
 image: ghcr.io/wg-easy/wg-easy
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/icon.png
    ports:
```

**Comment by pheiduck** [comment]
If you want to have Italian language on wg-easy feel free to create PR. :)
Would be nice if we get more languages to support.  :D

**Comment by tigernero79** [comment]
easy wireguard with login password and container icon


```
name: wg-easy
services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    environment:
      - PASSWORD=casaos
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_HOST=casaos.local
      - WG_PORT=51820
    image: ghcr.io/wg-easy/wg-easy
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/icon.png
    ports:
      - target: 51820
        published: "51820"
        protocol: udp
      - target: 51821
        published: "51821"
        protocol: tcp
    restart: unless-stopped
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"
    volumes:
      - type: bind
        source: /DATA/AppData/wg-easy/wireguard
        target: /etc/wireguard
    x-casaos:
      ports:
        - container: "51820"
          description:
            en_us: Wireguard VPN port
        - container: "51821"
          description:
            en_us: WEB UI port
      volumes:
        - container: /etc/wireguard
          description:
            en_us: Contains device VPN config files.
    devices: []
    command: []
    network_mode: bridge
    privileged: false
    hostname: wg-easy
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7781M
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: Sawy
  category: Network
  description:
    de_de: Sie haben den einfachsten Weg gefunden, WireGuard auf jedem Linux-Host zu
      installieren und zu verwalten!
    en_us: You have found the easiest way to install & manage WireGuard on any Linux
      host!
    es_es: Ha encontrado la forma más sencilla de instalar y gestionar WireGuard en
      cualquier host Linux.
    fr_fr: Vous avez trouvé le moyen le plus simple d'installer et de gérer
      WireGuard sur n'importe quel hôte Linux !
    hu_hu: Megtalálta a WireGuard telepítésének és kezelésének legegyszerűbb módját
      bármely Linux hoszton!
    it_it: Avete trovato il modo più semplice per installare e gestire WireGuard su
      qualsiasi host Linux!
    pl_pl: Znalazłeś najłatwiejszy sposób instalacji i zarządzania WireGuard na
      dowolnym hoście z systemem Linux!
    pt_br: Você encontrou a maneira mais fácil de instalar e gerenciar o WireGuard
      em qualquer host Linux!
    ru_ru: Вы нашли самый простой способ установки и управления WireGuard на любом
      Linux-хосте!
    sv_se: Du har hittat det enklaste sättet att installera och hantera WireGuard på
      en Linux-värd!
    uk_ua: Ви знайшли найпростіший спосіб встановити WireGuard та керувати ним на
      будь-якому комп'ютері з Linux!
    zh_cn: 您已经找到了在任何 Linux 主机上安装和管理 WireGuard 的最简单方法！
  developer: WeejeWel
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/icon.png
  main: wg-easy
  port_map: "51821"
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/screenshot-3.png
  store_app_id: wg-easy
  tagline:
    de_de: WEB UI zur Verwaltung von WireGuard VPN.
    en_us: WEB UI to manage WireGuard VPN.
    es_es: WEB UI para gestionar WireGuard VPN.
    fr_fr: WEB UI pour gérer WireGuard VPN.
    hu_hu: WEB felhasználói felület a WireGuard VPN kezeléséhez.
    it_it: Interfaccia WEB per la gestione di WireGuard VPN.
    pl_pl: WEB UI do zarządzania WireGuard VPN.
    pt_br: WEB UI para gerenciar o WireGuard VPN.
    ru_ru: WEB-интерфейс для управления WireGuard VPN.
    sv_se: WEB UI för att hantera WireGuard VPN.
    uk_ua: WEB інтерфейс для керування WireGuard VPN.
    zh_cn: 管理 WireGuard VPN 的 WEB UI。
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/icon.png
  tips:
    before_install:
      en_us: >
        🔧 Settings


        Default password: `casaos`


        ⚠️ Warning!


        You need to change at least change the mandatory parameter `WG_HOST` for this app to work properly.

        It's value has to be a domain (or an IP address) that points to this server (accesible from WAN).


        Same applies to the `WG_PORT` parameter. Change it to the port accessible from outside your LAN if it differs from the default 51820.
      zh_cn: |
        🔧 设置

        默认密码： `casaos`

        ⚠️ 警告！

        您至少需要更改强制参数 `WG_HOST` 才能使本应用程序正常工作。
        其值必须是指向本服务器的域（或 IP 地址）（可从广域网访问）。

        同样，`WG_PORT` 参数也是如此。如果与默认的 51820 不同，请将其更改为局域网外可以访问的端口。
  title:
    en_us: WireGuard Easy
    custom: ""
  hostname: ""
  scheme: http
  index: /
```

**Comment by pheiduck** [comment]
they have to upgrade the image: https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/Apps/WireGuardEasy/docker-compose.yml#L4
based on the new organisation.

**Comment by tigernero79** [comment]
https://github.com/IceWhaleTech/CasaOS-AppStore/compare/main...tigernero79:CasaOS-AppStore:patch-1

**Comment by pheiduck** [comment]
> [IceWhaleTech/CasaOS-AppStore@main...tigernero79:CasaOS-AppStore:patch-1](https://github.com/IceWhaleTech/CasaOS-AppStore/compare/main...tigernero79:CasaOS-AppStore:patch-1)

Seems they don’t allow none collaborators to create PR‘s

@tigernero79 I would suggest you create a wiki page how to update the image to newer one on casaOS.
