### ISSUE TITLE
Not able to start docker imge on CentOS 7

### ISSUE THREAD

**Issue by AlexisHW** [wg-easy/wg-easy#813]
**Describe the bug**
I start the docker container on the clean CentOS 7 and get the following in the los:

$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at async /app/lib/WireGuard.js:63:9
2024-02-03T23:37:40.101Z Server Listening on http://0.0.0.0:51821
2024-02-03T23:37:40.106Z WireGuard Loading configuration...
2024-02-03T23:37:40.111Z WireGuard Configuration loaded.
2024-02-03T23:37:40.111Z WireGuard Config saving...
2024-02-03T23:37:40.115Z WireGuard Config saved.
$ wg-quick down wg0

**To Reproduce**
Start with default params as per docs

**Expected behavior**
wg0 interface to be created in the docker image

**Screenshots**

**Desktop (please complete the following information):**
CentOS 7

**Additional context**
SELiniux is disabled

interfaces in the docker container
094ab937d7fc:/app# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
68: eth0@if69: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
094ab937d7fc:/app#

**Comment by eandersons** [comment]
Please search issues before adding new ones: [centos](/wg-easy/wg-easy/issues?q=is%3Aissue+centos)!

One of the issues in search results is #585, which has the following <https://github.com/wg-easy/wg-easy/issues/585#issuecomment-1610884401>:

> I got same problem with my CentOS 7. I found that there are some requirements to install wireguard.
> <https://www.wireguard.com/install/#installation>
>
> For example, CentOS 7 need to install and boot from kernel-plus to support wireguard.

**Comment by AlexisHW** [comment]
Thanks a lot for your prompt help!

For CentOS 7 fixed by installing
$ sudo yum install epel-release elrepo-release
$ sudo yum install yum-plugin-elrepo
$ sudo yum install kmod-wireguard 

on the host before running WG container

It would be great that you mention in your docs taht running docker container in most of OS requires prereqs installation, not just install docker

**Comment by pheiduck** [comment]
> It would be great that you mention in your docs taht running docker container in most of OS requires prereqs installation, not just install docker

See: https://github.com/wg-easy/wg-easy/pull/814
