### ISSUE TITLE
Empty dark mode in version 1.0

### ISSUE THREAD

**Issue by jcnk9** [wg-easy/wg-easy#820]
**Describe the bug**
When i pull the fresh container in version 1.0 it starts in a dark theme an the app.js aborts at line 9: const semver = require('semver');

**To Reproduce**
1. fresh build and deploy image tag 1.0
2. start webapp
3. empty dark page with js error

**Expected behavior**
See the UI in dark mode and a login form for known User

**Screenshots**
![image](https://github.com/wg-easy/wg-easy/assets/33402907/422130a3-f7e6-49f3-be01-16a110f4f8f2)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome
 - Version 121.0.6167.140

**Additional context**
I hope i didn't do anything wrong. v9.0 works without any problems after i set the version back.

**Comment by pheiduck** [comment]
image tag 1.0 is not an image use  image tag 10
