### ISSUE TITLE
The wg-easy web UI tries to load CSS from an external website

### ISSUE THREAD

**Issue by glutenmancy** [wg-easy/wg-easy#828]
**Describe the bug**
The wg-easy web UI tries to load CSS from an external site which can at times be inaccessible. This could also be a security consideration for some use cases.

**To Reproduce**
1. Visit wg-easy web UI on a restricted network or while blocking external resources from loading (e.g. with uMatrix or other blocking extension)
2. Page will appear with giant icons and network log will show unloaded resources

**Expected behavior**
Page will load normally.

**Screenshots**
![image](https://github.com/wg-easy/wg-easy/assets/27926988/45e21050-43bb-425f-9263-3cb20e0a1955)

**Desktop:**
 - OS: Windows
 - Browser: Firefox
 - Version: 122

**Additional context**
Would it be possible to bundle this CSS file as an included resource instead of external?

**Comment by pheiduck** [comment]
This will be fixed in our next release Version 11. This happend because the css is deployed on the tailwindcss cdn. Which might be blocked by your browser extensions.
Version 11 will have a local deployed css and does not load stuff from external resources.

**Comment by glutenmancy** [comment]
Thank you @pheiduck!
