### ISSUE TITLE
Creating profiles via webUI doesn't respect custom server port

### ISSUE THREAD

**Issue by juaneloDev** [wg-easy/wg-easy#832]
Hi, I noticed that if you set up a server to run on a non-standard port (ie. "-p 443:51820/udp") from the startup command "docker run -d --name=wg-easy", once you create profiles from the web interface, they'll still be created at :51820 by default, instead of at the port defined when starting up the instance.

**Comment by eandersons** [comment]
For that the environment variable `WG_PORT` is intended:

> The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.

https://github.com/wg-easy/wg-easy/blob/910ce7052e5e50d9d6c814f8fea6e1a01e7fb96b/src/lib/WireGuard.js#L200-L212

**Comment by peterlewis** [comment]
> For that the environment variable `WG_PORT` is intended:

☝️
