### ISSUE TITLE
When `systemctl stop wg-easy`, PostDown script is not working.

### ISSUE THREAD

**Issue by samart45** [wg-easy/wg-easy#835]
**Describe the bug**
When use `systemctl stop wg-easy`, PostDown script is not working.
I try to add WG_POST_DOWN.

```
module.exports.WG_POST_DOWN = process.env.WG_POST_DOWN || `
iptables -t nat -D POSTROUTING -s ${module.exports.WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ${module.exports.WG_DEVICE} -j MASQUERADE;
iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT;
iptables -D FORWARD -i wg0 -j ACCEPT;
iptables -D FORWARD -o wg0 -j ACCEPT;
`.split('\n').join(' ');
```

For remove iptables rule after stop service.

**To Reproduce**
1. Add WG_POST_DOWN script
```
module.exports.WG_POST_DOWN = process.env.WG_POST_DOWN || `
iptables -t nat -D POSTROUTING -s ${module.exports.WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ${module.exports.WG_DEVICE} -j MASQUERADE;
iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT;
iptables -D FORWARD -i wg0 -j ACCEPT;
iptables -D FORWARD -o wg0 -j ACCEPT;
`.split('\n').join(' ');
```
3. systemctl start wg-easy
4. iptables -L -t nat (to check MASQUERADE rule)
5. systemctl stop wg-easy
6. iptables -L -t nat (to check MASQUERADE rule again, rule is not remove)
7. systemctl start wg-easy
8. iptables -L -t nat (to check MASQUERADE rule again, rule is duplicate)

**Expected behavior**
iptables rule should remove after stop service.

**Addition information**
After systemctl stop wg-easy. wg0 interface is exists.

I try to use command `wg-quick down wg0`.
wg0 interface removed.
iptables rule removed.

**Comment by pheiduck** [comment]
@samart45 please test my linked PR #842

**Comment by samart45** [comment]
@pheiduck I suggest. You should handle graceful shutdown for nodejs.
Because when shutdown wg-easy (via systemctl or docker), wg-easy is terminated. but wg-easy cannot call `wq-quick down wg0` to terminate wireguard and apply iptables for WG_POST_DOWN.

wg0 interface and iptables rule is exists.

Reference for graceful shutdown: 
- https://dev.to/yusadolat/nodejs-graceful-shutdown-a-beginners-guide-40b6
- https://nairihar.medium.com/graceful-shutdown-in-nodejs-2f8f59d1c357

**Comment by samart45** [comment]
@pheiduck 
Example code for handle graceful shutdown.
https://github.com/wg-easy/wg-easy/compare/master...samart45:wg-easy:master

I have tested it. It's work.
