### ISSUE TITLE
Handshake failed on iPhone and MacBook

### ISSUE THREAD

**Issue by lorenzdomb** [wg-easy/wg-easy#836]
**Describe the bug**
When I try to connect with my Homeserver via Mac or iPhone Client, there is no connection to internet or intranet. 

Logs show: Handshake did not complete after 5 seconds, retrying 

A few days ago it works correctly. 

Installation via docker, following readme.  

**To Reproduce**
Nothing changed on the Server. 

**Expected behavior**
That it works correctly like before. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome, safari
 - Version newest

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.3.1
 - Browser safari, chrome

**Comment by peterlewis** [comment]
Docker compose pls.

**Comment by lorenzdomb** [comment]
I only used docker with the following command:

docker run -d \
  --name=wg-easy \
  -e LANG=de \
  -e WG_HOST=xyz.abc.de \
  -e PASSWORD=superstrongpassword \
  -e WG_DEFAULT_DNS=192.168.188.3 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy

An update to the lasted version doesn't change anything. 

I noticed that the VPN connection was not established using mobile data (Vodafone). The connection via other WiFi routers works fine. Any ideas?

**Comment by pheiduck** [comment]
xyz.abc.de needs to be poniting to your Public IP, if its not a static one you need dyndns.

**Comment by jamess60** [comment]
Similar issue here - cannot handshake on macOS 

    wireguard:
        image: ghcr.io/wg-easy/wg-easy
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - LANG=en
            - WG_HOST=xx.xx.xx.xx
            - PASSWORD=HIDDEN
            - WG_PERSISTENT_KEEPALIVE=25
            - WG_DEFAULT_DNS=1.1.1.1, 9.9.9.9
            - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
            - WG_DEVICE=ens6
        volumes:
            - /containers/vps-cont-01/data/wireguard:/etc/wireguard
            - /lib/modules:/lib/modules
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        ports:
            - 51820:51820
            - 51821:51821
        restart: always

Firewall on the VPS is just any any

**Comment by benisdev-py** [comment]
Same for me the Connection works but the Handshake failes and the Connection is commpletly reconnecting After like 2-3 min.

**Comment by chrisotherwise** [comment]
This seems to be an iphone-only problem, I'm seeing exactly the same thing with my iPhone Pro 15, but the vpn works fine from both my iPad and my macbook. From the phone I never see any packets at all reaching the VPN.

**Comment by lorenzdomb** [comment]
Update: 
After I turned off my VPS on WG-Easy for a week and turned it back on today, the handshake works again without any changes. Strange...

**Comment by bytaj** [comment]
It's still happening to me, I think it's not closed

**Comment by benisdev-py** [comment]
> It's still happening to me, I think it's not closed

For me too but I now have also a wiregaurd Service ok OPNsense and there its Wirkung perfectly. But would be good if this issue would be fixed.
