### ISSUE TITLE
Site to site configuration not working (WG_ALLOWED_IPS)

### ISSUE THREAD

**Issue by K4rlosReyes** [wg-easy/wg-easy#840]
**Bug description:**
When attempting to configure a site-to-site setup, I encounter an issue wherein the declaration of allowed IPs (`WG_ALLOWED_IPS`) fails to reflect any changes in the configuration or apply to newly created clients.

**To Reproduce:**
1. Execute the docker run command with specified `WG_ALLOWED_IPS`.
2. Generate a new client.
3. Inspect the configuration file for AllowedIPs.

**Expected behavior**
The expected behavior is that the specified allowed IPs should be incorporated into the configuration upon executing the command utilizing `WG_ALLOWED_IPS`.

**Screenshots**
No relevant screenshots available.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)

**Comment by eandersons** [comment]
You first have to stop and remove the WireGuard Easy container before executing `docker run` to change environmet variables. See also [Updating](/wg-easy/wg-easy?tab=readme-ov-file#updating): 

> ```shell
> docker stop wg-easy
> docker rm wg-easy
> ```

**Comment by eandersons** [comment]
@K4rlosReyes, sorry, this might not be the case, just noticed the discussion #823.

**Comment by K4rlosReyes** [comment]
Thank you for your prompt response; it's greatly appreciated. I managed to resolve the issue by adjusting the code within the `_saveConfig` function:

```
AllowedIPs = ${client.address}/32,${WG_ALLOWED_IPS}`;
```

With this modification, the functionality now operates as expected. However, it required the creation of a custom image...
