### ISSUE TITLE
Changelog and Roadmap

### ISSUE THREAD

**Issue by corasaniti** [wg-easy/wg-easy#852]
Hi,
Is it possible to have a small changelog with the changes made every time there is a new release?
It would be nice to also have a roadmap of upcoming features
Thanks in advance
PC

**Comment by pheiduck** [comment]
You can find changelogs here: https://github.com/wg-easy/wg-easy/blob/master/docs/changelog.json
and we might use milestones for our next releases: https://github.com/wg-easy/wg-easy/milestones

**Comment by corasaniti** [comment]
Thank you
