### ISSUE TITLE
Tx/Rx charts not working

### ISSUE THREAD

**Issue by DanyaSWorlD** [wg-easy/wg-easy#859]
After one of updates charts have been disappeared, but they are still presented in features list.
![изображение](https://github.com/wg-easy/wg-easy/assets/19343702/0788ed42-0ba1-4b47-8775-8810971b12ce)
So, the question is are they expected to be back or they are removed because of UI bad perfomance and gone forever?

**Comment by peterlewis** [comment]
The absence of charts is not intentional, this appears to be a bug. Thank you for raising!

**Comment by peterlewis** [comment]
Paging @suxscribe as, evident from #872, he is somewhat of a Tailwind guru... ;)

**Comment by suxscribe** [comment]
@peterlewis I've also thought this was intentional. I'll see what i can do
It's not that I like Tailwind this much btw =)

**Comment by peterlewis** [comment]
@pheiduck I'm not sure that https://github.com/wg-easy/wg-easy/pull/873 fixes this, yet? Or am I mistaken?

**Comment by suxscribe** [comment]
I've managed to get charts working. 
Looks quite cluttered, imo. Also the chart moves in steps, I got headache while debugging =)

Attached screenshots of different chart types:
<details>
  <summary>Charts</summary>
  ![2024-02-26_14-46-35](https://github.com/wg-easy/wg-easy/assets/19854626/4e5f75b5-98e4-42c1-948d-5fe7f0d9c1a6)
  ![2024-02-26_14-47-39](https://github.com/wg-easy/wg-easy/assets/19854626/7c466e6e-8c4c-497a-95ba-f2a3a4dc1a6e)
  ![2024-02-26_14-48-50](https://github.com/wg-easy/wg-easy/assets/19854626/d20758c4-fcd4-4247-b450-5739d932fd8f)
  ![2024-02-26_14-51-19](https://github.com/wg-easy/wg-easy/assets/19854626/e35d1589-4d95-4f6b-bb1a-1d5dc15a462a)
</details>

**Comment by peterlewis** [comment]
Ah amazing! Thank you @suxscribe! That is interesting! It may be pertinent for us to re-surface this through an environment variable, such as `UI_CHARTS` and default to `false`.

I note you've included a few examples as well. Do you think it would be a good idea to allow for the changing of styles with `UI_CHARTS_STYLE` or equivilent?

Thank you again, I would really welcome all your thoughts as to the above ponderings.

**Comment by suxscribe** [comment]
@peterlewis Yep, it needs further testing, so variables totally make sense
