### ISSUE TITLE
Future enhancements

### ISSUE THREAD

**Issue by pjbpaul** [wg-easy/wg-easy#86]
Hi, This is great, I like it a lot, excelent work. If you are interested in options for future enhancements here is a couple of things I would find useful. Update 1, I would like the option to have a read only user\password, this user could see the connected clients and be able to turn on\off the clients, but not config and no downloads of files or qr codes. Then a full admin user that can do everything as now.  Update 2, I would like the option to be able to allow\disallow client to client connections from the web console. Update 3, The option to customise the allowed IP's per user from the web console. Some clients I would like to be able to connect to only 1 server or  a couple servers, but not to all the network, but allow other clients to connect everywhere. Just a few ideas. Thanks. Paul.

**Comment by fanta2go** [comment]
That sounds great! Would like it to login about MFA (multi factor authentication) for more Security...
