### ISSUE TITLE
WG_PORT not copied to wg0.conf

### ISSUE THREAD

**Issue by VilterPD** [wg-easy/wg-easy#875]
**Describe the bug**
I started the container with WG_PORT=52983

**To Reproduce**
1. Start container with ENV WG_PORT=52983

**Expected behavior**
wg0.conf configured with ListenPort=52983

**Desktop (please complete the following information):**
 - OS: Raspbian OS Lite

**Comment by eandersons** [comment]
`WG_PORT` is only meant to change value for downloaded client configuration:

> The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.

See for example the issue #9, as well as many others that are similar and can be found by searching [WG_PORT](/wg-easy/wg-easy/issues?q=is%3Aissue+WG_PORT).

**Comment by VilterPD** [comment]
Oh wow. That makes sense. Thanks.
