### ISSUE TITLE
Error running ghcr.io/wg-easy/wg-easy image (weejewel/wg-easy works)

### ISSUE THREAD

**Issue by kavagoe** [wg-easy/wg-easy#878]
**Describe the bug**
Running container with github image ( NodeJS18) container fails to start with below log error:

#Fatal error in , line 0
#unreachable code
#FailureMessage Object: 0xbea3531c

**To Reproduce**
1. Run container as per instructions with image ghcr.io/wg-easy/wg-easy
2. Container starts but logs show message

**Expected behavior**
Running container with identical arguments using image weejewel/wg-easy works as expected 

**Desktop (please complete the following information):**
 - "Raspbian GNU/Linux 10 (buster)"
 - 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

**Comment by peterlewis** [comment]
`docker-compose.yml` please

**Comment by HomemadeAdvanced** [comment]
In my case it works, check out my created .yaml:

https://codeberg.org/HomemadeAdvanced/Docker-Homelab/src/branch/main/wg-easy-v2.yaml

**Comment by kavagoe** [comment]
Thanks for the reply, it was easier to reinstall the OS. Image runs good now

**Comment by kavagoe** [comment]
OS reinstall fixed the issue

**Comment by HomemadeAdvanced** [comment]
Allright great.
