### ISSUE TITLE
No connection with WG_DEFAULT_DNS & WG_DEFAULT_ADDRESS options

### ISSUE THREAD

**Issue by andrewbpowers** [wg-easy/wg-easy#882]
Hello!

Everything works without problems if I use the following standard configuration and only adjust the values for "WG_HOST" "PASSWORD". Perfect!

But as soon as I add the options "WG_DEFAULT_ADDRESS" and/or "WG_DEFAULT_DNS" and adjust the values, no client gets a connection to the internet anymore. It also doesn't work if I use the default value 10.8.0.x for "WG_DEFAULT_ADDRESS", for example.

Any idea what the problem could be?
Many thanks in advance for help and tips!

Have a great day...

**Comment by mfschumann** [comment]
Same here. Looking inside the container the wg0 interface always has IP 10.8.0.1, no matter what I set WG_DEFAULT_ADDRESS to. Also `ip route` inside the container only shows a route for 10.8.0.0/24 via wg0.

**Comment by andrewbpowers** [comment]
Right!

I have now customized this ([https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml](https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml)) Docker compose file and tested it out (via Portainer). 
Works, also together with Pihole!

**Comment by mfschumann** [comment]
Cool, do you mind to share your customized docker-compose.yml?

**Comment by andrewbpowers** [comment]
I didn't change much in the example. But I would have to look it up. I think I have changed and/or activated the following information/options: `LANG, WG_HOST, PASSWORD, WG_PORT, WG_DEFAULT_ADDRESS, WG_DEFAULT_DNS, WG_MTU, WG_ALLOWED_IPS` and `UI_TRAFFIC_STATS`

 Otherwise, wg-easy is in the same network as the Pi-hole installation.
