### ISSUE TITLE
Cant log to pihole admin page

### ISSUE THREAD

**Issue by zonexCS** [wg-easy/wg-easy#916]
I'm using 
https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole
But when i create and start the container, I can reach portainer admin page and wg-easy admin page, but i can't reach the pihole page unless if I do trought the wg vpn client... my question is wich ip i should put to reach it without vpn active? for example i log on portainer and wg-easy trought 192.168.1.512 for example, but not working for pihole.

thanks

**Comment by denisszzz** [comment]
Hi, i can using ip when write in ur env WG_HOST + 5353 port. ex http://192.168.1.512:5353/admin/login.php

**Comment by zonexCS** [comment]
Oh forgot the port... thanks alot
