### ISSUE TITLE
AllowedIPs was overwritten after reboot the docker

### ISSUE THREAD

**Issue by zzmy78** [wg-easy/wg-easy#921]
My home network doesn't got a public IP, so I install wg-easy in vps connecting my phone device and home router.  I can access home router through WG default adress 10.10.8.x;  however I wish to access home devices through my LAN ips (192.168.10.0/24);  I try to manually update AllowedIPs in wg0.conf file as below screen, and it was no problem to access any my home devices by LAN IPs.  However, the Alloweded IPs will be reset default and remove my manual update after docker reboot.   Can you help to reslove this issue.?

![微信截图_20240317092930](https://github.com/wg-easy/wg-easy/assets/119769156/61c3493f-554d-47bb-8668-b7bc6fada35f)

**Comment by pheiduck** [comment]
The `wg0.conf` get's overwritten by design as you can read in the header of the file.

**Comment by zzmy78** [comment]
> The `wg0.conf` get's overwritten by design as you can read in the header of the file. You have to add `WG_ALLOWED_IPS=` to your docker compose.

yes, i saw this in the header, but i wish writer can solve this issue.  I have already tried to add WG_ALLOWED_IPS= to docker compose , but unfortunately, it seems it is valid for clients routing only, but not for server routing.

**Comment by MisterPresident** [comment]
same problem here. Is there a way to set allowed ips for clients?

**Comment by renshed** [comment]
any news on the routing?

**Comment by wwalterww** [comment]
I think I found a dirty workaround:
First create a new persistent file, e.h. "/etc/wireguard/network.peer", containing the [Peer] section of your home network. Then add this command to your docker-compose.yml or docker creation script: wg addconf wg0 /etc/wireguard/network.peer
(docker-compose.yaml
service:
  wg-easy:
    image: ...
    ...
    command:
      - wg addconf wg0 /etc/wireguard/network.peer
)


I've not yet tried rebuilding the container, don't want to risk cutting my VPN connection now. But sing bash inside the container the command does what it should do - adding the routing information to the network peer.

**Comment by hausen1012** [comment]
具有同样的问题，希望重启容器配置不要被重写

**Comment by nhermosilla14** [comment]
There is already a PR (#997) aiming to address this very issue. It is not yet merged, though. In the meantime, I would suggest to avoid manually editing the wg0.conf file and, instead, add the routing entry manually by using the already available WG_POST_UP variable:

```bash
WG_POST_UP=ip route add 192.168.10.0/24 via 10.10.8.3 metric 50;
```
That should do basically the same thing, with the advantage of not being overwritten every time the container restarts.
