### ISSUE TITLE
Source code separation

### ISSUE THREAD

**Issue by cany748** [wg-easy/wg-easy#928]
### What am I suggesting?
I propose to split the source code into two parts: `frontend` and `server`. This shouldn't be a problem, we will need to move a few directories and change a few files. We can keep the existing directory names `src` and `www`, but I would recommend using more contextual names.

### Why?
You need to have a clear separation between the two runtime environments: `Node.js` and `browser`. So that we can use different configurations of Eslint and Typescript, and clearly separate the dependencies.

I'm ready to do a PR.

**Comment by peterlewis** [comment]
This makes a lot of sense. Thank you for your generosity. It would be greatly appreciated if you are happy to make a PR! Thank you!

**Comment by pheiduck** [comment]
Any reasons why the PR was closed?
