### ISSUE TITLE
Blank screen on latest `nightly`

### ISSUE THREAD

**Issue by peterlewis** [wg-easy/wg-easy#931]
**Describe the bug**
Blank screen on load in latest `nightly`

**To Reproduce**
1. Go to wg-easy 
2. Observe blank screen

**Expected behavior**
wg-easy should display

**Screenshots**
![image](https://github.com/wg-easy/wg-easy/assets/820394/85ddd677-d4d3-4fc1-8fb6-e16e3203b348)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 17.4
 - Browser: Safari

**Additional context**
Haven't done any troubleshooting yet but raising issue before I get started with morning chores.

**Comment by pheiduck** [comment]
Not a problem for me: 
![Bildschirmfoto_2024-03-22_10-17-51](https://github.com/wg-easy/wg-easy/assets/47042125/d963bff7-1c8c-4cc1-8e4c-1d41bc25b58a)

**Comment by pheiduck** [comment]
If you use Nginx Proxy Manager there is an option called "Cache Assets" which should be disabled for wg-easy. Otherwise removing browser data can help.

**Comment by LoV432** [comment]
I am using traefik proxy and the webpage css isn't loading with these errors:
```
The script from “https://wireguard.removed.com/js/vendor/vue.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/vendor/vue-i18n.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/vendor/apexcharts.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/vendor/vue-apexcharts.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/vendor/sha256.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/vendor/timeago.full.min.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/api.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/i18n.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The script from “https://wireguard.removed.com/js/app.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wireguard.removed.com
The stylesheet https://wireguard.removed.com/css/app.css was not loaded because its MIME type, “text/plain”, is not “text/css”. wireguard.removed.com
Current Release: 12 app.js:393:15
Latest Release: 12 app.js:394:15
```
I have tried recreating the traefik docker container to make sure all cache is removed and also turned off browser cache but that didn't fix the issue.

the webpage loads fine if i open it directly using ip but with this console output:
```
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/vendor/vue.min.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/vendor/vue-i18n.min.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/vendor/apexcharts.min.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/vendor/vue-apexcharts.min.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/vendor/sha256.min.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/vendor/timeago.full.min.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/api.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/i18n.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
The script from “http://192.168.1.104:51821/js/app.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. 192.168.1.104:51821
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. 192.168.1.104:51821
Current Release: 12 app.js:393:15
Latest Release: 12 app.js:394:15
```

**Comment by pheiduck** [comment]
Ya, I get this warnings too but everything is fine.

**Comment by pheiduck** [comment]
Ping @cany748

**Comment by LoV432** [comment]
> Ya, I get this warnings too but everything is fine.

Even the css error? i was guessing the issue was something to do with it because i only get it when opening using traefik proxy:

> The stylesheet https://wireguard.removed.com/css/app.css was not loaded because its MIME type, “text/plain”, is not “text/css”. wireguard.removed.com

**Comment by pheiduck** [comment]
> The stylesheet https://wireguard.removed.com/css/app.css was not loaded because its MIME type, “text/plain”, is not “text/css”. wireguard.removed.com

no.

**Comment by peterlewis** [comment]
> > Ya, I get this warnings too but everything is fine.
> 
> 
> 
> Even the css error? i was guessing the issue was something to do with it because i only get it when opening using traefik proxy:
> 
> 
> 
> > The stylesheet https://wireguard.removed.com/css/app.css was not loaded because its MIME type, “text/plain”, is not “text/css”. wireguard.removed.com

Snap. I too am using Traefik. Will need further investigation. I'm away from desk at the moment so cannot dig deeper, I'm afraid.

**Comment by peterlewis** [comment]
This looks to be caused by https://github.com/wg-easy/wg-easy/pull/914/ and from what I can see it may relate to incorrect paths, potentially due to the absence of preceding slashes:

https://stackoverflow.com/questions/50143297/refused-to-execute-script-from-because-its-mime-type-and-strict-mime-type

https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type

Ideally we would revert https://github.com/wg-easy/wg-easy/pull/914/ but as only affecting nightly let's fix forward for now.

@cany748 Are you happy to have a sniff, please?

**Comment by pheiduck** [comment]
found this one: https://stackoverflow.com/questions/57432292/javascript-mime-type-warning-on-firefox
