### ISSUE TITLE
Backwards compatibility issue with `WG_DEFAULT_ADDRESS`

### ISSUE THREAD

**Issue by peterlewis** [wg-easy/wg-easy#943]
In latest nightly, on setups where `WG_DEFAULT_ADDRESS` is set in the current format (e.g. `172.16.2.x`) the container fails to start with error advising of invalid IP address.

It is _essential_ that clients should not break on upgrade as a result of any changes to variables.

@pheiduck

**Comment by pheiduck** [comment]
catched it as well will do a revert.

**Comment by pheiduck** [comment]
#888 need some rework to get Backwards compatibility. I haven't currently time for...
