### ISSUE TITLE
 Can I freely edit the port in the control panel and automatically generate a new configuration file? 

### ISSUE THREAD

**Issue by xiao-Long-Long** [wg-easy/wg-easy#950]
When I change the default port 51820 to 55661, 
the configuration file download QR code scanning port in the Web control panel is still 51820. 
Can I freely edit the port in the control panel and automatically generate a new configuration file?

**Comment by pheiduck** [comment]
ya, as 51820 is been hardcoded. We had some try and error to get Port change working but until now without success. Feel free to open a PR.

**Comment by eandersons** [comment]
> When I change the default port 51820 to 55661

If you by this mean port mapping (seems like it), then the port to be used in client configuration can be specified with the environment variable `WG_PORT`.
If you mean changing port within container, then see what @pheiduck wrote above.
