### ISSUE TITLE
It not working if you change the IP range from 10.8.0.0 to other IP range

### ISSUE THREAD

**Issue by DarKidoz** [wg-easy/wg-easy#954]
**Describe the bug**
It did not work after change the IP default range from 10.8.0.0 to other IP range.

**To Reproduce**
If change to 10.6.0.0, when we create 1st peer, it will become 10.6.0.0 as IP, create 2nd peer, it will show IP is reach the limit.

**Comment by GaptekORG** [comment]
the same thing happened to me when using the latest version, but if you use the suffix 'x' in the IP address the error does not occur.

example :
Environment="WG_DEFAULT_ADDRESS=10.10.99.0"

change the last number 0 to x, like this :
Environment="WG_DEFAULT_ADDRESS=10.10.99.x"

don't understand what's going on but it works

**Comment by DarKidoz** [comment]
Will have a try on this. Thanks 🙏🏻

**Comment by DarKidoz** [comment]
Yes, I did test on this, it working. Thanks @GaptekORG

**Comment by peterlewis** [comment]
@DarKidoz You running `nightly`? Paging @pheiduck for his awareness as we were working through resolution for this, recently.
