### ISSUE TITLE
Not receiving data

### ISSUE THREAD

**Issue by wassereimer86** [wg-easy/wg-easy#96]
I can get a handshake but i don´t receive any data on my Androd phone. Custom docker port is exposed and its forwarded in my router (yes, homeserver - but with ddns and a subdomain). The docker log doesn´t show anything. Other containers are working fine. Im using nging-proxy but i don´t think that this is a problem. Am i missing something or is there a problem?

**Comment by divadsn** [comment]
Why is this closed? I recently tried running your image inside docker-compose and couldn't access anything when connected.

In the end I had to use wg-access-server which was working, but your web UI is far better to use.
