### ISSUE TITLE
AmneziaWG in wg-easy

### ISSUE THREAD

**Issue by HamasakiBrain** [wg-easy/wg-easy#962]
Has anyone integrated AmneziaWG (on golang) into wg-easy?

**Comment by pheiduck** [comment]
I don’t know may need feedback from @WeeJeWel (Founder of WireGuard Easy).

**Comment by eandersons** [comment]
@HamasakiBrain, can AmneziaWG and WireGuard work together or have they to be used interchangeably?
I took a glimpse on what AmneziaWG is, but I did not come to an complete understanding about this.

On a less serious note - if AmneziaWG would be joined with WireGuard Easy in one way or another, the outcome would be AmneasyWG. 😁

**Comment by peterlewis** [comment]
https://github.com/spcfox/amnezia-wg-easy

**Comment by HamasakiBrain** [comment]
> Looks like there's a fork that aims to accomplish what you're after:
> 
> https://github.com/spcfox/amnezia-wg-easy

I know this library, but it is very crooked and there is a DNS data leak and it works very slowly. And it works every other time.

**Comment by HamasakiBrain** [comment]
> @HamasakiBrain, can AmneziaWG and WireGuard work together or have they to be used interchangeably? I took a glimpse on what AmneziaWG is, but I did not come to an complete understanding about this.
> 
> On a less serious note - if AmneziaWG would be joined with WireGuard Easy in one way or another, the outcome would be AmneasyWG. 😁

AmneziaWG is a wireguard on steroids, it is supplemented to protect against DPI locks. But I would like wg-easy to officially release an update for amneziaWG so that everything works clearly)
 It can be a separate branch or something like that

**Comment by HamasakiBrain** [comment]
up

**Comment by Safe3** [comment]
This is my improve pure go version of wg-easy with no wireguard installing need.
I can contribute to wg-easy project if need.

Introduction：
Single file, better performance, no wireguard installation dependency.

Project：https://github.com/Safe3/firefly

Screenshot：
![image](https://raw.githubusercontent.com/Safe3/firefly/main/firefly.png)

**Comment by pheiduck** [comment]
> > Looks like there's a fork that aims to accomplish what you're after:
> > https://github.com/spcfox/amnezia-wg-easy
> 
> I know this library, but it is very crooked and there is a DNS data leak and it works very slowly. And it works every other time.

We don't care what they do with their fork. Apart from that, it is up to the user whether he uses a fork or the upstream project. If there are security issues, we are working on fixing them as soon as possible.
