### ISSUE TITLE
Why my wg-easy webpage only can create a object cannot create【为什么我的wg-easy网页端只能创建一个对象就不能创建了】

### ISSUE THREAD

**Issue by YogruTi** [wg-easy/wg-easy#970]
There's a composite file，please help me check which happened in the following.【以下是compose文件，请帮我检查以下到底哪里出现了问题】
    In this paper，we discuss the relationship between the mechanism and the relationship between the mechanism.【用的compose文件恢复容器，但是登录到网页端只能创建一个对象连接】

version: "3.8"
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=chs
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=0.0.0.0

      # Optional:
      - PASSWORD=possword
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.0
      - WG_DEFAULT_ADDRESS_RANGE=24
      - WG_DEFAULT_DNS=114.114.114.114
      - WG_MTU=1420
      - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=0 (0 # Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

**Comment by pheiduck** [comment]
Well, a client can not have IP `10.8.0.0`

**Comment by pheiduck** [comment]
And please revise: https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml

**Comment by YogruTi** [comment]
> 客户端不能拥有IP `10.8.0.0`

所以我要把- WG_DEFAULT_ADDRESS=10.8.0.0改为- WG_DEFAULT_ADDRESS=10.8.0.1然后重新执行compose文件吗

**Comment by YogruTi** [comment]
> And please revise: https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml

I'm going to try it now.

**Comment by pheiduck** [comment]
And you have maybe repull the image

**Comment by YogruTi** [comment]
> And you have to repull the image
Thank you. After changing the configuration file, execute docker compose up --detach again.
![Uploading 屏幕截图 2024-04-07 001430.png…]()

**Comment by pheiduck** [comment]
Which docker tag are you using?

**Comment by YogruTi** [comment]
> Which docker tag are you using?
I built it based on information I found online.

**Comment by xianren78** [comment]
WG_DEFAULT_ADDRESS=10.8.0.x
NOT： WG_DEFAULT_ADDRESS=10.8.0.**0**

**Comment by YogruTi** [comment]
> WG_DEFAULT_ADDRESS=10.8.0.x 非：WG_DEFAULT_ADDRESS=10.8.0.0
Thank you for your reply. It was my negligence. The problem has been corrected.
