### ISSUE TITLE
dockerfile EXPOSEs ports 51820+51821 even when not used

### ISSUE THREAD

**Issue by dstults** [wg-easy/wg-easy#972]
**Describe the bug**

We can set env vars `WG_PORT` and `PORT` to something other than the defaults, yet the default ports are still marked as exposed even though they wouldn't actually be functional. This makes docker info/ps reports misleading.

**To Reproduce**

Run valid `docker run`

```
> WG_PORT=12345
> WEB_PORT=12346
> docker run ...
	--env WG_PORT=$WG_PORT \
        --publish 0.0.0.0:$WG_PORT:$WG_PORT \
	--env PORT=$WEB_PORT \
        --publish 0.0.0.0:$WEB_PORT:$WEB_PORT \
      ....
     ghcr.io/wg-easy/wg-easy
```

View container running and observe that the ports that aren't actually being used are marked as exposed

```
>  docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED         STATUS                  PORTS                                                                      NAMES
3737e3e9d9d4   ghcr.io/wg-easy/wg-easy                  "docker-entrypoint.s…"   2 seconds ago   Up 1 second             0.0.0.0:12345->12345/udp, 0.0.0.0:12346->12346/tcp, 51820/udp, 51821/tcp   wg-easy
```

**Expected behavior**

Maybe the dockerfile should not include the EXPOSE commands for the default ports and they should just be recommended in the docs for a default `docker run` or `docker-compose` file.

The output would then reflect reality

```
>  docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED         STATUS                  PORTS                                                NAMES
3737e3e9d9d4   ghcr.io/wg-easy/wg-easy                  "docker-entrypoint.s…"   2 seconds ago   Up 1 second             0.0.0.0:12345->12345/udp, 0.0.0.0:12346->12346/tcp   wg-easy
```

**Additional context**

Proposed fix:

Remove this from the `dockerfile`
```
# Expose Ports
EXPOSE 51820/udp
EXPOSE 51821/tcp
```

Update the `README.md` and `docker-compose*.yml` files accordingly.

**Comment by pheiduck** [comment]
Yo, if you found a way to use differnt ports would be nice if you can open a PR. So we can implement this feature. We had some issue with the implementation we had a time ago.
Would be nice to give the Feature a new start.

**Comment by pheiduck** [comment]
To you issue, due this would affect the default ports? 51820/udp 51821/tcp maybe we have to make a var for the exposed ports. I think it needs also a fallback when ports not set.

**Comment by pheiduck** [comment]
otherwise we do the suggestion from you and make `WG_PORT` a requiered option.

**Comment by pheiduck** [comment]
> The EXPOSE instruction doesn't actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published. To publish the port when running the container, use the -p flag on docker run to publish and map one or more ports, or the -P flag to publish all exposed ports and map them to high-order ports.

ref: https://docs.docker.com/reference/dockerfile/#expose

**Comment by pheiduck** [comment]
@dstults please test image with tag: `development`

**Comment by dstults** [comment]
Hey just filed that right before heading out on a road trip, will try to get some good testing in and get back to you hopefully some time soon. Thanks for the quick response!

**Comment by dstults** [comment]
✅ Test 1 successful: Only the desired-to-be-used ports showing (thank you)

```
WG_PORT=12345
WEB_PORT=12346
docker run -d \
	--name "wg-easy" \
	--env WG_HOST=mydomain.net \
	--env WG_DEFAULT_ADDRESS="192.168.69.x" \
	--env WG_DEFAULT_DNS="172.16.0.2" \
	--env WG_ALLOWED_IPS="0.0.0.0/0" \
	--volume "/deploy/src/wg-easy:/etc/wireguard" \
	--env WG_PORT=$WG_PORT \
	--publish "0.0.0.0:$WG_PORT:$WG_PORT/udp" \
	--env PORT=$WEB_PORT \
	--publish "0.0.0.0:$WEB_PORT:$WEB_PORT/tcp" \
	--env PASSWORD=password \
	--cap-add "NET_ADMIN" \
	--sysctl="net.ipv4.conf.all.src_valid_mark=1" \
	--sysctl="net.ipv4.ip_forward=1" \
	--restart unless-stopped \
	ghcr.io/wg-easy/wg-easy:develop

$ docker ps -a
CONTAINER ID   IMAGE                                 COMMAND                  CREATED              STATUS              PORTS                                                NAMES
46b7555c7256   ghcr.io/wg-easy/wg-easy:development   "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:12345->12345/udp, 0.0.0.0:12346->12346/tcp   wg-easy
```

---

❌ Test 2-1 failed:
Client could not talk to the server

Root cause: `wg0.conf` was showing still on the default port.
```
# wg show
interface: wg0
  public key: TUqNdeadbeefG3oiYiIo8B9hiuN8bJRBeegmqMvyEjI=
  private key: (hidden)
  listening port: 51820
```

Next update: I think the only other change that would be needed is the `WireGuard.js` line 98 may need changed to the env-var-set `WG_PORT` env variable (as it was hard-coded):
```
ListenPort = ${WG_PORT}
```

i.e.
<img width="358" alt="image" src="https://github.com/wg-easy/wg-easy/assets/20900852/d84d74b5-7561-4f45-bc97-40c3930d2e87">

Which I think should result in the config that let's the client connect properly (I manually edited mine using `docker exec` -- I've not attempted a full `docker build` directly on it yet but can when I get back if need be).

---

✅ Test 2-2 successful -- client connects and has a new IP address local to WG server.

```
# wg show
interface: wg0
  public key: TUqNdeadbeefG3oiYiIo8B9hiuN8bJRBeegmqMvyEjI=
  private key: (hidden)
  listening port: 12345

peer: X56++R97DXEQCzWNgoO5vdeadbeefAZYdGQtjCOLFm0=
  preshared key: (hidden)
  endpoint: 172.56.104.204:18226
  allowed ips: 192.168.69.2/32
  latest handshake: 5 minutes, 53 seconds ago
  transfer: 104.43 KiB received, 798.58 KiB sent
```

--------------

> Yo, if you found a way to use different ports would be nice if you can open a PR. So we can implement this feature. We had some issue with the implementation we had a time ago.

My apologies, I was in a rush, I will try that next time!

Let me know if anyone is having issues with that after that above mentioned change is implemented and I might still be able to help double-check either again on my setup or help anyone debug theirs.

Thanks again!

**Comment by dstults** [comment]
> EXPOSE doesn't actually publish the port. It acts as the documentation...

It's because no matter what, `--publish` (`-p`) must be used, so I think the potential for "documentation" value is not very helpful. On the opposite hand, if no ports are visible in a troubleshooter's `PORTS` then we instantly know that they aren't connecting into the container because they failed to publish any port -- having a default EXPOSE would make this difficult to troubleshoot.

> To your issue, due this would affect the default ports? 51820/udp 51821/tcp maybe we have to make a var for the exposed ports. I think it needs also a fallback when ports not set.

As just mentioned, these must be set for ports to be open no matter what because the EXPOSEs are documentary:
```
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
```

Furthermore the code does have fallback already:
```
module.exports.PORT = process.env.PORT || '51821';       // <--- sets value if PORT is falsey (eg undefined)
module.exports.WG_PORT = process.env.WG_PORT || '51820'; //        same
```

Both ports will be set to their respective defaults if not otherwise set by env vars, so I think we already have good fallback.

**Comment by pheiduck** [comment]
Published a new dev build with that changes.

**Comment by dstults** [comment]
Roger that, for my part I'll be on a longer leg of my trip and will be without power or signal possibly for up to a week. I'll set an alarm to come back here in case no one else beats me to it. Apologies and thanks again.

**Comment by dstults** [comment]
Sorry I took so long, got back 2 days later than expected and then was busy working overtime and then playing catchup with stuff at home.

It looks like you merged the changes but just as a sanity check, here's some testing against the current master with changes and against the previous master upgraded to current.

```
$ docker build . --tag wg-easy:dev
$ docker image ls
REPOSITORY                TAG           IMAGE ID       CREATED          SIZE
wg-easy                   dev           e50a64839af1   42 minutes ago   158MB
ghcr.io/wg-easy/wg-easy   development   b50d0135813f   25 hours ago     158MB
ghcr.io/wg-easy/wg-easy   latest        d397f3146680   5 weeks ago      155MB
```

I ran 3 tests, 1 on the latest git master (as a new wg-easy built on local), 1 on whatever is sitting on "development" from 25 hours ago, and 1 that will remain on the old version as a control. I used nearly identical parameters except that the ports and name incremented so that I could test them one after another.

As expected, the new master branch-built image and development image does not show ports while the old one does:

```
$ docker ps -a
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS         PORTS                                                                      NAMES
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS         PORTS                                                                      NAMES
f5b516bf65cc   wg-easy:dev                           "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   0.0.0.0:32780->32780/udp, 0.0.0.0:32781->32781/tcp                         wg-easy-1
a741a8dfad67   ghcr.io/wg-easy/wg-easy:development   "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   0.0.0.0:32782->32782/udp, 0.0.0.0:32783->32783/tcp                         wg-easy-2
ccd88c1d2d3e   ghcr.io/wg-easy/wg-easy:latest        "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   0.0.0.0:32784->32784/udp, 0.0.0.0:32785->32785/tcp, 51820/udp, 51821/tcp   wg-easy-3
```

The original master docker image is/was still showing the ports but doesn't actually work .

Testing connectivity on the brand-new wg versions:
```
wg1-user1   192.168.69.2  59 seconds ago
0 B/s 3.02 MB    0 B/s 153.57 KB

wg2-user1   192.168.18.2  1 minute ago
240 B/s 5.51 MB    336 B/s 186.36 KB
```

Both the master branch and development builds seem to work like a charm.

Thanks again so much.
