### ISSUE TITLE
[Copyright issue] a secondary distributed webui by a plagiarist

### ISSUE THREAD

**Issue by kmou424** [wg-easy/wg-easy#993]
I found a project embedded this webui without any fork, commits history, credits, copyright or license, even not mentioned original authors of wg-easy. They just simply repacked with a golang backend and built a new docker image.

Repository of that project: https://github.com/Safe3/firefly

**Comment by eandersons** [comment]
They actually announced this project themselves in #988. 😁

**Comment by pheiduck** [comment]
We don`t care about Projects there won`t collaborate with us!
