### ISSUE TITLE
Contribute my improved pure go version of wg-easy !

### ISSUE THREAD

**Issue by Safe3** [wg-easy/wg-easy#995]
This is my improved pure go version of wg-easy !
I can contribute all code to wg-easy project if you need this.

Introduction：
Single file, better performance, auto ssl, no wireguard installation dependency.

Project：https://github.com/Safe3/firefly

Screenshot：
![image](https://raw.githubusercontent.com/Safe3/firefly/main/firefly.png)

**Comment by pheiduck** [comment]
**Please stop to promot your fork here!**

**Comment by pheiduck** [comment]
If you want to make contribution you may have to make changes in a different Branch.
**But it should not infringe the licence**
